### ISSUE TITLE
Canvas keep resetting the node positions

### ISSUE THREAD

**Issue by alexk1919** [n8n-io/n8n#11936]
### Bug Description

After I move around a node or nodes and save the workflow, it resets the nodes to the previous position. 

### To Reproduce

1. Move a node
2. Save the workflow

### Expected behavior

The nodes remain where I positioned them

### Operating System

Windows 11

### n8n Version

1.69.2

### Node.js Version

na

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @alexk1919,

We have created an internal ticket to look into this which we will be tracking as "GHC-514"

**Comment by McCalebTheSecond** [comment]
I noticed this issue but only when I move multiple nodes at once.  If I move one node at a time, it saves the position but if I select many nodes and move, the position gets reset.  I'm using new canvas and version 1.69.2

**Comment by alexk1919** [comment]
New canvasWill try the single node movement and see if it works On Nov 29, 2024, at 1:53 AM, Tomi Turtiainen ***@***.***> wrote:﻿
Hi @alexk1919 ! Thank for your report. Are you using the new or old canvas? You can see that from the workflow settings menu
image.png (view on web)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

The information transmitted is intended solely for the individual(s) or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of or taking action in reliance upon this information by persons or entities other than the intended recipient maybe unlawful and is prohibited. If you have received this email in error please contact the sender and delete the material from any computer.  By reading this email, you, the recipient agree to keep all information received herein as strictly confidential and proprietary and understand that the sender has declared any contacts, clients, internal procedures, information, programs, attachments and any transactions to which they relate, to be classified as fully protected Corporate or Trade Secrets in accordance with U.S. H.R. 3723 and international standards for fair business, confidentiality, non-disclosure and non-circumvention including the I.C.C. and its publication 664. If you the recipient, do not agree to this, delete this email and any attachments immediately.

**Comment by Stockotaco** [comment]
I'm experiencing this as well. 

On the new canvas. 

If you select multiple nodes and move them, the canvas does not prompt you to save. Nor does it save.

[https://share.zight.com/BlumjEGd](https://share.zight.com/BlumjEGd)

**Comment by xhzkp** [comment]
I encountered the same issue.

**Comment by tomi** [comment]
This has been fixed in #11871 and released in `1.70.0` (tho I recommend skipping that and using `1.70.1` instead)

**Comment by xhzkp** [comment]
> This has been fixed in #11871 and released in `1.70.0` (tho I recommend skipping that and using `1.70.1` instead)

I am using the latest version 1.70.1 and still encountering a similar issue. The problem is very noticeable when there are many nodes. I will record a demonstration shortly.

**Comment by tomi** [comment]
@xhzkp I was not able to reproduce this on `1.70.1` anymore. Could you provide a WF and steps to reproduce this please 🙏

**Comment by xhzkp** [comment]
> @xhzkp I was not able to reproduce this on `1.70.1` anymore. Could you provide a WF and steps to reproduce this please 🙏
Apologies for the mistake in my previous message. I just tested it: there is an issue in version 1.69.2, but the problem has been resolved in version 1.70.1. Thanks to the developers for their time and effort in fixing this.
