### ISSUE TITLE
NODES_INCLUDE not working!

### ISSUE THREAD

**Issue by zakariamehbi** [n8n-io/n8n#12713]
### Bug Description

Hello, I have a problem with NODES_INCLUDE not working, every time I set my list and start my docker container, I get an error when trying to create a trigger.

```
Error cannot read properties of undefined (reading 'match')
```

```
- NODES_INCLUDE=["n8n-nodes-base.gmailTrigger","n8n-nodes-base.gmail","n8n-nodes-base.googleSheets","n8n-nodes-base.httpRequest","n8n-nodes-base.if","n8n-nodes-base.code","n8n-nodes-base.set","n8n-nodes-base.merge","n8n-nodes-base.emailSend","n8n-nodes-base.dateTime","n8n-nodes-base.webhook","n8n-nodes-base.manualTrigger","n8n-nodes-base.scheduleTrigger"]
```

### To Reproduce

1. Create a docker-compose.yml
2. Add this config: 
```
version: '3.1'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - NODES_INCLUDE=["n8n-nodes-base.gmailTrigger","n8n-nodes-base.gmail","n8n-nodes-base.googleSheets","n8n-nodes-base.httpRequest","n8n-nodes-base.if","n8n-nodes-base.code","n8n-nodes-base.set","n8n-nodes-base.merge","n8n-nodes-base.emailSend","n8n-nodes-base.dateTime","n8n-nodes-base.webhook","n8n-nodes-base.manualTrigger","n8n-nodes-base.scheduleTrigger"]
    volumes:
      - ~/.n8n:/home/node/.n8n
```
3. start the container
4. try creating a workflow, any trigger will output an error

### Expected behavior

- The list of items included in NODES_INCLUDE shows up, and all the rest disappear.
- Clicking a trigger doesn't show an error

### Operating System

Mac OS

### n8n Version

1.74.3

### Node.js Version

23.6.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @zakariamehbi,

We have created an internal ticket to look into this which we will be tracking as "N8N-8169"

**Comment by zakariamehbi** [comment]
Thank you, after further investigation, NODES_EXCLUDE doesn't exclude anything but doesn't error when trying to create a trigger.

**Comment by Joffcom** [comment]
Hey @zakariamehbi 

I think when using the exclude option while the node appears in the list if you try to use it you will get an error.

I have not tested the include option yet but if you add a node that is on the include list does it also error?

**Comment by Joffcom** [comment]
Hey @zakariamehbi 

Can you try 1.75.0 this should have been fixed as part of #12544

**Comment by zakariamehbi** [comment]
hey @Joffcom, i'm using the latest docker image, so i should be on the latest version of n8n, but still having this issue.

<img width="422" alt="Image" src="https://github.com/user-attachments/assets/5f7a86df-a744-411b-9d60-a29c4e99e924" />

**Comment by despairblue** [comment]
> after testing with the fixed version 1.75.2 instead of the latest image (for some reason, it's not the latest?)

Releases are tagged as `next` for a week before they are tagged as `latest`. That is to iron out issues before most people start using it.

**Comment by tomi** [comment]
@zakariamehbi I'm going to close this one as it should be fixed now. I can reopen if the issue does reappear.

**Comment by guilhermevescovi** [comment]
I am running version 1.100.1

My docker environment variable NODES_EXCLUDE:

NODES_EXCLUDE=["n8n-nodes-base.executeCommand", "n8n-nodes-base.scheduleTrigger", "n8n-nodes-base.manualTrigger"]

1. I see Manual Trigger available to add as a node from the list, I expected it not to show 
2. I add it to simulate user doing something they should not, then I try to execute it
3. Problem running workflow: "Unrecognized node type: n8n-nodes-base.manualTrigger"

Is this related to this issue?

<img width="691" alt="Image" src="https://github.com/user-attachments/assets/b0b090a9-5c0f-474c-88b8-3efd43485ce8" />

**Comment by tomi** [comment]
@guilhermevescovi out of curiosity, what's the use case for excluding the Manual Trigger node?

**Comment by guilhermevescovi** [comment]
@tomi No case on that, I was just testing the application function with any trigger node.
