### ISSUE TITLE
Postgres node with ssh tunnel - random Connection refused

### ISSUE THREAD

**Issue by andrsp** [n8n-io/n8n#12807]
### Bug Description

I'm using postgres node in workflows with option to connect via ssh tunnel.
After upgrading from 1.73 to 1.75.2 (and 1.76.0) some of workflow executions started failing on postgres node with error which looks like this:
```
Connection refused
127.0.0.1:44563
```
looks like ssh tunnel closed after some time (5m?) and reconnecting not working as expected

error log from node:

```
Node type: n8n-nodes-base.postgres
Node version: 2.5 (Latest)
n8n version: 1.76.0 (Self Hosted)

Stack trace

NodeOperationError: Connection refused
 at parsePostgresError (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+client-sts@3.666.0_@aws-sdk+credential-provi_itzq4gjm3572fjrrbfktkg2f4u/node_modules/n8n-nodes-base/dist/nodes/Postgres/v2/helpers/utils.js:102:12)
 at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+client-sts@3.666.0_@aws-sdk+credential-provi_itzq4gjm3572fjrrbfktkg2f4u/node_modules/n8n-nodes-base/dist/nodes/Postgres/v2/helpers/utils.js:205:31
 at processTicksAndRejections (node:internal/process/task_queues:95:5)
 at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+client-sts@3.666.0_@aws-sdk+credential-provi_itzq4gjm3572fjrrbfktkg2f4u/node_modules/n8n-nodes-base/dist/nodes/Postgres/v2/actions/database/select.operation.js:85:12)
 at ExecuteContext.router (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+client-sts@3.666.0_@aws-sdk+credential-provi_itzq4gjm3572fjrrbfktkg2f4u/node_modules/n8n-nodes-base/dist/nodes/Postgres/v2/actions/router.js:59:26)
 at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+client-sts@3.666.0_@aws-sdk+credential-provi_itzq4gjm3572fjrrbfktkg2f4u/node_modules/n8n-nodes-base/dist/nodes/Postgres/v2/PostgresV2.node.js:16:16)
 at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:632:19)
 at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:890:51
 at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/dist/execution-engine/workflow-execute.js:1224:20
```

switching to direct connection to postgres without tunnel fixes problem

### To Reproduce

1. set up postgres credentials with ssh tunnel
2. set up workflow with postgres node using these credentials
3. execute flow continuously for 5-10 minutes
4. after ~5min you will start see errors 

### Expected behavior

postgres node works same way with or without ssh tunnel

### Operating System

ubuntu 22.04 / docker

### n8n Version

1.76

### Node.js Version

2.5

### Database

PostgreSQL

### Execution mode

queue

**Comment by akhudolev** [comment]
Faced with same issue after upgrading to 1.75.2

**Comment by akhudolev** [comment]
Looks like https://github.com/n8n-io/n8n/pull/12346 change caused this issue

**Comment by ohmyboroda** [comment]
Same problem.

**Comment by scropion86** [comment]
@Joffcom is downgrade to 1.72 is possible, currently i am running 1.76.2
and is this will resolve my issue until the fix i released

**Comment by ohmyboroda** [comment]
Moved the database to Hertzner and opened it to the public. The problem persists without Cloudflare.
I think this is a critical error? It is impossible to work with data collecting.

**Comment by daveahmadi** [comment]
We are having the same issue with postgres db connections via ssh on a cloud hosted pro plan on 1.78.1 - We were also at either 1.72 or 1.73 prior to upgrading and had no Postgres connectivity issues. Also, looking to downgrade versions if a fix is not on the horizon. Many of our production workflows need to be run manually and in small chunks in order to complete.

**Comment by Tim-nocode** [comment]
Same problem here

**Comment by lmuehleisen** [comment]
Same problem here

**Comment by pdwarf** [comment]
We just released [the ability to SSH tunnel idle timeout](https://github.com/n8n-io/n8n/pull/14522) in `1.89.0`. For anyone affected, can you check if this resolves it for you?

**Comment by Tim-nocode** [comment]
Hello @pdwarf 

I still faced this issue

![Image](https://github.com/user-attachments/assets/14aa5804-e4db-4afe-9b5e-e24a01c21551)

![Image](https://github.com/user-attachments/assets/478bc48c-ae7b-430c-8f10-41af55d8f3d8)

**Comment by daveahmadi** [comment]
@pdwarf - is this environment variable configurable in n8n Cloud? We do not self-host n8n. 

Also, I'm not sure how a configurable idle timeout would help in this situation. Even when we run consecutive (not parallel) Postgres operations, the error gets thrown around the 5 minute mark. For example, "Postgres operation 1" completes in 2 minutes, "Postgres operation 2" then starts and completes in 2 minutes and then "Postgres operation 3" starts and the connection refused error will be thrown shortly afterwards. This doesn't just happen when a single long-running query is executing for more than 5 minutes.

**Comment by RobyRPA** [comment]
Hi, me again.
I think there might be a bug related to how tunnels are closed.
As I mentioned before, everything works fine until at some point it just stops.
I found that the only way to make it work again is to open the credential, change any minor setting (like max connections), save it, and then test the connection.

My guess is that testing the credential forces n8n to close all open connections and reestablish them.
So maybe there's an issue with how the Postgres node opens a connection and then fails to close it properly?

Is there any solution?

Thank you

**Comment by huksley** [comment]
I am also experiencing the same issue. Additionally ed25519 keys does not work and it is not in the docs, so I needed to recreate the key. Checking the connecting in the node (Retry button) works ok, but workflow says connection refused.

**Comment by scropion86** [comment]
@despairblue 

not yet fixing the issue I am running 1.97.1
and still getting same error

![image](https://github.com/user-attachments/assets/aa66620f-80af-4398-b918-bceb49f3130d)

`
 Other info
Node type

n8n-nodes-base.postgres

Node version

2.5 (Latest version: 2.6)

n8n version

1.97.1 (Self Hosted)

Time

6/15/2025, 9:40:21 AM

Stack trace
```
NodeOperationError: Connection refused 
	at parsePostgresError (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+credential-providers@3.808.0_asn1.js@5_12b981d6b49d407a163f4d5244314033/node_modules/n8n-nodes-base/nodes/Postgres/v2/helpers/utils.ts:124:9) 
	at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+credential-providers@3.808.0_asn1.js@5_12b981d6b49d407a163f4d5244314033/node_modules/n8n-nodes-base/nodes/Postgres/v2/helpers/utils.ts:279:19 
	at processTicksAndRejections (node:internal/process/task_queues:95:5) 
	at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+credential-providers@3.808.0_asn1.js@5_12b981d6b49d407a163f4d5244314033/node_modules/n8n-nodes-base/nodes/Postgres/v2/actions/database/executeQuery.operation.ts:149:9) 
	at ExecuteContext.router (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+credential-providers@3.808.0_asn1.js@5_12b981d6b49d407a163f4d5244314033/node_modules/n8n-nodes-base/nodes/Postgres/v2/actions/router.ts:40:17) 
	at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-nodes-base@file+packages+nodes-base_@aws-sdk+credential-providers@3.808.0_asn1.js@5_12b981d6b49d407a163f4d5244314033/node_modules/n8n-nodes-base/nodes/Postgres/v2/PostgresV2.node.ts:26:10) 
	at WorkflowExecute.runNode (/usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:1185:9) 
	at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:1534:27 
	at /usr/local/lib/node_modules/n8n/node_modules/.pnpm/n8n-core@file+packages+core_openai@4.78.1_encoding@0.1.13_zod@3.24.1_/node_modules/n8n-core/src/execution-engine/workflow-execute.ts:2098:11

```

**Comment by despairblue** [comment]
@scropion86 The fix was only released in 1.99 yesterday, which is in beta right now. You could try that version or wait until it's stable next week. 🙏🏾

**Comment by janober** [comment]
Fix got released with [`n8n@1.99.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.99.0)
