### ISSUE TITLE
High level node isn't staying connected

### ISSUE THREAD

**Issue by mmda1404** [n8n-io/n8n#13613]
## Describe the problem/error/question
The high level module is not staying connected...it's as if it keeps changing the client secret...when I put the correct one in it connects but then when I add it to my workflow it says it isn't connected and I see the client secret is much longer than the actual one. I add the secret in again, it connects but then when I try to edit the nodes it says it isn't connected

## What is the error message (if any)?
Unable to sign without access token

## Please share your workflow/screenshots/recording
https://www.loom.com/share/d24ca2e7400b4f8b9ee497780d87348e?sid=203f85cc-78e5-4ded-8555-b83507406d4c
```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
```
{
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "6c85e095-2c69-4837-80bd-7fe44b586658",
        "options": {}
      },
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [
        -320,
        -60
      ],
      "id": "fa187836-b67f-4c9d-851f-c65d25d3e2fa",
      "name": "Webhook",
      "webhookId": "6c85e095-2c69-4837-80bd-7fe44b586658"
    },
    {
      "parameters": {
        "jsCode": "// Loop over each input item\nfor (const item of $input.all()) {\n  // Retrieve the array from $json.body[\"Related Documents\"]\n  const relatedDocumentsArray = item.json.body[\"Related Documents\"];\n\n  // Check if the variable is indeed an array\n  if (Array.isArray(relatedDocumentsArray)) {\n    // Join the array elements into a single string separated by newlines\n    item.json.body[\"Related Documents\"] = relatedDocumentsArray.join(\"\\n\");\n  }\n}\n\nreturn $input.all();\n"
      },
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        -100,
        -60
      ],
      "id": "e228819a-f508-41ae-917b-794b9a9ddd01",
      "name": "Code"
    },
    {
      "parameters": {
        "email": "={{ $json.body.email }}",
        "additionalFields": {
          "customFields": {
            "values": [
              {
                "fieldId": {
                  "__rl": true,
                  "mode": "list",
                  "value": ""
                }
              }
            ]
          }
        },
        "requestOptions": {}
      },
      "type": "n8n-nodes-base.highLevel",
      "typeVersion": 2,
      "position": [
        120,
        -60
      ],
      "id": "07478a01-2d5d-4348-9607-cc45988bbcd4",
      "name": "HighLevel",
      "credentials": {
        "highLevelOAuth2Api": {
          "id": "4IozMHrB9fUCAtBv",
          "name": "HighLevel account 4"
        }
      }
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "HighLevel",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "Webhook": [
      {
        "headers": {
          "host": "merakiai.app.n8n.cloud",
          "user-agent": "axios/1.7.7",
          "content-length": "3009",
          "accept": "application/json, text/plain, */*",
          "accept-encoding": "gzip, br",
          "cdn-loop": "cloudflare; loops=1; subreqs=1",
          "cf-connecting-ip": "34.29.79.49",
          "cf-ew-via": "15",
          "cf-ipcountry": "US",
          "cf-ray": "919924d4f596636e-ORD",
          "cf-visitor": "{\"scheme\":\"https\"}",
          "cf-worker": "n8n.cloud",
          "content-type": "application/json",
          "x-forwarded-for": "34.29.79.49, 172.70.179.156",
          "x-forwarded-host": "merakiai.app.n8n.cloud",
          "x-forwarded-port": "443",
          "x-forwarded-proto": "https",
          "x-forwarded-server": "traefik-prod-users-gwc-11-cb7f6dc87-4tgl8",
          "x-is-trusted": "yes",
          "x-real-ip": "34.29.79.49"
        },
        "params": {},
        "query": {},
        "body": {
          "Case Claim Name": "Test 7",
          "Case/Claim No.": "7",
          "Appointment Type": "Deposition",
          "Appointment Date": "2025-02-28",
          "From what language": "Chinese (Cantonese)",
          "To what language": "English",
          "Job Details": "This is test 7- ignore please",
          "Related Documents": [
            "https://services.leadconnectorhq.com/documents/download/WMdbuuZPWhQuYjKSOzaa",
            "https://services.leadconnectorhq.com/documents/download/JK7JNZCWQkUwlWT8mNiO",
            "https://services.leadconnectorhq.com/documents/download/rXOcdmf5mkdT0Pzlug3F",
            "https://services.leadconnectorhq.com/documents/download/bSMkHSO6VGC1RYIKySQ5"
          ],
          "Appointment Time": "09:30",
          "Your Message": "",
          "Mobile Phonme": "",
          "Fax": "",
          "Language": "",
          "MVP CONTACT ID": "",
          "Test documents ": "",
          "Files To Send": "",
          "contact_id": "eMu0h6dQ2T8mVXH6gQXY",
          "first_name": "Michelle",
          "last_name": "Test7",
          "full_name": "Michelle Test7",
          "email": "test7@gmail.com",
          "phone": "+33666983165",
          "tags": "",
          "country": "US",
          "timezone": "Europe/Paris",
          "date_created": "2025-02-25T20:05:23.620Z",
          "company_name": "Test 7",
          "contact_source": "request an interpreter",
          "full_address": "",
          "contact_type": "lead",
          "location": {
            "name": "MVP Translations, INC.",
            "address": "P.O. Box 677154",
            "city": "Orlando",
            "state": "FL",
            "country": "US",
            "postalCode": "32867",
            "fullAddress": "P.O. Box 677154, Orlando FL 32867",
            "id": "wPVQOcsop9mrdP6lXxxo"
          },
          "workflow": {
            "id": "5f48ee29-61cb-4ecf-99da-49f2a6ef9074",
            "name": "Form Submissions ->Webhook (N8N)"
          },
          "triggerData": {},
          "contact": {
            "attributionSource": {
              "sessionSource": "Referral",
              "url": "https://link.merakimarketingservice.com/widget/form/dNklLDBHpfEZsk5uJvt0",
              "campaign": null,
              "utmSource": null,
              "utmMedium": null,
              "utmContent": null,
              "utmTerm": null,
              "utmKeyword": null,
              "utmMatchtype": null,
              "referrer": "https://leadgen-apps-form-survey-builder.leadconnectorhq.com",
              "gclid": null,
              "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
              "ip": "2a02:842a:42ce:4601:24f5:6afc:7f9e:ec",
              "gaClientId": "GA1.2.783162188.1715116151",
              "medium": "form",
              "mediumId": "dNklLDBHpfEZsk5uJvt0",
              "adName": null,
              "adGroupId": null,
              "adId": null,
              "gbraid": null,
              "wbraid": null
            },
            "lastAttributionSource": {
              "sessionSource": "Referral",
              "url": "https://link.merakimarketingservice.com/widget/form/dNklLDBHpfEZsk5uJvt0",
              "utmSource": null,
              "utmMedium": null,
              "utmContent": null,
              "utmTerm": null,
              "utmKeyword": null,
              "utmMatchtype": null,
              "referrer": "https://leadgen-apps-form-survey-builder.leadconnectorhq.com",
              "gclid": null,
              "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
              "ip": "2a02:842a:42ce:4601:24f5:6afc:7f9e:ec",
              "gaClientId": "GA1.2.783162188.1715116151",
              "medium": "form",
              "mediumId": "dNklLDBHpfEZsk5uJvt0",
              "adName": null,
              "adGroupId": null,
              "adId": null,
              "gbraid": null,
              "wbraid": null
            }
          },
          "attributionSource": {},
          "customData": {
            "First Name": "Michelle",
            "Last Name": "Test7",
            "Email": "test7@gmail.com",
            "Phone": "+33 6 66 98 31 65",
            "Documents": "https://services.leadconnectorhq.com/documents/download/WMdbuuZPWhQuYjKSOzaa",
            "Fields To Send": ""
          }
        },
        "webhookUrl": "https://merakiai.app.n8n.cloud/webhook-test/6c85e095-2c69-4837-80bd-7fe44b586658",
        "executionMode": "test"
      }
    ]
  },
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "6f015927d09e8c2d4a556816ad5301603dda9cbe495f0710833d8495a0acb455"
  }
}

## Share the output returned by the last node

there isn't one.

### core

- n8nVersion: 1.74.4
- platform: npm
- nodeJsVersion: 20.18.2
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

### client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/133.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-03-01T14:01:09.307Z}

**Comment by Joffcom** [comment]
Hey @mmda1404,

We have created an internal ticket to look into this which we will be tracking as "GHC-1015"

**Comment by Joffcom** [comment]
Hey @mmda1404 

Can you do an update it looks like you are on 1.74.4 and this is something we fixed a couple of versions ago.

**Comment by mmda1404** [comment]
Hi,

I did an update and it is still not working. (Running version ***@***.***)

**Comment by mmda1404** [comment]
now I tried the very latest beta version and it is still not working:
https://www.loom.com/share/6e45154976eb4c65922d3469c796f9f2?sid=e7293191-16da-4fe0-8c37-2e8d233e567a

**Comment by mmda1404** [comment]
I have tried many times now in both of the projects I have and it just
keeps doing the same thing. Please help! I need to get this working for a
client.

**Comment by mmda1404** [comment]
Hi

Yes, I realized that afterwards but I still have tried several times after
my video because I need this to work asap. I have started from scratch
several times. Thanks

*Finder - Downloads - 4 March 2025* - Watch Video
<https://www.loom.com/share/f9ab8d94c8b947db9e379b27ef789501>
<https://www.loom.com/share/f9ab8d94c8b947db9e379b27ef789501?utm_medium=gif>

Here's the code:

{
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "baa4051f-ebc0-48c1-9956-88a9227904a7",
        "options": {}
      },
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [
        -320,
        -60
      ],
      "id": "467712a8-86d1-4392-8728-3e592a01e624",
      "name": "Webhook",
      "webhookId": "baa4051f-ebc0-48c1-9956-88a9227904a7"
    },
    {
      "parameters": {
        "jsCode": "// Loop over each input item\nfor (const item of
$input.all()) {\n  // Retrieve the array from $json.body[\"Related
Documents\"]\n  const relatedDocumentsArray = item.json.body[\"Related
Documents\"];\n\n  // Check if the variable is indeed an array\n  if
(Array.isArray(relatedDocumentsArray)) {\n    // Join the array elements
into a single string separated by newlines\n    item.json.body[\"Related
Documents\"] = relatedDocumentsArray.join(\"\\n\");\n  }\n}\n\nreturn
$input.all();\n"
      },
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        -100,
        -60
      ],
      "id": "d646bfef-d2a7-4928-8050-40726bfd728c",
      "name": "Code"
    },
    {
      "parameters": {
        "email": "={{ $json.body.email }}",
        "additionalFields": {
          "customFields": {
            "values": [
              {
                "fieldId": {
                  "__rl": true,
                  "mode": "list",
                  "value": ""
                }
              }
            ]
          }
        },
        "requestOptions": {}
      },
      "type": "n8n-nodes-base.highLevel",
      "typeVersion": 2,
      "position": [
        120,
        -60
      ],
      "id": "ac6e91dc-56cd-47d1-bbdd-a51fcb91056b",
      "name": "HighLevel",
      "credentials": {
        "highLevelOAuth2Api": {
          "id": "GrNjqbsaovfKPO3N",
          "name": "MVP Translations"
        }
      }
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "HighLevel",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "Webhook": [
      {
        "headers": {
          "host": "merakiai.app.n8n.cloud",
          "user-agent": "axios/1.7.7",
          "content-length": "3009",
          "accept": "application/json, text/plain, */*",
          "accept-encoding": "gzip, br",
          "cdn-loop": "cloudflare; loops=1; subreqs=1",
          "cf-connecting-ip": "34.58.14.109",
          "cf-ew-via": "15",
          "cf-ipcountry": "US",
          "cf-ray": "91b47ab895c835b5-ORD",
          "cf-visitor": "{\"scheme\":\"https\"}",
          "cf-worker": "n8n.cloud",
          "content-type": "application/json",
          "x-forwarded-for": "34.58.14.109, 172.69.17.170",
          "x-forwarded-host": "merakiai.app.n8n.cloud",
          "x-forwarded-port": "443",
          "x-forwarded-proto": "https",
          "x-forwarded-server": "traefik-prod-users-gwc-11-cb7f6dc87-lq44n",
          "x-is-trusted": "yes",
          "x-real-ip": "34.58.14.109"
        },
        "params": {},
        "query": {},
        "body": {
          "Case Claim Name": "Test 7",
          "Case/Claim No.": "7",
          "Appointment Type": "Deposition",
          "Appointment Date": "2025-02-28",
          "From what language": "Chinese (Cantonese)",
          "To what language": "English",
          "Job Details": "This is test 7- ignore please",
          "Related Documents": [
            "
https://services.leadconnectorhq.com/documents/download/WMdbuuZPWhQuYjKSOzaa
",
            "
https://services.leadconnectorhq.com/documents/download/JK7JNZCWQkUwlWT8mNiO
",
            "
https://services.leadconnectorhq.com/documents/download/rXOcdmf5mkdT0Pzlug3F
",
            "
https://services.leadconnectorhq.com/documents/download/bSMkHSO6VGC1RYIKySQ5
"
          ],
          "Appointment Time": "09:30",
          "Your Message": "",
          "Mobile Phonme": "",
          "Fax": "",
          "Language": "",
          "MVP CONTACT ID": "",
          "Test documents ": "",
          "Files To Send": "",
          "contact_id": "eMu0h6dQ2T8mVXH6gQXY",
          "first_name": "Michelle",
          "last_name": "Test7",
          "full_name": "Michelle Test7",
          "email": ***@***.***",
          "phone": "+33666983165",
          "tags": "",
          "country": "US",
          "timezone": "Europe/Paris",
          "date_created": "2025-02-25T20:05:23.620Z",
          "company_name": "Test 7",
          "contact_source": "request an interpreter",
          "full_address": "",
          "contact_type": "lead",
          "location": {
            "name": "MVP Translations, INC.",
            "address": "P.O. Box 677154",
            "city": "Orlando",
            "state": "FL",
            "country": "US",
            "postalCode": "32867",
            "fullAddress": "P.O. Box 677154, Orlando FL 32867",
            "id": "wPVQOcsop9mrdP6lXxxo"
          },
          "workflow": {
            "id": "5f48ee29-61cb-4ecf-99da-49f2a6ef9074",
            "name": "Form Submissions ->Webhook (N8N)"
          },
          "triggerData": {},
          "contact": {
            "attributionSource": {
              "sessionSource": "Referral",
              "url": "
https://link.merakimarketingservice.com/widget/form/dNklLDBHpfEZsk5uJvt0",
              "campaign": null,
              "utmSource": null,
              "utmMedium": null,
              "utmContent": null,
              "utmTerm": null,
              "utmKeyword": null,
              "utmMatchtype": null,
              "referrer": "
https://leadgen-apps-form-survey-builder.leadconnectorhq.com",
              "gclid": null,
              "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
              "ip": "2a02:842a:42ce:4601:24f5:6afc:7f9e:ec",
              "gaClientId": "GA1.2.783162188.1715116151",
              "medium": "form",
              "mediumId": "dNklLDBHpfEZsk5uJvt0",
              "adName": null,
              "adGroupId": null,
              "adId": null,
              "gbraid": null,
              "wbraid": null
            },
            "lastAttributionSource": {
              "sessionSource": "Referral",
              "url": "
https://link.merakimarketingservice.com/widget/form/dNklLDBHpfEZsk5uJvt0",
              "utmSource": null,
              "utmMedium": null,
              "utmContent": null,
              "utmTerm": null,
              "utmKeyword": null,
              "utmMatchtype": null,
              "referrer": "
https://leadgen-apps-form-survey-builder.leadconnectorhq.com",
              "gclid": null,
              "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
              "ip": "2a02:842a:42ce:4601:24f5:6afc:7f9e:ec",
              "gaClientId": "GA1.2.783162188.1715116151",
              "medium": "form",
              "mediumId": "dNklLDBHpfEZsk5uJvt0",
              "adName": null,
              "adGroupId": null,
              "adId": null,
              "gbraid": null,
              "wbraid": null
            }
          },
          "attributionSource": {},
          "customData": {
            "First Name": "Michelle",
            "Last Name": "Test7",
            "Email": ***@***.***",
            "Phone": "+33 6 66 98 31 65",
            "Documents": "
https://services.leadconnectorhq.com/documents/download/WMdbuuZPWhQuYjKSOzaa
",
            "Fields To Send": ""
          }
        },
        "webhookUrl": "
https://merakiai.app.n8n.cloud/webhook-test/baa4051f-ebc0-48c1-9956-88a9227904a7
",
        "executionMode": "test"
      }
    ]
  },
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId":
"6f015927d09e8c2d4a556816ad5301603dda9cbe495f0710833d8495a0acb455"
  }
}

**Comment by Joffcom** [comment]
Hey @mmda1404,

So looking at that video it isn't that it isn't staying connected but instead that the custom fields are not working? If that is the case this is a known issue that we have not yet resolved but we have another ticket open for this somewhere that I will link this to.

**Comment by mmda1404** [comment]
Hi,

Will I know when this is fixed? I am anxious to get this automation working.

**Comment by Joffcom** [comment]
Closing as this a duplicate of #[12903](https://github.com/n8n-io/n8n/issues/12903) which should be resolved very soon
