### ISSUE TITLE
"Let the model define this parameter" option is not showing in my any workflow

### ISSUE THREAD

**Issue by LuxmiShanker** [n8n-io/n8n#14358]
### Bug Description

![Image](https://github.com/user-attachments/assets/a12550d3-4225-4b28-824b-cb473098bd4a)

Hi,
I am running n8n on Docker, but it is not showing the three star button (let the model define this parameter) in any workflow. Can you please resolve this issues ASAP?

Thanks,
Luxmi Shanker

### To Reproduce

Go to Brave Search Execute Tool
Operation: Execute Tool
Tool Name: {{ $fromAI("tool", "the tool selected")}}
Tool Parameters: <**ISSUE is here. Not the three star button (let the model define this parameter)** >

### Expected behavior

![Image](https://github.com/user-attachments/assets/327c2ca2-b049-476d-8d85-c2df56adf45c)

You can check in this image, the three star button (let the model define this parameter) is working fine. I was running n8n on Elestio in this image. 

### Operating System

Windows 11

### n8n Version

1.85.4

### Node.js Version

v22.13.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @LuxmiShanker,

We have created an internal ticket to look into this which we will be tracking as "GHC-1433"

**Comment by one-ia** [comment]
I got the same problem , with MCP Client, I have the latest version  of n8n and mcp client, please help!


![Image](https://github.com/user-attachments/assets/80bc706d-4e7b-40dc-96a1-14a502a8c30f)

**Comment by one-ia** [comment]
I have the same problem, un 1.88 version with MCP Client 0.1.19 , 

![Image](https://github.com/user-attachments/assets/9be227ab-d8a4-4bb0-9624-65ef3ed8291a)

**Comment by tingwei161803** [comment]
I have the same problem with n8n 1.88 and mcp node 0.1.19

**Comment by rv192** [comment]
> I have the same problem with n8n 1.88 and mcp node 0.1.19 The star didn't show


same as you, waiting for a fix.

**Comment by Jdavid77** [comment]
Facing the same issue!!

**Comment by dmota13** [comment]
I am having same issue. just disappeared

**Comment by babyfengfjx** [comment]
Hope for an early fix.🙏🙏Looking forward to using the mcp service

**Comment by ernyeizoli** [comment]
same issue pls fix

**Comment by Redpills88** [comment]
Same issue here, any fix available?

**Comment by ykaratasykaratas** [comment]
I have the same problem. If you find a solution, please share.

**Comment by Jungleislander** [comment]
I also have the same problem, commenting here to help drive the urgency of the fix...

**Comment by asterd** [comment]
same problem on 1.90.2.. please fix it!

**Comment by Jungleislander** [comment]
Side note to everyone who is blocked on this - it absolutely needs to be fixed, but the workaround I've found for now is to downgrade my n8n version, which restores the option. I realize that might not be viable for everyone though.

**Comment by asterd** [comment]
@Jungleislander can you share the right version?

**Comment by nateritter** [comment]
@asterd I've heard prior to 1.88

**Comment by nateritter** [comment]
I had trouble with the workaround... but simplifying to `{{ $fromAI('Tool_Parameters') }}` did the job. 

![Image](https://github.com/user-attachments/assets/b6b8ac1c-7eac-4882-9b1b-0c2b183865af)

**Comment by Jungleislander** [comment]
@asterd I went aaaaaall the way back to 1.83.2.  There may be more recent versions that still have it though...

**Comment by asterd** [comment]
> I had trouble with the workaround... but simplifying to `{{ $fromAI('Tool_Parameters') }}` did the job.
> 
> ![Image](https://github.com/user-attachments/assets/b6b8ac1c-7eac-4882-9b1b-0c2b183865af)

So, is something like "It's not a bug, it's an undocumented feature"?

**Comment by nateritter** [comment]
The bug is that the option to click the Detect Automatically isn't working. For sure. But under the hood it seems this is kinda what it's doing anyway. This is definitely a workaround.

**Comment by heyviet** [comment]
Hey guys, make sure you check your adblocker settings and disable it for your n8n url. This made the icon reappear for me.

**Comment by AntonDVP** [comment]
Same issue here. Self-hosted n8n on my web server. 

![Image](https://github.com/user-attachments/assets/eb1ec632-2f26-434a-bc33-bdad84d201b6)

**Comment by Joffcom** [comment]
This was fixed in 1.92.0 which was released today, if you see this issue after upgrading let me know and we can open this again

**Comment by victoralvelais** [comment]
Working for me on 1.92.0 - Win10 - docker, great work!

**Comment by flywin8** [comment]
> This was fixed in 1.92.0 which was released today, if you see this issue after upgrading let me know and we can open this again

Just upgraded to 1.92.1, the problem still exists, the button does not display

**Comment by gmgngmgn** [comment]
I upgraded to the latest version 1.91.3 and this issue remains

**Comment by vkimone** [comment]
The same issue still occurs in version 1.94.1.

**Comment by miamilabs** [comment]
spend so many hours on debugging!
Just intalled 1.99 but i cant manage to see it. Was this one fixed already?

**Comment by dkudosz** [comment]
Same issue:
- n8nVersion: 1.107.2
- platform: docker (self-hosted)
- nodeJsVersion: 22.17.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/139.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-08-15T18:13:38.598Z

Running on localhost - no ad blocker
