### ISSUE TITLE
⛓️‍💥🐛 Item linking breaks in Execute Sub-workflow node

### ISSUE THREAD

**Issue by pemontto** [n8n-io/n8n#14568]
### Bug Description

Item linking can break when calling sub workflows with mode `Run once with all items`. This is non-obvious and silently fails.

It seems the execute workflow node naively returns the pariedItems from the last node in the sub-workflow, which doesn't get resolved to the triggered input. This means item linking will break if you sub workflow:
1. changes the order of items
2. filters some items

Effectively the parent workflow can trace the pairedItem path through the child workflow, so takes the returned pairedItems at face value 😢

### To Reproduce

- Create a parent workflow with a list of 6 post IDs in `Create Data` <img width="1470" alt="Image" src="https://github.com/user-attachments/assets/795bcdb1-77e4-4210-a50f-5a770fe0563f" />

<details>
<summary>Parent workflow JSON</summary>

```json
{
  "nodes": [
    {
      "parameters": {
        "jsCode": "return [\n  {json: {_postId: 1}},\n  {json: {_postId: 2}},\n  {json: {_postId: 3}},\n  {json: {_postId: 4}},\n  {json: {_postId: 5}},\n  {json: {_postId: 6}}\n]"
      },
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        0,
        -240
      ],
      "id": "4cf01608-f335-4099-abf4-30ecf318a667",
      "name": "Create Data"
    },
    {
      "parameters": {
        "workflowId": {
          "__rl": true,
          "value": "pkIgVSKKNMBYfgPq",
          "mode": "list",
          "cachedResultName": "Drop Some Stuff Sub Workflow"
        },
        "workflowInputs": {
          "mappingMode": "defineBelow",
          "value": {},
          "matchingColumns": [],
          "schema": [],
          "attemptToConvertTypes": false,
          "convertFieldsToString": true
        },
        "options": {}
      },
      "type": "n8n-nodes-base.executeWorkflow",
      "typeVersion": 1.2,
      "position": [
        220,
        -240
      ],
      "id": "19c76c59-91b4-4611-8d46-30c0c61696d0",
      "name": "Execute Workflow"
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "20671d7e-9415-495f-add3-172eae1a5a69",
              "name": "Linked Parent Workflow _postId",
              "value": "={{ $('Create Data').item.json._postId }}",
              "type": "number"
            }
          ]
        },
        "includeOtherFields": true,
        "options": {}
      },
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        440,
        -240
      ],
      "id": "1fe800f1-96bf-4161-8a82-2aa061efb32c",
      "name": "Join to Original"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        -220,
        -240
      ],
      "id": "a4d52565-c699-4daf-a2e1-5c176fe3e25c",
      "name": "When clicking ‘Test workflow’"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        880,
        -340
      ],
      "id": "324fef88-e2d8-4838-9cc8-a04fc37b832b",
      "name": "Good"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        880,
        -140
      ],
      "id": "5a20201a-b420-49c5-b5c2-c86736fdeeb1",
      "name": "Quite Bad"
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "loose",
            "version": 2
          },
          "conditions": [
            {
              "id": "0f96d0b0-d646-4199-81e7-31568b4e94de",
              "leftValue": "={{ $json._postId }}",
              "rightValue": "={{ $json['Linked Parent Workflow _postId'] }}",
              "operator": {
                "type": "string",
                "operation": "equals",
                "name": "filter.operator.equals"
              }
            }
          ],
          "combinator": "and"
        },
        "looseTypeValidation": true,
        "options": {}
      },
      "type": "n8n-nodes-base.if",
      "typeVersion": 2.2,
      "position": [
        660,
        -240
      ],
      "id": "09e26d12-d170-4b77-ab17-ff0e08dc0778",
      "name": "Correct"
    }
  ],
  "connections": {
    "Create Data": {
      "main": [
        [
          {
            "node": "Execute Workflow",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Execute Workflow": {
      "main": [
        [
          {
            "node": "Join to Original",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Join to Original": {
      "main": [
        [
          {
            "node": "Correct",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "Create Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Correct": {
      "main": [
        [
          {
            "node": "Good",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Quite Bad",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

</details>

- Create a sub workflow that filters and/or reorders items <img width="1396" alt="Image" src="https://github.com/user-attachments/assets/33d555d5-e0e6-4091-b1b1-bcf9638408b6" />

<details>
<summary>Sub workflow JSON</summary>
{
  "nodes": [
    {
      "parameters": {
        "url": "=https://jsonplaceholder.typicode.com/posts/{{ $json._postId || $position + 1 }}",
        "options": {
          "response": {
            "response": {
              "neverError": true
            }
          }
        }
      },
      "id": "d0cc51c2-2d85-494e-86f2-5b1e90b389e4",
      "name": "Get Post",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        -240,
        40
      ]
    },
    {
      "parameters": {
        "url": "=https://jsonplaceholder.typicode.com/users/{{ $json.userId }}",
        "options": {
          "response": {
            "response": {
              "neverError": true
            }
          }
        }
      },
      "id": "5e88592e-872a-4744-bdab-639d9abf39a2",
      "name": "Get Author",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        200,
        40
      ]
    },
    {
      "parameters": {
        "jsCode": "for (let index = 0; index < $input.all().length; index++) {\n  const item = $input.all()[index];\n  const item1 = $('Trigger').itemMatching(index);\n  item.json['Current pairedItem'] = item.pairedItem.item;\n  item.json['Trigger pairedItem'] = item1.pairedItem.item;\n  // Replace the pairedItems with items linked from the trigger\n  item.pairedItem = item1.pairedItem;\n}\n\nreturn $input.all();"
      },
      "id": "a0856b64-b7ff-48a8-a0e1-73724f7d914d",
      "name": "FIX",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        760,
        -160
      ]
    },
    {
      "parameters": {},
      "id": "6ff5c77b-ae61-43e5-af90-f9b6ff6022b3",
      "name": "Trigger",
      "type": "n8n-nodes-base.executeWorkflowTrigger",
      "typeVersion": 1,
      "position": [
        -500,
        -100
      ]
    },
    {
      "parameters": {
        "content": "### Connect this to fix when called by a parent workflow 🛠️",
        "height": 260,
        "width": 280,
        "color": 3
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        680,
        -240
      ],
      "typeVersion": 1,
      "id": "3b415ade-6884-42f1-b6c1-935f5b42e9a5",
      "name": "Sticky Note"
    },
    {
      "parameters": {
        "conditions": {
          "options": {
            "caseSensitive": true,
            "leftValue": "",
            "typeValidation": "loose",
            "version": 1
          },
          "conditions": [
            {
              "id": "caafc48c-f911-49c4-993d-697590157a41",
              "leftValue": "={{ $json.id % 2 }}",
              "rightValue": 1,
              "operator": {
                "type": "number",
                "operation": "equals"
              }
            }
          ],
          "combinator": "and"
        },
        "options": {
          "looseTypeValidation": true
        }
      },
      "id": "37ab24c9-2eeb-431c-8222-668868f57980",
      "name": "Odd",
      "type": "n8n-nodes-base.filter",
      "typeVersion": 2,
      "position": [
        -40,
        40
      ]
    },
    {
      "parameters": {
        "type": "random"
      },
      "type": "n8n-nodes-base.sort",
      "typeVersion": 1,
      "position": [
        -40,
        -260
      ],
      "id": "66b91bdf-3f03-4440-9a67-779e78036371",
      "name": "Sort"
    },
    {
      "parameters": {
        "type": "random"
      },
      "type": "n8n-nodes-base.sort",
      "typeVersion": 1,
      "position": [
        200,
        -260
      ],
      "id": "5dbb6c63-f5c1-4860-a57f-8206f5feff52",
      "name": "Sort1"
    },
    {
      "parameters": {
        "content": "## End here OK ✅",
        "height": 200,
        "width": 220
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        -100,
        -320
      ],
      "typeVersion": 1,
      "id": "2a8c26ee-d1b3-488a-b06a-231bcca5c9cb",
      "name": "Sticky Note2"
    },
    {
      "parameters": {
        "content": "## End here Bad ❌",
        "height": 200,
        "width": 220
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        140,
        -320
      ],
      "typeVersion": 1,
      "id": "ee11d6c1-c145-41e8-99d7-654615e6f6a5",
      "name": "Sticky Note3"
    },
    {
      "parameters": {
        "content": "## End here OK ✅",
        "height": 200,
        "width": 220
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        -100,
        -20
      ],
      "typeVersion": 1,
      "id": "5bfc34df-b51a-433b-b792-28541a99329f",
      "name": "Sticky Note4"
    },
    {
      "parameters": {
        "content": "## End here Bad ❌",
        "height": 200,
        "width": 400
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        140,
        -20
      ],
      "typeVersion": 1,
      "id": "540d91b7-83ff-4298-8547-1cbb9efd3d7a",
      "name": "Sticky Note5"
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "206bba29-9c20-4a7b-98b6-df12aa5a9bfa",
              "name": "_postId",
              "value": "={{ $('Trigger').item.json._postId }}",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "221ad5aa-a085-4928-8ce1-e4d6b9d5e27b",
      "name": "Set _postId",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        380,
        40
      ]
    },
    {
      "parameters": {
        "content": "## Reordering Example",
        "height": 300,
        "width": 880,
        "color": 6
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        -320,
        -380
      ],
      "typeVersion": 1,
      "id": "74ab67e0-7e1c-4bec-b011-61af04917af2",
      "name": "Sticky Note1"
    },
    {
      "parameters": {
        "content": "## Filtering Example",
        "height": 300,
        "width": 880,
        "color": 6
      },
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        -320,
        -60
      ],
      "typeVersion": 1,
      "id": "761a7df5-1bbd-47e4-b55c-02f8b1208262",
      "name": "Sticky Note6"
    }
  ],
  "connections": {
    "Get Post": {
      "main": [
        [
          {
            "node": "Odd",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Author": {
      "main": [
        [
          {
            "node": "Set _postId",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Trigger": {
      "main": [
        [
          {
            "node": "Sort",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Odd": {
      "main": [
        [
          {
            "node": "Get Author",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Sort": {
      "main": [
        [
          {
            "node": "Sort1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Sort1": {
      "main": [
        []
      ]
    },
    "Set _postId": {
      "main": [
        []
      ]
    }
  },
  "pinData": {
    "Trigger": [
      {
        "_postId": 1
      }
    ]
  }
}
</details>

- Update the execute workflow node in the parent to point at your sub workflow
- Try running the sub workflow with with either example, and observe the item linking break when a subsequent node in the child workflow wipes out the pariedItems from the trigger
- Notice how connecting the FIX node to either corrects the output in the parent node
```js
for (let index = 0; index < $input.all().length; index++) {
  const item = $input.all()[index];
  const item1 = $('Trigger').itemMatching(index);
  item.json['Current pairedItem'] = item.pairedItem.item;
  item.json['Trigger pairedItem'] = item1.pairedItem.item;
  // Replace the pairedItems with items linked from the trigger
  item.pairedItem = item1.pairedItem;
}

return $input.all();
```

### Expected behavior

1. The execute workflow node should be pairedItem aware and update the item linking to point to the correct items
2. This should be documented, it's a silent failure condition that can really mess up workflows

### Operating System

Alpine Linux

### n8n Version

1.86.1

### Node.js Version

20.19.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @pemontto,

We have created an internal ticket to look into this which we will be tracking as "GHC-1543"

**Comment by pemontto** [comment]
@Joffcom this is fixed 🎉

Thanks @afitzek ❤️!

Just one typo `findPairedItemTroughWorkflowData` should probably be `findPairedItemThroughWorkflowData` 😬

**Comment by MarcL** [comment]
@pemontto - Fixed in #17611. Thanks!

**Comment by fstadt** [comment]
I still experience this issue even with the current release [1.105.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.105.0).

I downgraded to 1.101.3 (similar to what we previously used before our workflow breaking on upgrading the n8n instance) and we have no issues there.

I don't have a minimalistic example yet which I can share, but I have something like this:

<img width="687" height="212" alt="Image" src="https://github.com/user-attachments/assets/97c0f7ec-5c74-4171-94ad-556297535d17" />

"Merge ticket information1" is referencing $("lastUpdated aktualisieren").item.json, which is not working ($("lastUpdated aktualisieren").item is undefined). Input count and output count of the subworkflow is the same (4 items).

The subworkflow looks like this:

<img width="1432" height="601" alt="Image" src="https://github.com/user-attachments/assets/119bbb46-24a2-4b74-b972-6b604044e69c" />

As I said, no minimal example yet, sorry ;) The subworkflow is not reordering or filtering anything, but I assume the complex structure of the subworkflow with the different branches with different item counts and the merge node which in the end restores the previous "input order" somehow breaks things after your improvements. Important info: The subworkflow is NOT "Run once with all items", still item linking fails somehow.

**Comment by pemontto** [comment]
@fstadt ahh I see you're using a multi input merge node. Is it just appending or doing some more complex SQL? Even in a single workflow I've had issues with item linking with multiple merge inputs. One hacky (and ugly) option to try work around is splitting that merge node into 6 separate ones...

**Comment by fstadt** [comment]
@pemontto  A simple append merge, yes. Item pairing worked fine for that subworkflow before the update.

**Comment by fstadt** [comment]
I was able to solve the problem by switching the execute subworkflow node to "Run once for each item".

**Comment by r-buc** [comment]
The current solution has a lot of known issues and breaks also the workaround initially suggested.
May I propose a different approach to the problem: getting and storing the correct item pairing at the end of the sub workflow execution instead of trying to rebuild it afterwards.
Please see this conversation for details and a proposed implementation: https://deepwiki.com/search/how-is-the-paireditem-tracking_8d656d06-ecc0-47ea-8360-603127951fab

> You're asking whether the Execute Workflow node's pairedItem tracking problem could be solved by traversing to the trigger node **within the sub-workflow** before returning, and storing that information directly in the returned data, instead of the current approach which returns pairedItem references from the last executed node.
> 
> # Answer
> 
> Yes, this is a viable alternative approach that would address the core limitation of `findPairedItemThroughWorkflowData`. Let me explain the current problem and how your proposed solution would work.
> 
> ## Current Problem
> 
> When the Execute Workflow node runs a sub-workflow in "once" mode with `waitForSubWorkflow: true`, it receives the sub-workflow's output data with pairedItem references pointing to the **last node** in the sub-workflow. [1](#6-0)  Then it attempts to backtrack through the sub-workflow's execution history to find the original trigger input: [2](#6-1) 
> 
> This backtracking fails for complex workflows because `findPairedItemThroughWorkflowData` has the limitations we discussed—it doesn't handle multiple runs, branches, or properly follow source chains. [3](#6-2) 
> 
> ## Your Proposed Solution
> 
> Instead of post-execution backtracking, you're suggesting to **pre-compute** the correct pairedItem references before the sub-workflow returns. This would work as follows:
> 
> ### Implementation Approach
> 
> 1. **Before returning from sub-workflow**: In the workflow execution engine, when a workflow completes, traverse backward from each output item to find its origin at the trigger/start node
> 
> 2. **Store the correct pairedItem**: Replace the current pairedItem (which points to the last node) with the pairedItem that points to the original input item from the trigger
> 
> 3. **Return pre-computed data**: The Execute Workflow node would receive data with correct pairedItem references already set, eliminating the need for `findPairedItemThroughWorkflowData`
> 
> ### Where This Would Be Implemented
> 
> The logical place would be in the workflow execution completion logic, specifically in `WorkflowExecute.processRunExecutionData()` after the execution loop completes. [4](#6-3)  
> 
> You could add a post-processing step that:
> - Identifies if this is a sub-workflow execution (check for parent execution metadata)
> - For each item in the final output, uses the existing `getPairedItem` logic to traverse back to the trigger node
> - Replaces the pairedItem with the trigger-relative reference
> 
> ### Advantages Over Current Approach
> 
> 1. **Uses full source information**: During execution, all the source data (`previousNode`, `previousNodeOutput`, `previousNodeRun`) is available, [5](#6-4)  so you can use the robust `getPairedItem` logic instead of the limited `findPairedItemThroughWorkflowData`
> 
> 2. **Handles complex workflows**: Would correctly handle multiple inputs, outputs, runs, and branches since it uses the same traversal logic that works during live execution [6](#6-5) 
> 
> 3. **No post-execution reconstruction**: Eliminates the need for the Execute Workflow node to fetch execution data and attempt backtracking [7](#6-6) 
> 
> 4. **Consistent with real-time behavior**: The pairedItem references would be computed using the same logic that expressions like `$('nodeName').item` use during execution
> 
> ### Potential Implementation Location
> 
> The most appropriate place would be in the workflow execution hooks, specifically in the `workflowExecuteAfter` hook.<cite /> You could add logic there to:
> 
> ```typescript
> // Pseudo-code for the concept
> if (isSubWorkflowExecution && hasParentExecution) {
>   const finalOutputs = getFinalOutputData(fullRunData);
>   for (const output of finalOutputs) {
>     for (const item of output) {
>       // Use getPairedItem-style logic to find trigger node
>       const triggerPairedItem = traverseToTrigger(item, fullRunData);
>       item.pairedItem = triggerPairedItem;
>     }
>   }
> }
> ```
> 
> ### Challenges to Consider
> 
> 1. **Identifying the trigger node**: You'd need to determine which node is the "start" of the sub-workflow (the node that received the input from the parent workflow)
> 
> 2. **Performance**: This adds processing time to every sub-workflow execution, though it would likely be faster than the current approach of fetching execution data post-hoc
> 
> 3. **Backward compatibility**: Existing workflows might depend on the current behavior, so this would need careful migration
> 
> # Notes
> 
> Your proposed approach is architecturally sound and would solve the fundamental problem by leveraging the complete source information available during execution rather than trying to reconstruct it afterward. The current `findPairedItemThroughWorkflowData` utility exists precisely because this pre-computation wasn't done, forcing post-execution reconstruction with incomplete logic. Implementing your suggestion would make sub-workflow pairedItem tracking as robust as the real-time `getPairedItem` function used in expressions.
>
