### ISSUE TITLE
Constant “Connection lost” error, cannot use n8n self-hosted since several days

### ISSUE THREAD

**Issue by Oswald0101** [n8n-io/n8n#16111]
### Bug Description

I have been experiencing a constant “Connection lost” message on my self-hosted n8n instance for almost a week. I am unable to use the platform or access any workflows. This issue started suddenly and persists even after server restarts and checking my network/firewall.

My n8n instance is accessible via HTTPS, the SSL certificate is valid (checked via SSL Labs and VirusTotal), and all other server services are running correctly.

I also tested the server from different devices and networks, but the problem remains the same.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/83840acd-7f26-4e80-b161-f939aacac2d1" />

### To Reproduce

Start n8n self-hosted (via PM2 or Docker or direct Node.js, specify your method here if possible)

Open the web interface at https://n8n.worldagentia.com/

Wait a few seconds/minutes

The “Connection lost” message appears and the interface is unusable.

### Expected behavior

n8n web interface should stay connected and allow me to access workflows and settings without interruption.

### Operating System

Ubuntu Linux 24.04.2 LTS

### n8n Version

last version

### Node.js Version

22

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Oswald0101,

We have created an internal ticket to look into this which we will be tracking as "GHC-2399"

**Comment by Oswald0101** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/34e985e5-9eb2-4386-842c-031a67659e0a" />

**Comment by sambrucejoseph** [comment]
Having the same issue. Spent 3+ hours yesterday trying out all possible solutions i found here in other GitHub issues, nothing is working.

Now, I'm only praying for @Joffcom 's internal ticket (GHC-2399) to be solved.

Till then, my workflows are not working at all.

**Comment by Joffcom** [comment]
This was fixed in 1.97 can you try upgrading?

**Comment by sambrucejoseph** [comment]
Still showing the same "Connection lost" error on 1.97.1

![Image](https://github.com/user-attachments/assets/9c090a2e-dc20-4df8-b316-e507d2bac6cd)

**Comment by Joffcom** [comment]
@sambrucejoseph interesting, are you using a reverse proxy and is it set up to use websockets correctly?

Can you open the browser dev console and check for any errors?

**Comment by Oswald0101** [comment]
Always the same error, impossible to install the new version. I don’t know what to do anymore, I really need help.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/0e8b9b93-256e-4f6f-aafd-8c252e43ad3a" />

**Comment by Oswald0101** [comment]
# Debug info

## core

- n8nVersion: 1.95.3
- platform: docker (self-hosted)
- nodeJsVersion: 20.19.2
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: d23ecd3b-5bff-46a0-b641-d7c34d864721

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/136.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-06-09T00:15:16.683Z

**Comment by Oswald0101** [comment]
Hello?

**Comment by Joffcom** [comment]
Hello 👋🏻 

Can you update to 1.97 as suggested and see if that resolves the issue for you, Based on other reports for about 90% of reports this has been solved with an update.

**Comment by Oswald0101** [comment]
I’ve tried every possible way to upgrade to version 1.97, but it’s impossible. I’ve been working on this for a week. I need help

**Comment by Oswald0101** [comment]
# Debug info

## core

- n8nVersion: 1.97.1
- platform: docker (self-hosted)
- nodeJsVersion: 20.19.2
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 0f27534e-20b3-41bd-938e-aac71b1267b4

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/137.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-06-09T15:44:50.646Z

**Comment by Oswald0101** [comment]
I have the latest version installed, but I’m still getting the same “Connection Lost” error.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/49c210e0-4b02-487c-ba3c-d3b57997906a" />

**Comment by Oswald0101** [comment]
I really need a solution so I can work; it’s urgent.

**Comment by Oswald0101** [comment]
I really need a solution so I can work; it’s urgent.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/56f85601-7341-478c-b726-4070a083aef0" />

**Comment by Oswald0101** [comment]
hello

**Comment by Joffcom** [comment]
Hey @Oswald0101 

This is very likely to be environmental, can you share how you have n8n deployed and any errors you see in the browser console?

**Comment by Joffcom** [comment]
As we haven’t heard back from you, we’re going to close this issue to keep things organized. But don’t worry, if you have more information or need further assistance, you’re welcome to reopen the issue anytime or create a new one. We’re always happy to help! 

Thanks for reaching out and have a great day! If this was closed by mistake and you have been waiting for us let me know and I can also re-open it.
