### ISSUE TITLE
[Bug Report][Self-Hosted n8n] Python ModuleNotFoundError in code node

### ISSUE THREAD

**Issue by Marshall-Qiu** [n8n-io/n8n#16414]
### Bug Description

Our n8n instance is self-hosted on k8s.
I tried to import a package called cryptography in my script, which exists in the list of available packages, but it throws an error.
https://pyodide.org/en/stable/usage/packages-in-pyodide.html#packages-in-pyodide
I also tried other packages in the list, and they all throw the same error.

### To Reproduce

1. open a code node
2. language field select python
3. put this code into python field
```python
# Then import and use
from cryptography.fernet import Fernet
# Loop over input items and add a new field called 'myNewField' to the JSON of each one
for item in _input.all():
  item.json.myNewField = 1
return _input.all()
```
4. click test the step
5. you will see code node throws an error
```
ModuleNotFoundError: No module named 'cryptography' The module 'cryptography' is included in the Pyodide distribution, but it is not installed. You can install it by calling: await micropip.install("cryptography") in Python, or await pyodide.loadPackage("cryptography") in JavaScript See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

<img width="1789" alt="Image" src="https://github.com/user-attachments/assets/41a26d01-f2ac-4700-9533-b3b6f9801c48" />

### Expected behavior

should run without throwing any error, since cryptography is in the list of supported package on pyodide website
https://pyodide.org/en/stable/usage/packages-in-pyodide.html#packages-in-pyodide

### Operating System

Alpine Linux v3.21

### n8n Version

1.92.2

### Node.js Version

v20.19.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Marshall-Qiu,

We have created an internal ticket to look into this which we will be tracking as "GHC-2592"

**Comment by Joffcom** [comment]
Hey @Marshall-Qiu,

Can you upgrade this was recently fixed. The below is from 1.97

![Image](https://github.com/user-attachments/assets/a21e2779-4ab8-4d5b-a78d-e340608d9461)

If after upgrading you are still seeing an issue let me know and we can open this again

**Comment by Marshall-Qiu** [comment]
Hi @Joffcom , I have upgrade my n8n instance to `1.98.1` I got new error 
my script
```
from cryptography.fernet import Fernet
# Loop over input items and add a new field called 'myNewField' to the JSON of each one
for item in _input.all():
  item.json.myNewField = 1
return _input.all()
```
result
```
ModuleNotFoundError: Module 'os' is blocked The module 'os' is removed from the Python standard library in the Pyodide distribution due to browser limitations. See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

**Comment by Marshall-Qiu** [comment]
For `1.97.1`, I got same error

<img width="1790" alt="Image" src="https://github.com/user-attachments/assets/a3c35202-5f31-4373-af45-5e5b21fdc79e" />

**Comment by jabbson** [comment]
Same in 1.98.2 when importing:

```
from email.parser import HeaderParser, BytesParser
from email import policy
```

from [community forum thread](https://community.n8n.io/t/issue-with-python-code-node-module-os-is-blocked).

**Comment by BigAddict** [comment]
Same case here in `v1.98.2` when importing:
```
import asyncio
import micropip

# Define an asynchronous function to install packages
async def install_packages():
    await micropip.install("beautifulsoup4")
    await micropip.install("simplejson")
```
Error 
```
ModuleNotFoundError: Module 'os' is blocked The module 'os' is removed from the Python standard library in the Pyodide distribution due to browser limitations. See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

![Image](https://github.com/user-attachments/assets/fcd7d623-8915-4423-aa3e-923285e7207f)

**Comment by AteneaV0204** [comment]
Im having the same problem in my job with a simple script. We did a rollback to version 1.97.0 and this version seems to not have this problem

![Image](https://github.com/user-attachments/assets/11754bc4-5545-41d3-affd-039f1a175b72)

**Comment by ltx0633** [comment]
![Image](https://github.com/user-attachments/assets/c65beda9-61a1-4a55-9ad9-9bd3edea845e)
Rolling back to 1.97.1 will work fine

**Comment by AteneaV0204** [comment]
we tried here but 1.97.1 didnt seem to work for us, but ill let my mate know it!

**Comment by arielbarreiros96** [comment]
Same error with `import micropip`
v 1.98.2

**Comment by Marshall-Qiu** [comment]
> Im having the same problem in my job with a simple script. We did a rollback to version 1.97.0 and this version seems to not have this problem
> 
> ![Image](https://github.com/user-attachments/assets/11754bc4-5545-41d3-affd-039f1a175b72)

I tried v1.97.0 still having problem

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/152b08b8-4f78-4db9-a3e0-8eb6641bdb40" />

**Comment by eduardotang** [comment]
Same in 1.98.2 when importing:

from shapely.geometry import Point, Polygon

**Comment by AteneaV0204** [comment]
> I tried v1.97.0 still having problem
> 
> <img alt="Image" width="1792" src="https://private-user-images.githubusercontent.com/89381510/457713293-152b08b8-4f78-4db9-a3e0-8eb6641bdb40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA2NjIyMTAsIm5iZiI6MTc1MDY2MTkxMCwicGF0aCI6Ii84OTM4MTUxMC80NTc3MTMyOTMtMTUyYjA4YjgtNGY3OC00ZGI5LWEzZTAtOGViNjY0MWJkYjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjIzVDA2NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTI4NWQ2ZTUxNTMzYjA3NWEwN2I5MGY1MDZiYWFhOTg2NmRmOWU1MTY4YzJiN2NhNmU2ZmYxYjVhMjZiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GVob9wxS16IdhCA6yH6Z_ar2LYKark2aNefWnAscz5Q">

It seems like everyone is having the problem, but at diffetent versions

**Comment by junior-saraiva** [comment]
Hello everyone,
I'm also having this problem and getting the same error.
My N8N version is: 1.99.1
I hope someone can find a solution.

![Image](https://github.com/user-attachments/assets/591c6961-4068-4431-b7af-7af9ecbeac4b)

**Comment by Joffcom** [comment]
There are different issues here, we fixed an issue with packages not loading but then we removed the OS capability as it was a potential security risk which then introduced a second issue.

There is a community PR in that will fix this and it is with our CATs team to review at the moment.

**Comment by Marshall-Qiu** [comment]
Hi @Joffcom, So can I expect it to be fixed soon?

**Comment by jaggyalex** [comment]
I am also having this problem on 1.100.1. It looks like #16543 might fix this if it is approved and merged.

**Comment by kamalmeh** [comment]
Hi there
I also have the same issue after I self-hosted from railway to my own server.

<img width="1338" height="589" alt="Image" src="https://github.com/user-attachments/assets/184ccfb9-5353-483f-940b-95931de0a353" />

Surprisingly, I am not using 'os' module at all in my code.

Kamal Mehta
Founder
https://www.smiansh.com

**Comment by jolin0915** [comment]
@Joffcom is there an update on this issue? thank you.

**Comment by Pegazse** [comment]
this seems to be fixed in 1.102.3

**Comment by jolin0915** [comment]
it's still not fixed in v1.102.3 for me

<img width="1278" height="519" alt="Image" src="https://github.com/user-attachments/assets/41f17c51-0368-48ee-8701-2245adbbad77" />

**Comment by Joffcom** [comment]
This issue should now be resolved

<img width="911" height="491" alt="Image" src="https://github.com/user-attachments/assets/a42da263-8a2b-4d82-b399-34078eacd396" />

and from the original post

<img width="887" height="584" alt="Image" src="https://github.com/user-attachments/assets/e200501f-e935-43c2-a145-2e4aebeb2720" />

I am going to mark this as closed, If after updating you are still seeing this please create a post on the support forum after searching to see if one already exists there.

**Comment by jolin0915** [comment]
@Joffcom sorry, which version fixes this issue?

**Comment by jolin0915** [comment]
@Joffcom i've upgraded to the latest version (1.105.3) and still seeing this issue:

<img width="1308" height="514" alt="Image" src="https://github.com/user-attachments/assets/17a1867d-f4ab-452a-87bd-ea5947e5f150" />

**Comment by jolin0915** [comment]
@Joffcom i've created a post on the forum: https://community.n8n.io/t/python-modulenotfounderror-in-code-node/162818
