### ISSUE TITLE
Can't start n8n from source - failed to load module 'insights'

### ISSUE THREAD

**Issue by KeemOnGithub** [n8n-io/n8n#17039]
### Bug Description

Hi,

I'm trying to start n8n using the source code from the main branch, and it works up until pnpm start. I get this error:

```
Error: Failed to load module "insights": Cannot find module 'C:\Users\<user>\node_modules\n8n\dist\modules/insights.ee/insights.module'
```

Are there any fixes available for this? I saw this error occurred for Docker too.

Additionally, windows-build-tools wasn't able to be installed. This seems to be a problem with node though.

Thank you!

### To Reproduce

1. Build the n8n build using the instructions in CONTRIBUTING.md
2. Run pnpm start

### Expected behavior

pnpm start succeeds, running n8n on localhost:5678

### Operating System

Windows 11

### n8n Version

1.100.1+ (from main branch source code)

### Node.js Version

22.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

This should have been fixed recently when did you last check out the source and have you tried building the docker image to see if that is working?

**Comment by KeemOnGithub** [comment]
Hi,

I pulled from the source again after reading your reply, rebuilt it using pnpm and used pnpm start, but the error still remains for some reason. 

Thank you for the Docker suggestion, I can give that a shot!

**Comment by toxsick** [comment]
Same here using npm version `"n8n": "1.100.1"` with pnpm (not Docker). Version`1.99.1` works.

Thanks for looking into this!

**Comment by Joffcom** [comment]
I am not able to reproduce this, I wonder if this is an issue specific to Windows. @toxsick are you also running on Windows?

When installing and building are there any errors?

**Comment by toxsick** [comment]
@Joffcom nope, i'm  on **macOS Sequoia**. During install i can not see anything out of the ordinary. Here you have the stacktrace where it fails for me:

```bash
n8n:dev: User settings loaded from: .n8n/.n8n/config
n8n:dev: Error: Failed to load module "insights": Cannot find module '/Users/<project-path>/apps/n8n/dist/modules/insights.ee/insights.module'
n8n:dev: Require stack:
n8n:dev: - /Users/<project-path>/node_modules/.pnpm/@n8n+backend-common@0.11.0/node_modules/@n8n/backend-common/dist/modules/module-registry.js
n8n:dev: - /Users/<project-path>/node_modules/.pnpm/@n8n+backend-common@0.11.0/node_modules/@n8n/backend-common/dist/index.js
n8n:dev: - /Users/<project-path>/node_modules/.pnpm/n8n@1.101.1_c550a0a036f3ae2f55906bb702dc2a8a/node_modules/n8n/dist/config/index.js
n8n:dev: - /Users/<project-path>/node_modules/.pnpm/n8n@1.101.1_c550a0a036f3ae2f55906bb702dc2a8a/node_modules/n8n/bin/n8n. Please review the module's entrypoint file name and the module's directory name.
n8n:dev:     at ModuleRegistry.loadModules (/Users/<project-path>/node_modules/.pnpm/@n8n+backend-common@0.11.0/node_modules/@n8n/backend-common/src/modules/module-registry.ts:71:12)
n8n:dev:     at BaseCommand.loadModules (/Users/<project-path>/node_modules/.pnpm/n8n@1.101.1_c550a0a036f3ae2f55906bb702dc2a8a/node_modules/n8n/src/commands/base-command.ts:80:3)
n8n:dev:     at /Users/<project-path>/node_modules/.pnpm/n8n@1.101.1_c550a0a036f3ae2f55906bb702dc2a8a/node_modules/n8n/bin/n8n:68:2
n8n:dev:  ELIFECYCLE  Command failed with exit code 1.
n8n:dev: ERROR: command finished with error: command (/Users/<project-path>/apps/n8n) /Users/hannes/Library/pnpm/.tools/@pnpm+macos-arm64/10.12.4/bin/pnpm run dev exited (1)
n8n#dev: command (/Users/<project-path>/apps/n8n) /Users/hannes/Library/pnpm/.tools/@pnpm+macos-arm64/10.12.4/bin/pnpm run dev exited (1)
```

Looking at it more closely it is right to complain that `/Users/<projectpath>/apps/n8n/dist/modules/insights.ee/insights.module` does not exist and I am not sure why it should?! 

Is this expected to be generated during install? (I run install with `--ignore-scripts`, as one should) Why is this file expected in the package `dist` directory?

Thanks and regards!

**Comment by Joffcom** [comment]
@toxsick From downloading the repo what are the exact commands you are running? I have just checked out a new clean copy and I am able to run `pnpm i && pnpm build && pnpm start` to get everything installed, built and then started.

**Comment by halouprogramer** [comment]
N8N Master code and releases version n8n@1.102.0,n8n@1.101.1 ..
 The same question on ubuntu, run command 
 pnpm install
 pnpm build
 pnpm build:n8n

**Comment by Joffcom** [comment]
Hey @halouprogramer 

We are not able to reproduce this, if you just pnpm install and pnpm build do you get any errors?

**Comment by halouprogramer** [comment]
Hi @Joffcom 
No, it only throws an error when I run the pnpm build:n8n command.
I think pnpm install and pnpm build are prerequisite steps.

As @toxsick said, version 1.99.1 works fine.
I copied the scripts/build-n8n.mjs file from the master branch to the same directory in version 1.99.1, and then ran 
`node scripts/build-n8n.mjs` and it worked successfully.

**Comment by toxsick** [comment]
Ok i narrowed it down a little bit. In my case the module-registry gets confused here:

 https://github.com/n8n-io/n8n/blob/master/packages/%40n8n/backend-common/src/modules/module-registry.ts#L56

I guess because my app package is also called n8n (`apps/n8n`). In my repo this is resolved to:

**n8nRoot**: `/Users/<project-path>/apps/n8n`

Once i rename my app folder to something like `apps/n8n-app` it resolves to:

**n8nRoot**: `/Users/<project-path>/node_modules/.pnpm/n8n@1.103.2_8667b83d5a51a7aae06794025252042a/node_modules/n8n`

And the problem is gone. I still have problems to create a minimal reproduction of this. But at least that explains what is going on here.

**Comment by toxsick** [comment]
@guillaumejacquart @ivov maybe you guys have a guess here, because of the recent changes?

**Comment by Joffcom** [comment]
I am still not able to reproduce this at all, When you say your app package is also called n8n what do you actually mean? Are you using a fork of n8n or your own folder structure maybe?

**Comment by guillaumejacquart** [comment]
I was able to reproduce when I have a monorepo (`apps`) with n8n source code inside, and if I'm running n8n from the monorepo (instead of from n8n directly). It is indeed due to the way we dynamically load the modules: https://github.com/n8n-io/n8n/blob/master/packages/@n8n/backend-common/src/modules/module-registry.ts#L56
Touching this is quite risky (there are lots of different way to run n8n and load modules). I'm not sure we want to touch it for this edgy use case that already have a workaround (renaming the child n8n folder) though

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3682".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3682".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3682".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3682".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by Joffcom** [comment]
Hey @KeemOnGithub,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3682".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by dube25** [comment]
Hi @Joffcom , 

I was able to repro the above, on a different environment:
Device: Raspberry Pi (ARM64)
Install method: npm install -g n8n
Node: v20.19.1
NPM: v11.5.2

Confirmed failing in these versions: 
- Current latest: 1.106.3
- Current next: 1.107.1

Installation method:
npm install n8n -g

Workaround:
- Reinstalled 1.101.3 

This is what I see when attempting to start n8n in the two latest versions installed via npm:
~ $ n8n Error: Failed to load module "insights": Cannot find module '/usr/lib/node_modules/n8n/dist/modules/insights.ee/insights.module' Require stack: - /usr/lib/node_modules/n8n/node_modules/@n8n/backend-common/dist/modules/module-registry.js - /usr/lib/node_modules/n8n/node_modules/@n8n/backend-common/dist/index.js - /usr/lib/node_modules/n8n/dist/config/index.js - /usr/lib/node_modules/n8n/bin/n8n. Please review the module's entrypoint file name and the module's directory name. at ModuleRegistry.loadModules (/usr/lib/node_modules/n8n/node_modules/@n8n/backend-common/src/modules/module-registry.ts:74:12) at CommandRegistry.execute (/usr/lib/node_modules/n8n/src/command-registry.ts:43:3) at /usr/lib/node_modules/n8n/bin/n8n:63:2

Yet, the actual path of these modules is **/usr/lib/node_modules/n8n/dist/modules/insights/**, where I find insights.module.js, insights.service.js, etc.

So it seems the global install (likely due to a wrong ModuleRegistry resolution of some sort) expects the module to be under a path that does not exist in the public build. Perhaps some config leaks from the enterprise edition's build (if that's what ee would stand for)?

I will try different versions upwards in case I can identify which one this issue got introduced with.

**Comment by dube25** [comment]
Looks like version `v1.105.4` would be the latest version that works on my system.

**Comment by FedeCzerwiak** [comment]
I can confirm, as @dube25 mentions I had this same issue with Current latest: `1.106.3` using `npm install n8n -g` as the installation method, and after switching back to `v1.105.4` I could run the application.

**Comment by ijouiri** [comment]
I’m facing the same issue. I’m hosting it on cPanel using npm.

Version 1.105.4 works fine, but when I update n8n to 1.106.3, it stops working.

**Comment by guillaumejacquart** [comment]
Hi @dube25, thanks for reporting this.
I did not manage to reproduce on my side (same node / npm version), but I'm suspecting something specific to the environment.
The module registry is supposed to first check the module dir (without .ee) and fallback to the .ee folder path: https://github.com/n8n-io/n8n/blob/master/packages/@n8n/backend-common/src/modules/module-registry.ts#L71
Could you run some checks to try and diagnose it further ?
```bash
  # Check if the insights module exists and is readable
  ls -la /usr/lib/node_modules/n8n/dist/modules/insights/
  ls -la /usr/lib/node_modules/n8n/dist/modules/insights/insights.m
  odule.js

  # Check permissions
  stat /usr/lib/node_modules/n8n/dist/modules/insights/insights.mod
  ule.js

  # Try to manually import the module in Node.js
  node -e "import('/usr/lib/node_modules/n8n/dist/modules/insights/
  insights.module.js').then(() => console.log('OK')).catch(e => 
  console.log('Error:', e.message))"
```

Could you also tell me if you have specific environment variable set (I'm curious about the NODE_ENV one for instance).

**Comment by ijouiri** [comment]
Hi @guillaumejacquart ,

Here’s the error I’m seeing:

`Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found 
(required by /home/username/nodevenv/domain.name/22/lib/node_modules/@sentry-internal/node-native-stacktrace/lib/stack-trace-linux-x64-glibc-127.node)
`

Just to note, I’m on shared hosting and don’t have root access to upgrade system libraries.
Everything works fine for me on version 1.105.4, but this issue appears starting with 1.106.3.

**Comment by dube25** [comment]
Hi @guillaumejacquart,

Thanks a lot for looking into this!

**Repro on Raspberry Pi (Linux ARM) with n8n 1.107.3**
```
$ n8n --version
1.107.3

$ ls -la /usr/lib/node_modules/n8n/dist/modules/insights/insights.module.js
-rw-r--r-- 1 root root 4142 Aug 18 22:00 .../insights.module.js

$ node -e "import('/usr/lib/node_modules/n8n/dist/modules/insights/insights.module.js').then(() => console.log('OK')).catch(e => console.log('Error:', e.message))"
Error: Cannot find module './stack-trace-linux-arm-glibc-115.node'
Require stack:
- /usr/lib/node_modules/n8n/node_modules/@sentry-internal/node-native-stacktrace/lib/index.js
- /usr/lib/node_modules/n8n/node_modules/@sentry/node-native/build/cjs/event-loop-block-integration.js
- /usr/lib/node_modules/n8n/node_modules/@sentry/node-native/build/cjs/index.js
- /usr/lib/node_modules/n8n/node_modules/n8n-core/dist/errors/error-reporter.js
- /usr/lib/node_modules/n8n/node_modules/n8n-core/dist/errors/index.js
- /usr/lib/node_modules/n8n/node_modules/n8n-core/dist/execution-engine/...
- /usr/lib/node_modules/n8n/dist/modules/insights/insights.module.js
```

The module file exists and is readable, so the failure is not a missing `insights.module.js.` It’s the **native dependency** required via `@sentry/node-native → @sentry-internal/node-native-stacktrace`, which tries to load `stack-trace-linux-arm-glibc-115.node.`

My environment is a Raspberry Pi (ARM). Node ABI should be 115 (Node 20). It looks like there’s **no prebuilt native binary published** for this platform/ABI combo, so the import fails. The ModuleRegistry fallback then tries `.ee` and surfaces a misleading “missing module” message.

**Environment details:**

No environment variables set for NODE, N8n etc...:
(`$ env | grep -E '^(NODE_ENV|N8N_|NODE_)'` returns nothing)

```
$ node -p "process.version"
v20.19.1

$ node -p "process.versions.modules"
115

$ node -p "process.platform + '-' + process.arch"
linux-arm

$ uname -a
Linux raspberrypi 6.12.34+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.34-1+rpt1~bookworm (2025-06-26) aarch64 GNU/Linux
```

**Ecosystem Config for PM2**

```
module.exports = {
  apps: [
    {
      name: "n8n",
      script: "n8n",
      env: {
        N8N_PROTOCOL: "https",
        N8N_HOST: "internal-xxxxx.example.net",   // anonymized
        N8N_PORT: 5678,
        NODE_ENV: "production",
        WEBHOOK_URL: "https://internal-xxxxx.example.net", // anonymized
        GENERIC_TIMEZONE: "America/Toronto"
      }
    }
  ]
};
```

**Comment by feri-irawan** [comment]
Same error, version 1.107.3

**Comment by Jamira40** [comment]
Same error, AlmaLinux 8 version 1.107.3 
AlmaLinux 9 is working since there is available glibc 2.34 but 8 have latest 2.28 in repo.

**Comment by MirekHovorka** [comment]
Same here - 1.105.4 seems to be the last working stable version.

**Comment by jsalcedo09** [comment]
Just got a critical update notification, updated from 1.105.4 to 1.107.3 and got this error. Any workaround is appreciated

**Comment by Jackfritt** [comment]
Ty @jsalcedo09 your workaround saved me. Installed via

npm install n8n@1.105.4

and it works...

**Comment by dube25** [comment]
I found a workaround for this on **Raspberry Pi OS (Bookworm, ARMv7, Node 20 ABI=115)**.  
The root problem is that `@sentry-internal/node-native-stacktrace` doesn’t ship a prebuilt binary for `linux-arm-glibc`, so n8n can’t load `stack-trace-linux-arm-glibc-115.node`.

Here’s what worked for me:

---

### Workaround steps

1. **Install Rust (needed to build the native module):**

```bash
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
```

2. **Rebuild the Sentry native modules from source inside the n8n install:**

```
cd /usr/lib/node_modules/n8n
sudo npm rebuild @sentry/node-native --build-from-source
sudo npm rebuild @sentry-internal/node-native-stacktrace --build-from-source
```

3. Symlink the compiled binary to the filename the loader expects:
```
SRC="node_modules/@sentry-internal/node-native-stacktrace/build/Release/stack-trace.node"
DST_DIR="$(node -p "require('path').dirname(require.resolve('@sentry-internal/node-native-stacktrace/lib/index.js'))")"

sudo ln -sf "$SRC" "$DST_DIR/stack-trace-linux-arm-glibc-115.node"
# optional extra for some toolchains
sudo ln -sf "$SRC" "$DST_DIR/stack-trace-linux-arm-gnueabihf-115.node"
```

4. **Restart n8n:**
```
n8n
```

**⚠️ Note: I will likely need to redo the symlink step after each n8n upgrade, until official ARM binaries are published by Sentry.**

**Comment by vip0123** [comment]
same issue almalinux Cpanel npm local installation  Error: Failed to load module "insights": Cannot find module when updated 
to 1.107.3

**Comment by vip0123** [comment]
latest stable is npx n8n -v
1.105.4

**Comment by guillaumejacquart** [comment]
Hey all, 
We've added a fix to dynamically try to load the library in question, and continue if it fails: https://github.com/n8n-io/n8n/pull/18586
This should fix your issues, and is released on [1.108.1](https://github.com/n8n-io/n8n/releases/tag/n8n%401.108.1)

**Comment by ijouiri** [comment]
@guillaumejacquart it works thank you
