### ISSUE TITLE
sendAndWait Broken with missing/invalid token

### ISSUE THREAD

**Issue by biovolt** [n8n-io/n8n#18610]
### Bug Description

I think this broke sendAndWait webhooks (at least for Telegram and Slack)

https://github.com/n8n-io/n8n/pull/17566

After upgrading my sendAndWait actions all return {“error”:“Invalid token”}

I tried in a clean setup and still got the same error, but when trying it in 1.103.2 it works

### To Reproduce

Install 1.107.4
Add a Telegram bot credentials
Add a Send message and wait for a response, and set the From id
Set the response type to Approval
Add an approve button
Then trigger the node, and you should get an approval request in telegram
When you click on the button yo should get `{"error":"Invalid token"}`

### Expected behavior

When the above buttn is cliked the node should be triggerd

### Debug Info

# Debug info

## core

- n8nVersion: 1.107.4
- platform: npm
- nodeJsVersion: 22.18.0
- database: postgres
- executionMode: regular
- concurrency: 1
- license: enterprise (production)
- consumerId: c365a869-660e-48e1-837e-6e4f6a4ea111

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 900 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/139.0.0.0 safari/537.36
- isTouchDevice: false

## security

- secureCookie: false

Generated at: 2025-08-20T17:13:11.994Z

### Operating System

Debian

### n8n Version

1.107.4

### Node.js Version

22.18.0

### Database

PostgreSQL

### Execution mode

main (default)

### Hosting

self hosted

**Comment by Joffcom** [comment]
Hey @biovolt,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-3914".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by biovolt** [comment]
```
{
  "nodes": [
    {
      "parameters": {},
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        -208,
        -128
      ],
      "id": "d73133b7-0269-42e7-94d7-1014fabeb289",
      "name": "When clicking ‘Execute workflow’"
    },
    {
      "parameters": {
        "operation": "sendAndWait",
        "chatId": "Your Telegram From or chat ID",
        "message": "Message",
        "approvalOptions": {
          "values": {
            "approvalType": "double"
          }
        },
        "options": {
          "appendAttribution": false
        }
      },
      "type": "n8n-nodes-base.telegram",
      "typeVersion": 1.2,
      "position": [
        96,
        0
      ],
      "id": "d95987e7-c281-4bd6-8422-ab511f77cc6c",
      "name": "Send message and wait for response",
      "webhookId": "8f12ed0b-3a92-4a09-ac5a-e50223a32974",
      "credentials": {
        "telegramApi": {
          "id": "eqdonT6KAASeCaAw",
          "name": "Telegram CN"
        }
      }
    }
  ],
  "connections": {
    "When clicking ‘Execute workflow’": {
      "main": [
        [
          {
            "node": "Send message and wait for response",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {},
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "c3427095edcaf52146cd9b1aa0b1f99d104092e99795d6ed6487ee189a41464a"
  }
}
```

**Comment by priority1it** [comment]
Confirmed broken in slack for me on 1.107.4

**Comment by geoza2000** [comment]
+1 broken in 1.107.4

**Comment by ShireenMissi** [comment]
Hi all,

I tried reproducing the issue for Slack and Telegram on multiple instances, using both 107.4 and beta, but everything works as expected on my side.
I also tested with the attached workflow, and it still works fine.

Could you please provide more details about the issue you’re seeing?

Thanks,

**Comment by geoza2000** [comment]
@ShireenMissi 

Clicking the button in slack to respond back to a form, displays  `{"error":"Invalid token"}` on the browser. 

Is there any possibility it checks the domain ? (n8n is hosted) 

Because my redirect is localhost and I manually change it to my local ip.

**Comment by chobeat** [comment]
broken for me on Telegram on 1.106.3 self-hosted with yunohost

**Comment by biovolt** [comment]
I am doing a new clean install with steps to recreate, but in the meantime @ShireenMissi did you click on the button to send the response to N8N?

**Comment by geoza2000** [comment]
I just looked on the code , it seems that domain, plays a role in the token generated :/

Example from #17566 
`const token = generateUrlSignature(urlForSigning, this.instanceSettings.hmacSignatureSecret);`

Probably that’s the issue, as req is a mismatch in validation.

```
if (shouldValidate && !this.validateSignatureInRequest(req, this.getHmacSecret())) {
				res.status(401).json({ error: 'Invalid token' });
				return { noWebhookResponse: true };
			}
		}
```

**Comment by biovolt** [comment]
I use ngrok with the settings below, which then redirect the call to n8n on localhost

This works on 1.105.4
But not on 1.107.4 or 1.106.3

# Webhook URLs
Environment="WEBHOOK_TUNNEL_URL=https://asdasdasd.ngrok-free.app"
Environment="WEBHOOK_URL=https://asdasdasd.ngrok-free.app"

**Comment by geoza2000** [comment]
@biovolt what is your host header (in the n8n request) ? Probably you can see it in webhook execution node

**Comment by biovolt** [comment]
All I can see is this. How should I be able to see it? Sorry


Forwarding                    https://blablabla.ngrok-free.app -> http://localhost:5678     

[
  {
    "update_id": 701983787,
    "message": {
      "message_id": 2604,
      "from": {
        "id": 111111111,
        "is_bot": false,
        "first_name": "rrrrrr",
        "language_code": "en"
      },
      "chat": {
        "id": 111111111,
        "first_name": "rrrrrr",
        "type": "private"
      },
      "date": 1755858944,
      "text": "bla"
    }
  }
]

> [@biovolt](https://github.com/biovolt) what is your host header (in the n8n request) ? Probably you can see it in webhook execution node

**Comment by geoza2000** [comment]
@biovolt create a new workflow , add webhook trigger node ,  call the (new webhook) endpoint as you are doing regally, and now on the execution tab you can see the result of the node , that should include the headers. 

We care about the `host` and `x-forwarded-host` headers

**Comment by biovolt** [comment]
```
[
  {
    "headers": {
      "host": "localhost:5678",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:142.0) Gecko/20100101 Firefox/142.0",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "accept-encoding": "gzip, deflate, br, zstd",
      "accept-language": "en-GB,af;q=0.5",
      "cookie": "abuse_interstitial=blablabla.ngrok-free.app",
      "priority": "u=0, i",
      "sec-fetch-dest": "document",
      "sec-fetch-mode": "navigate",
      "sec-fetch-site": "none",
      "sec-fetch-user": "?1",
      "sec-gpc": "1",
      "te": "trailers",
      "upgrade-insecure-requests": "1",
      "x-forwarded-for": "xxx.xxx.xxx.xxx",
      "x-forwarded-host": "blablabla.ngrok-free.app",
      "x-forwarded-proto": "https"
    },
    "params": {},
    "query": {},
    "body": {},
    "webhookUrl": "https://blablabla.ngrok-free.app/webhook/1ce7481a-9490-425e-a70e-09ab45e977d6",
    "executionMode": "production"
  }
]
```

**Comment by geoza2000** [comment]
@biovolt for me it’s obvious what the issue is , the code only accounts for the `host` header , where it should account for the `x-forwarded-host` header too. @ShireenMissi 

A quick fix you can try to resolve it temporary is override the `Host` value in your reverse proxy. Although your configuration is correct.

Let me know if you try the `Host` header override fix

**Comment by geoza2000** [comment]
Unfortunately I am off my PC until Monday @ShireenMissi cant create a PR

**Comment by biovolt** [comment]
Confirmed! Thank you @geoza2000 
When manually setting the host to the x-forwarded-host it works

Luckily, I can do that in my ngrok.yml config. 

Now I don't have to see the **SUPER annoying**! Please upgrade to the broken version pop-up **on every, single, page, load**

**Comment by TheSongg** [comment]
@geoza2000 Hello, I have encountered the same problem when using the telegram node of version 1.107.4 that I am using now. Excuse me, which version can solve it? Thank you.

**Comment by tomi** [comment]
Hey all. Looks like this is something we overlooked. Will fix this ASAP. In the meantime, you can use an older version `1.106.2` until this is fixed.

**Comment by tomi** [comment]
I tried reproducing this locally with ngrok but that didn't work. 

```
WEBHOOK_TUNNEL_URL=https://xxxx.ngrok-free.app WEBHOOK_URL=xxxx.ngrok-free.app
```

Could you elaborate how your setup works? Do you have a reverse proxy in front? How are the host headers handled in there?

**Comment by biovolt** [comment]
@tomi 

 Install ngrok (and move it to /usr/local/bin/ or similar), register a free account, and get an auth token.


Create an ngrok.yml config file and put your details in the file
```
version: "3"
agent:
  authtoken: xxxxxxxxxxx
tunnels:
  n8n:
    addr: 5678
    proto: http
    host_header: rewrite
    hostname: xxxxxxxx.ngrok-free.app
```

Start ngrok with something like "ngrok start --config /etc/ngrok.yml --all" depending on where you put the file.
N8N runs on http://localhost:5678

I hope this helps

**Comment by tomi** [comment]
Thanks @biovolt ! I was able to reproduce this. This should be fixed in [#18767](https://github.com/n8n-io/n8n/pull/18767). Remember that you need to have the `N8N_PROXY_HOPS` env var set correctly for n8n to behave correctly when it's behind a proxy.

**Comment by TheSongg** [comment]
> Hey all. Looks like this is something we overlooked. Will fix this ASAP. In the meantime, you can use an older version `1.106.2` until this is fixed.

@tomi @geoza2000 After I downgraded to version 1.06, the problem was solved.

However, the generated webhook-waiting url is https://my_domain/n8n/webhook-waiting/119/1bb47ad4-90a4-4cfa-b17f-c4baad943806?approved=true, and cannot be accessed.

Why is the access successful after / is removed?
https://my_domain/n8nwebhook-waiting/119/1bb47ad4-90a4-4cfa-b17f-c4baad943806?approved=true

Here is my docker command:
```bash
docker run -it -d --rm --name n8n \
  -p 5678:5678 \
  -e GENERIC_TIMEZONE="Asia/Shanghai" \
  -e TZ="Asia/Shanghai" \
  -e N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true \
  -e N8N_RUNNERS_ENABLED=true \
  -e N8N_SECURE_COOKIE=true \
  -e N8N_PROTOCOL=https \
  -e N8N_EDITOR_BASE_URL=https://my_domain/n8n \
  -e N8N_ENDPOINT_WEBHOOK=/webhook \
  -e N8N_ENDPOINT_WEBHOOK_TEST=/webhook-cf \
  -e N8N_ENDPOINT_API=/n8n/api \
  -e N8N_PATH=/n8n \
  -e N8N_DEFAULT_LOCALE=zh-CN \
  -e N8N_HOST=my_domain \
  -e WEBHOOK_URL=https://my_domain/n8n \
  -v n8n_data:/home/node/.n8n \
  n8nio/n8n
```

Here is my nginx configuration.
```bash
location /n8n {
            proxy_pass http://127.0.0.1:5678/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_buffering off;
        }
```

**Comment by kauezatarin** [comment]
Hello everyone,
This issue is still happening to me when I use the Telegram node 'Send and Wait for Response'.

Install: 1.111.0
Problem: Browser shows `{"error":"Invalid token"}` after opening the link received on telegram.

I’ve set up a new instance running inside a Docker container, behind Nginx as a proxy. I’ve also attached my docker-compose.yaml and .env files so you can get a better understanding of my setup.

[docker-compose.yml](https://github.com/user-attachments/files/22364385/docker-compose.yml)
[env.txt](https://github.com/user-attachments/files/22364191/env.txt)

Here are the headers received by n8n from nginx:

<img width="428" height="217" alt="Image" src="https://github.com/user-attachments/assets/d0d39260-57f8-4b6b-83a3-cadc17e93581" />

The same flow works on install 1.105.4

if you need some more info, please, let me know.

**Comment by chobeat** [comment]
same behavior for me, I was wondering if I did anything wrong with the update but in telegram it is still throwing an error

**Comment by jelleholtkamp** [comment]
Same here, but for Teams.

**Comment by lrtherond** [comment]
Same here with Gmail

**Comment by tomi** [comment]
@chobeat @jelleholtkamp @lrtherond are you all using `N8N_PATH`?

**Comment by lrtherond** [comment]
@tomi I am not using N8N_PATH. I am hosting via a subdomain served behind a reverse proxy for port mapping.

**Comment by jelleholtkamp** [comment]
> [@chobeat](https://github.com/chobeat) [@jelleholtkamp](https://github.com/jelleholtkamp) [@lrtherond](https://github.com/lrtherond) are you all using `N8N_PATH`?

Yes, we use n8n_path due to it being behind a proxy which uses the path to determine the correct backend.

**Comment by danielpieper** [comment]
I had the same issue `invalid token` with the latest n8n version 1.112.6. My setup is
```
Client → Traefik A (cloud) → Tailscale → Traefik B (cellar) → local service (n8n)
```

The problem here was the 2nd proxy. Traefik by default adds `X-Forwarded-For, X-Forwarded-Host and X-Forwarded-Proto` headers. This is what we want for Traefik A but not for Traefik B (as it would overwrite the headers with the values from Traefik A).

So in order for n8n to receive the correct client host Traefik B has to trust the ip address of Traefik A and carry over the headers. in this case set `forwardedHeaders.trustedIPs` to the tailnet ip.

I guess nginx would have to be configured in a similar way.

**Comment by karthikvyas-cashfree** [comment]
This worked for me.
N8N_PROXY_HOPS env var set correctly when it's behind a proxy.

**Comment by michael-radency** [comment]
Hello all, 
to confirm - does issue still happening if `N8N_PROXY_HOPS` set and the proxy is configured as mentioned by @danielpieper?

**Comment by jelleholtkamp** [comment]
@michael-radency Unfortunately haven't had the time to investigate @danielpieper's suggestion. I don't use Traefik but my proxy (Azure App Gateway) might be doing the same thing. I'm building a different proxy setup at the moment for unrelated reasons and this issue is not the highest of priorities right now. But when I'm finished with that and the issue persists, I will have better tools to investigate this further.

**Comment by kauezatarin** [comment]
@michael-radency unfortunately yes. I've also tried seting it to 0 and 2 just to be sure, but for my layout 1 should be the value (as it is in the docker compose I've provided), but the problem persists.

**Comment by StepAll** [comment]
same here,  Telegram, ver 1.118.1

**Comment by mrkylegp** [comment]
Had this issue, setting N8N_PROXY_HOPS=1 in my docker-compose.yml environment variables worked for me.

**Comment by JustGoscha** [comment]
Doesn't work for me on the newest version `1.120.3` even with `N8N_PROXY_HOPS=1`

Self-hosted, behind nginx on a subdomain

**Comment by jelleholtkamp** [comment]
Unfortunately still broken for me. Set N8N_PROXY_HOPS=2 (which is the case for us, when I check the headers in an incoming webhook i see 2 ip addresses in x-forwarded-for).

**Comment by ralcaidev** [comment]
Same here, N8N_PROXY_HOPS doesn't solve it.

**Comment by tomi** [comment]
@kauezatarin @StepAll @JustGoscha @jelleholtkamp @ralcaidev Could answer the following questions to help us troubleshoot this:

1. Have you ensured your reverse proxy includes the `X-Forward-*` headers documented [here](https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/)?
2. Do you see `X-Forward-*` headers in webhook requests? Is the leftmost entry in them the correct value you'd expect?
3. Are both the webhooks URL and editor URL in the same domain?

**Comment by lrtherond** [comment]
I was able to solve this problem. In my case it was because I use Cloudflare to protect my domains.

**Comment by ralcaidev** [comment]
> [@kauezatarin](https://github.com/kauezatarin) [@StepAll](https://github.com/StepAll) [@JustGoscha](https://github.com/JustGoscha) [@jelleholtkamp](https://github.com/jelleholtkamp) [@ralcaidev](https://github.com/ralcaidev) Could answer the following questions to help us troubleshoot this:

1- Yes
2- No
3- Yes

Proxy works fine for the editor, I can't see any problem. Exposed on port 8443:

Nginx ssl proxy listening on 8443:
```
    ...
    proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto    $scheme;
    proxy_set_header X-Forwarded-Host     $host;
    ...
```

Docker envs:
```
- N8N_PATH=/
- N8N_HOST=****.***
- N8N_PORT=8443
- N8N_PROTOCOL=https
- N8N_RUNNERS_ENABLED=true
- N8N_SECURE_COOKIE=true
- N8N_PROXY_HOPS=1
- NODE_ENV=production
- WEBHOOK_URL=https://****.***:8443/
- N8N_EDITOR_BASE_URL=https://****.***:8443/
```

**Comment by jelleholtkamp** [comment]
> [@kauezatarin](https://github.com/kauezatarin) [@StepAll](https://github.com/StepAll) [@JustGoscha](https://github.com/JustGoscha) [@jelleholtkamp](https://github.com/jelleholtkamp) [@ralcaidev](https://github.com/ralcaidev) Could answer the following questions to help us troubleshoot this:
> 
> 1. Have you ensured your reverse proxy includes the `X-Forward-*` headers documented [here](https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/)?
> 2. Do you see `X-Forward-*` headers in webhook requests? Is the leftmost entry in them the correct value you'd expect?
> 3. Are both the webhooks URL and editor URL in the same domain?

1 - Yes
2 - Yes; there are 2 IP addresses in there, as expected since it has to pass through 2 proxies. Hence i set proxy_hops to 2 as well.
3 - Yes

**Comment by jelleholtkamp** [comment]
I found a workaround for now, but it makes this case all the more confusing to be honest. 

The "wait" node works fine. What I did is I created a workflow with an n8n form trigger. Then I need a human-in-the-loop principle (which is what I needed the sendAndWaiting for). I solved it by sending a regular teams message (so no wait for response) with some meaningful text and the following hyperlink:

```{{ $execution.resumeUrl }}?action=approve```

Then AFTER the teams message, I added a "wait" node configured to "On webhook call". This works great. The strange thing though is that the $execution.resumeUrl is also on the /webhook-waiting path, so I kinda expected this to be broken as well.

**Comment by kauezatarin** [comment]
> [@kauezatarin](https://github.com/kauezatarin) [@StepAll](https://github.com/StepAll) [@JustGoscha](https://github.com/JustGoscha) [@jelleholtkamp](https://github.com/jelleholtkamp) [@ralcaidev](https://github.com/ralcaidev) Could answer the following questions to help us troubleshoot this:
> 
> 1. Have you ensured your reverse proxy includes the `X-Forward-*` headers documented [here](https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/)?
> 2. Do you see `X-Forward-*` headers in webhook requests? Is the leftmost entry in them the correct value you'd expect?
> 3. Are both the webhooks URL and editor URL in the same domain?

1 - Yes
2 - Yes 
I'm setting those headers as bellow on nginx:

   ```
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
```

Generating those outputs on webhook node:
<img width="428" height="217" alt="Image" src="https://github.com/user-attachments/assets/fb3fb9c8-fe13-4c4b-a208-e09411459235" />

3 - Yes

**Comment by tugzii** [comment]
For anyone still hitting **401 Invalid Token** on `sendAndWait` behind Nginx on a non-standard port:

The fix in PR #18767 is correct but only works if Nginx passes the right headers. The root cause is that n8n signs the `sendAndWait` token using the **full URL including port**. If your Nginx headers omit the port, the HMAC signature validation fails every time.

### Two headers must include the port:
```nginx
# WRONG - missing port, causes signature mismatch
proxy_set_header X-Forwarded-Host $host;
proxy_set_header Origin "https://your-domain.com";

# CORRECT - port included in both
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header Origin "https://your-domain.com:YOUR_PORT";
```

### Also critical — `N8N_PROXY_HOPS`

Must be set correctly in your n8n environment. Without it, Express ignores `X-Forwarded-*` headers entirely, making the Nginx fixes pointless.

- Single Nginx proxy → `N8N_PROXY_HOPS: "1"`
- Nginx + Cloudflare or similar → `N8N_PROXY_HOPS: "2"`

### Full working config

Complete `docker-compose.yml` and `nginx.conf` here:
https://gist.github.com/tugzii/5c731ee4df9c2cfcf17fbc35d0f32696

Verified working on **n8n 2.13.4** with PostgreSQL behind Nginx on a non-standard port.
