### ISSUE TITLE
Cannot register to receive license key for paid features on new N8N Self-hosted AI starter kit installation

### ISSUE THREAD

**Issue by AIDecisions** [n8n-io/n8n#19941]
## Describe the problem/error/question
New installation of N8N Self-hosted AI starter kit and tried to register to receive the paid features for free, but license request failed (Failed to register community edition: Request failed with status code 403) using docker containers

## What is the error message (if any)?
Failed to register community edition: Request failed with status code 403

## Please share your workflow/screenshots/recording

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
⚠️ WARNING ⚠️ If you have sensitive data in your workflow (like API keys), please remove it before sharing.
```

### core

- n8nVersion: 1.112.4
- platform: docker (self-hosted)
- nodeJsVersion: 22.19.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

### pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/140.0.0.0 safari/537.36
- isTouchDevice: false

### security

- secureCookie: false

Generated at: 2025-09-24T04:13:07.806Z}

**Comment by Joffcom** [comment]
Hey @AIDecisions,

Thank you for reaching out! We’ve received your issue and are looking into it. To help us track this internally, we’ve created a Linear ticket with the reference: "GHC-4602".

We’ll keep you updated as we make progress, but if you have any additional details or context to share, feel free to add them here - it’s always helpful!

Thanks for your patience and for bringing this to our attention.

**Comment by jixn-hu** [comment]
解决了么

**Comment by Zhiuannnn** [comment]
me too 
License request failed
Failed to register community edition: Request failed with status code 403

**Comment by MarcL** [comment]
Hey folks.

Can you try to apply for the community registered license again today?
We had some problems with our firewall which was stopping some requests from getting through earlier.
I think it should work now but please reply here if it doesn't.

**Comment by tuxpowered** [comment]
This issue seems to still persist. 

<img width="1074" height="1160" alt="Image" src="https://github.com/user-attachments/assets/e176b914-1c44-4ad3-96fa-12fac2945571" />

Proxmox PVE using community LXC script, and updated to current.

```bash
root@n8n:~# n8n --version
1.112.6
root@n8n:~# 
```

Attempted to launch n8n with --tunnel but that fails as well 

```bash
root@n8n:~# systemctl stop n8n
root@n8n:~# npx n8n start --tunnel
Permissions 0644 for n8n settings file /root/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
Initializing n8n process
n8n ready on ::, port 5678

There are deprecations related to your environment variables. Please take the recommended actions to update your configuration:
 - DB_SQLITE_POOL_SIZE -> Running SQLite without a pool of read connections is deprecated. Please set `DB_SQLITE_POOL_SIZE` to a value higher than zero. See: https://docs.n8n.io/hosting/configuration/environment-variables/database/#sqlite
 - N8N_RUNNERS_ENABLED -> Running n8n without task runners is deprecated. Task runners will be turned on by default in a future version. Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future. Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
 - N8N_BLOCK_ENV_ACCESS_IN_NODE -> The default value of N8N_BLOCK_ENV_ACCESS_IN_NODE will be changed from false to true in a future version. If you need to access environment variables from the Code Node or from expressions, please set N8N_BLOCK_ENV_ACCESS_IN_NODE=false. Learn more: https://docs.n8n.io/hosting/configuration/environment-variables/security/

[license SDK] Skipping renewal on init: license cert is not initialized

Waiting for tunnel ...
^CReceived SIGINT. Shutting down...

Stopping n8n...

root@n8n:~# ping google.com
PING google.com (142.250.73.142) 56(84) bytes of data.
64 bytes from pnseaa-ao-in-f14.1e100.net (142.250.73.142): icmp_seq=1 ttl=113 time=6.32 ms
^C
--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 6.322/6.322/6.322/0.000 ms
root@n8n:~# 
```

**Comment by adityataps** [comment]
> This issue seems to still persist.
> <img alt="Image" width="1074" height="1160" src="https://private-user-images.githubusercontent.com/2959347/494647542-e176b914-1c44-4ad3-96fa-12fac2945571.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5NDU5OTQsIm5iZiI6MTc1ODk0NTY5NCwicGF0aCI6Ii8yOTU5MzQ3LzQ5NDY0NzU0Mi1lMTc2YjkxNC0xYzQ0LTRhZDMtOTZmYS0xMmZhYzI5NDU1NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjdUMDQwMTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJlMWEzMTA4NGYwNWUxNzg2ZTdiMTRlNjljMTQxODJmZmZjODJjZjA5NTZlMjE5OTM5ODJlNDY0MWIwMTg5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zv2GHO-J2SmeJNLA-L7uagaJDchCIb9NK1RhZl7dsO8">
> 
> Proxmox PVE using community LXC script, and updated to current.
> 
> root@n8n:~# n8n --version
> 1.112.6
> root@n8n:~# 
> 
> Attempted to launch n8n with --tunnel but that fails as well
> 
> root@n8n:~# systemctl stop n8n
> root@n8n:~# npx n8n start --tunnel
> Permissions 0644 for n8n settings file /root/.n8n/config are too wide. This is ignored for now, but in the future n8n will attempt to change the permissions automatically. To automatically enforce correct permissions now set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true (recommended), or turn this check off set N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false.
> Initializing n8n process
> n8n ready on ::, port 5678
> 
> There are deprecations related to your environment variables. Please take the recommended actions to update your configuration:
>  - DB_SQLITE_POOL_SIZE -> Running SQLite without a pool of read connections is deprecated. Please set `DB_SQLITE_POOL_SIZE` to a value higher than zero. See: https://docs.n8n.io/hosting/configuration/environment-variables/database/#sqlite
>  - N8N_RUNNERS_ENABLED -> Running n8n without task runners is deprecated. Task runners will be turned on by default in a future version. Please set `N8N_RUNNERS_ENABLED=true` to enable task runners now and avoid potential issues in the future. Learn more: https://docs.n8n.io/hosting/configuration/task-runners/
>  - N8N_BLOCK_ENV_ACCESS_IN_NODE -> The default value of N8N_BLOCK_ENV_ACCESS_IN_NODE will be changed from false to true in a future version. If you need to access environment variables from the Code Node or from expressions, please set N8N_BLOCK_ENV_ACCESS_IN_NODE=false. Learn more: https://docs.n8n.io/hosting/configuration/environment-variables/security/
> 
> [license SDK] Skipping renewal on init: license cert is not initialized
> 
> Waiting for tunnel ...
> ^CReceived SIGINT. Shutting down...
> 
> Stopping n8n...
> 
> root@n8n:~# ping google.com
> PING google.com (142.250.73.142) 56(84) bytes of data.
> 64 bytes from pnseaa-ao-in-f14.1e100.net (142.250.73.142): icmp_seq=1 ttl=113 time=6.32 ms
> ^C
> --- google.com ping statistics ---
> 1 packets transmitted, 1 received, 0% packet loss, time 0ms
> rtt min/avg/max/mdev = 6.322/6.322/6.322/0.000 ms
> root@n8n:~#

Same here, setting up n8n as a LXC. This is my first time setting up n8n so I wasn't sure if it was an issue with my firewall/reverse proxy or if it was something out of my hands. I'll sit tight for now

**Comment by MarcL** [comment]
Hello @tuxpowered and @adityataps,

I think there might be a couple of other issues at play here. I'm not super familiar with Proxmox setups but I think it might be a problem with the `Origin` header in the client-side request we make for the community registered license.

From a self-hosted instance, it should be `localhost` and I wonder if you're sending a local IP address (e.g. 192.168.*, 10.*, 172.16.* etc.). Can you look in the browser dev tools and let us know what headers are being sent with the client-side request to https://enterprise.n8n.io/community-registered? I think the firewall probably blocks these IP address ranges as it may be considered a server-side request forgery (SSRF) request.

As for the tunnel not working, I think that might be your n8n instance being unable to establish an outbound connection due to network or firewall configuration. Could Proxmox or the container's networking configuration be incorrect?

**Comment by tuxpowered** [comment]
The container (LXC) can establish network access, (see previous post with ping output to google).

Looks like a normal request, where the Host is the IP of the system.  not localhost, but the IP of the system that is in a private space subnet.

```bash
POST /rest/license/enterprise/community-registered HTTP/1.1
Host: 10.0.200.207:5678
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0
Accept: application/json, text/plain, */*
Accept-Language: en
Accept-Encoding: gzip, deflate
Content-Type: application/json
push-ref: byqzpjgqpl
browser-id: 9945bd42-5c59-4713-aa18-a6dc540e3321
Content-Length: 25
Origin: http://10.0.200.207:5678
DNT: 1
Connection: keep-alive
Cookie: xxx
Priority: u=0
Pragma: no-cache
Cache-Control: no-cache
```


This got me to looking into how things were set, with relation to Proxmox Containers (LXC) deployed from the community-scripts. 

The community scriptes all create an enviorment variable file (if you said to save config) to /opt/*.env.

On a clean install this looked like :
```bash
root@n8n:/opt# cat n8n.env 
N8N_SECURE_COOKIE=false
N8N_PORT=5678
N8N_PROTOCOL=http
N8N_HOST=10.0.200.207
```
The `N8N_HOST=` line has the IP of the running LXC, this actually makes sense. 

However this needed to be chaged to `localhost` in place of the IP.
The LXC needs to be restarted as just a restart of the service, was not enough.

Once restarted you could successfully register.

*HOWEVER* The actrivation link will fail because it now also looks at `localhost`, so one must manually copy the url with the license key and change the localhost to the IP of the system to activate it.

After the activation, you can go back to the `n8n.env` file and set the IP back for `N8N_HOST=` to the correct IP and again restart the system.


Whooew that was a workaround. 

Not sure why your license server rejects local IPs and is hardcoded to need localhost, seems like an issue there. 

Never tried the `--tunnel` again, as the above worked to get things going.

So maybe pin this or something for anyone with Proxmox Community scripts deploying N8N so they have a fix.... or maybe allow private IPs to register :)

**Comment by MarcL** [comment]
@tuxpowered - Thanks for the detailed response and I'm glad you got a hacky workaround for now.

It's not our license server that's rejecting the private IP. It's the firewall from Cloudflare that sits in front as a proxy.
I think that the firewall is attempting to block [server-side request forgery requests (SSRF)](https://portswigger.net/web-security/ssrf) which often use a local IP range which is why we initially saw issues with `localhost` and probably why we're also seeing issues with this ProxMox IP address.

Let me speak to the team and see what our options are here.

**Comment by MarcL** [comment]
@tuxpowered - Can you try again today? We've altered some of our firewall configuration will hopefully easy the issue. I'm hoping you won't have to use the `N8N_HOST=localhost` workaround now. Thanks!

**Comment by tuxpowered** [comment]
@MarcL I spun up another LXC on a different server this afternoon with no modifications, 

The system was able to get out and send an invite back with a 192.168.1.x address, in addition the activate license also redirected to the correct address. 

it looks like the firewall change was what allowed success. 

As my curisoity gets the better of me, I am curious what firewall settings in CF you are using? (maybe just PM me as its not related to this issue) I have lots of things behind CF proxies and sometimes run in to odd issues due to that but never seen anything to block this type of traffic. Might be something I would look into implememnting and learning :)

Thank you for the quick isolation! always awesome when someone knows there stuff :)

**Comment by adityataps** [comment]
Hey, I'm coming back to this thread a little late but I was able to get a email set out now without doing any workarounds for the LXC. Thanks n8n team!

**Comment by MarcL** [comment]
@tuxpowered @adityataps - I'm glad it works now, and sorry for the inconvenience! 🫡 

@tuxpowered - There's a bunch of [Cloudflare Managed Rules](https://developers.cloudflare.com/waf/managed-rules/reference/cloudflare-managed-ruleset/) for their WAF product. These include SSRF protection and these were enabled. For some reason Cloudflare has 2 rules but it's unclear how they differ.

Let me know if you spot any other issues. 👍🏻

**Comment by AIDecisions** [comment]
Hi @MarcL, 
Thank you for all your efforts and dedication. 
To close the loop, I was able to register the license from the first round of fixes. 

Thank you again.

**Comment by MarcL** [comment]
@AIDecisions - No problem. It's always frustrating when infrastructure breaks things for people so I'm glad we got it fixed for everyone. 👍🏻

**Comment by SebastianB12** [comment]
Hi @MarcL ,
I just installed it with the community proxmox helper scripts and get the error again. Did you change something back in your cloudflare firewall config?
Thanks!

**Comment by Mr-DS-ML-85** [comment]
> Hey folks.
> 
> Can you try to apply for the community registered license again today? We had some problems with our firewall which was stopping some requests from getting through earlier. I think it should work now but please reply here if it doesn't.

Brother Not working

**Comment by f1xtro** [comment]
Hi,
Sadly it did not work for me today either. The workaround with changing the host to localhost to request the code and change it back after did work.

**Comment by MarcL** [comment]
Hey folks. Nothing has been manually changed. Let me see if Cloudflare has applied any new rules.

**Comment by MarcL** [comment]
It seems that Cloudflare can add additional firewall rules at any time and it looks like they've added a couple which may be the cause of the problems. I've changed them so they shouldn't block traffic now.

@SebastianB12 @Mr-DS-ML-85 @f1xtro - Can you retry getting your community registered licenses and let me know if you're still having problems? Thanks!

**Comment by xiaowei01** [comment]
Is there any have this issue?
below is log:
n8n Task Broker ready on 127.0.0.1, port 5679

There are deprecations related to your environment variables. Please take the recommended actions to update your configuration:
 - N8N_BLOCK_ENV_ACCESS_IN_NODE -> The default value of N8N_BLOCK_ENV_ACCESS_IN_NODE will be changed from false to true in a future version. If you need to access environment variables from the Code Node or from expressions, please set N8N_BLOCK_ENV_ACCESS_IN_NODE=false. Learn more: https://docs.n8n.io/hosting/configuration/environment-variables/security/
 - N8N_GIT_NODE_DISABLE_BARE_REPOS -> Support for bare repositories in the Git Node will be removed in a future version due to security concerns. If you are not using bare repositories in the Git Node, please set N8N_GIT_NODE_DISABLE_BARE_REPOS=true. Learn more: https://docs.n8n.io/hosting/configuration/environment-variables/security/

[license SDK] Skipping renewal on init: license cert is not initialized
Registered runner "JS Task Runner" (yXSTYBxj9MYfGXWtqHNip)
Version: 1.118.1

Editor is now accessible via:
http://localhost:5678
-----------
my issue is when i using Nginx to proxy the n8n it can't load js
Failed to load module script: Expected a JavaScript-or-Wasm module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
any one can help me  thanks.

**Comment by MarcL** [comment]
@xiaowei01 - I don't think your comment is related to the problem with license keys. Can you create a new GitHub issue for your problems please? Thank you.

**Comment by tuxpowered** [comment]
@MarcL, Would it not be better / more managable even, if lets say there was a way said user could just enter their email address and have a code emailed to them, that they could then "paste" into n8n and not have to deal with the 3rd party changes that are out of your control?

At the vary least it would be a 'fall back' option should someone have issues, but also it would be a nice way to not be relient on a 3rd party provider for a critical aspect.

**Comment by MarcL** [comment]
@tuxpowered 

Thanks for your comment. Unless I'm misunderstanding what you're saying, the process you suggested is already what happens. You enter your email address and the license is emailed to you for the Community Registered version.

The issue is that we have a lot of requests for licenses and ultimately they all have to go through our license server in some way in order to generate the license key. In order to mitigate some of the load, there's a queuing and caching system that goes through Cloudflare. It's generally fine and handles any downtime we might have had previously, but their firewall is proactive in trying to stop people from potential security threats. We don't really see enough problems now to warrant moving this away from Cloudflare.

Does that make sense or have I misunderstood what you asked?

**Comment by Billjeff** [comment]
Im having the same issues. The license key never arrives in my inbox.

**Comment by MarcL** [comment]
@Billjeff - Apologies, we've had an issue with our production server. It should be working again shortly
