### ISSUE TITLE
Javascript Code Modules keep hanging over simple tasks

### ISSUE THREAD

**Issue by Pushingcapital** [n8n-io/n8n#21299]
Describe the problem/error/question

I’m running a workflow on n8n Cloud that receives a HubSpot webhook, processes it with a Code in JavaScript node (to extract file URLs), and then passes them to an HTTP Request node for conversion.
The Code in JavaScript node gets stuck in “Executing node…” indefinitely — it never returns or times out, even when the code is extremely simple (e.g., return [{ json: { message: "ok" } }]).

This happens consistently, even when the webhook payload is small. Stopping executions and reactivating the workflow doesn’t help. It seems to be a stuck or non-returning execution issue within the n8n cloud runtime.

What is the error message (if any)?

No error message is shown. The node remains in a perpetual “Executing node…” state, with no logs or output returned.

Please share your workflow/screenshots/recording

<img width="927" height="410" alt="Image" src="https://github.com/user-attachments/assets/210d0711-c73d-48f5-8d4d-82b1c2366af5" />

Workflow summary:
Webhook → Code in JavaScript → HTTP Request (GET) → HTTP Request (POST to HubSpot)

The Code node is extremely lightweight:
```
-------------------------------------------------
const items = [];
const input = $input.all();
const data = input[0].json;

const urls = [
  data.utility_bill_photo,
  data.id_photo_front,
  data.id_photo_back
].filter(Boolean);

for (const url of urls) {
  items.push({ json: { url } });
}

return [{ json: { test: "ok" } }];
-------------------------------------------------
```
Share the output returned by the last node

No output — the execution freezes on the Code node.

Expected output:
```
[
  { "json": { "url": "..." } },
  { "json": { "url": "..." } }
]
```

Debug info
core

n8nVersion: 1.115.3

platform: docker (cloud)

nodeJsVersion: 22.20.0

nodeEnv: production

database: sqlite

executionMode: regular

concurrency: 5

license: community

storage

success: all

error: all

progress: false

manual: true

binaryMode: filesystem

pruning

enabled: true

maxAge: 168 hours

maxCount: 2500 executions

client

userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/141.0.0.0 safari/537.36

isTouchDevice: false

Generated at: 2025-10-28T23:04:42.918Z

**Comment by arc64** [comment]
Hi @Pushingcapital,

This has been resolved in the latest version of n8n, please update and let us know if you have any more issues.

**Comment by Pushingcapital** [comment]
Just to let you know. The problem was still occurring. The only fix was to restart my workspace.
