### ISSUE TITLE
AgentV3 - MCP tools open new http streamable session per tool call

### ISSUE THREAD

**Issue by SirPangolin** [n8n-io/n8n#21642]
### Bug Description

`@n8n/n8n-nodes-langchain.agent` typeVersion3 handling of MCP tools call are dispatched via `createEngineRequests`, resulting in a fresh `connectMcpClient` handshake. This results in a new http session to be created on each MCP tool call resulting in any MCP Server that requires context of a previous session to lose that context and start a new session.

For example, AgentV3 issuing a tool call to a PlaywrightMCP server with `browser_navigate` cannot issue another tool call with `browser_click` to the same MCP Client/Server page session and instead opens a new session between the server and client and attempts the `browser_click` on an "about:tab" page since no `browser_navigate` has occurred in the current session. The previous sessions opened per tool call are left abandoned.

This workflow worked properly with `@n8n/n8n-nodes-lanchain.agent` typeVersion2 (2.3).

### To Reproduce

1. Create Agent typeVersion3 (`@n8n/n8n-nodes-langchain.agent` typeVersion: 3) workflow with an HTTP Streamable MCP Client (`@n8n/n8n-nodes-langchain.mcpClientTool` typeVersion: 1.2) that requires the same http session per execution to provide intended results.
2. Execute workflow where multiple tool calls are expected via the MCP Client (i.e. Playwright MCP Server with a `browser_navigate` + `browser_click` (to accept cookies).
3. Observe first tool call returns 'browser_navigate` intended result. Second tool call starts new MCP Client / Server session (i.e. new browser context), and returns unintended result i.e. "about:blank".

### Expected behavior

During the same workflow execution, same http session is reused between MCP Client / MCP Server with multiple tool calls. Next **workflow execution** creates a new MCP Client / MCP Server session, not the next **tool call**.

### Debug Info

# Debug info

## core

- n8nVersion: 1.117.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.18.0
- nodeEnv: production
- database: postgres
- executionMode: scaling (single-main)
- concurrency: -1
- license: enterprise (production)
- consumerId: 6242b784-77cf-49e7-b138-348dded14b9f

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36 edg/142.0.0.0
- isTouchDevice: false

Generated at: 2025-11-07T18:27:04.949Z

### Operating System

Alpine Linux v3.22

### n8n Version

1.117.3

### Node.js Version

22.18.0

### Database

PostgreSQL

### Execution mode

queue

### Hosting

self hosted

**Comment by MookieLian** [comment]
`#triage:in-progress`

**Comment by MookieLian** [comment]
<aside>

Thank you for raising this issue, the first step of triage is completed, and it has been routed internally for further investigation.

_This issue has been resolved in the latest version of n8n._

`#triage:complete`

</aside>

**Comment by SirPangolin** [comment]
I'm curious what you define as "resolved" when migrating to the later version. I have tested with v1.118.2 / v1.122.5 and each version creates a new session for the MCP server while v.1.116.2 keeps the same session context.

**Comment by SirPangolin** [comment]
I have updated to the latest stable version of n8n (1.123.5) and am still experiencing this issue.

**Comment by nicolaeser** [comment]
Any news on this?

**Comment by ferhimedamine** [comment]
We hit this exact same class of problem building stateful MCP tool chains — the root issue is that session state is coupled to the transport lifecycle. When `connectMcpClient()` tears down the `StreamableHTTPClientTransport` after each call, any server-side state (browser context, open cursors, transaction handles) dies with it. The fix everyone reaches for — connection pooling keyed by execution ID — works for single-worker setups but breaks down the moment you scale horizontally, because session affinity across workers requires the state to live *outside* both the client and the server.

What we ended up doing is treating tool execution state as a memory problem: each tool call writes its output context (page URL, DOM snapshot hash, session tokens) as a record tagged with the execution/session ID, and the next tool call in the chain recalls that state before executing. This decouples persistence from the transport entirely — you can reconnect, switch workers, even restart the agent mid-chain, and the tool state survives. We open-sourced the MCP server that handles this at [dakera-mcp](https://github.com/dakera-ai/dakera-mcp), which acts as a session-state sidecar: your Playwright MCP server writes browser context to it, and subsequent calls hydrate from it rather than relying on the HTTP session staying alive.

For the n8n-specific workaround, the cleanest path I've seen is intercepting at the `closeFunction` level — defer transport teardown until workflow execution completes rather than after each tool invocation. That's essentially what v1.116.2 did. But the more durable pattern is externalizing the state so it's transport-agnostic.
