### ISSUE TITLE
Imported workflows cannot be enabled unless first edited

### ISSUE THREAD

**Issue by voortwis** [n8n-io/n8n#22393]
### Bug Description

In version 1.122.x after starting n8n docker and importing workflows. It is not possible to enable them in the UI or with the n8n-node (i use for autostarting). Only after opening a workflow and changing it (that it gets saved) the flow can set active/enabled again. Otherwise I get an 500 error.

### To Reproduce

1. Start fresh instance of n8n that will automatically import a workflow.
2. Try to enable the workflow in the UI or using a n8n step.
3. You will see a 500 http error.
4. Edit the workflow (just add and remove a tag, or drag a step to another location), Save
5. After save, enable the workflow - will work.

### Expected behavior

Imported workflows should be possible to be enabled using the cli or a workflow with the n8n node.

### Debug Info

# Debug info - this is working, use the 1.122.2 image and it fails.

## core

- n8nVersion: 1.121.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: 20
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-11-27T10:46:13.819Z

### Operating System

Kubernetes

### n8n Version

1.122.2

### Node.js Version

22.21.0

### Database

SQLite (default)

### Execution mode

main (default)

### Hosting

self hosted

**Comment by voortwis** [comment]
Tried again with 1.122.3 - same error - not able to activate imported workflows

# Debug info

## core

- n8nVersion: 1.122.3
- platform: docker (self-hosted)
- nodeJsVersion: 22.21.0
- nodeEnv: production
- database: sqlite
- executionMode: regular
- concurrency: 20
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/142.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2025-11-28T10:37:45.723Z

**Comment by schbas** [comment]
I can confirm this issue on **1.122.2** (Self-hosted Docker).

It happens specifically when using **Git Source Control**:
1. I push a workflow from Dev.
2. I pull it to Prod.
3. Trying to activate it results in a `500 Internal Server Error`.

**Important Observation:**
After the Git Pull, the project shows my role as **"Viewer"** (Read Only), even though I am the **Instance Owner**.

**Workaround:**
If I turn off the production instance protection, edit the workflow in the Prod UI (e.g., change a node name) and **Save**, the issue is resolved, and I can activate the workflow immediately. This suggests the "Save" action repairs whatever is broken during the Git Pull/Import.

**Comment by lennartki** [comment]
We are having the same issue. This is what I see in the logs. 

`2025-12-08T15:46:48.1021215Z stdout F Error: 
2025-12-08T15:46:48.1021358Z stdout F     at WorkflowHistoryService.getVersion (/usr/local/lib/node_modules/n8n/src/workflows/workflow-history/workflow-history.service.ts:72:10)
2025-12-08T15:46:48.1021412Z stdout F     at processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-12-08T15:46:48.1021428Z stdout F     at WorkflowService.update (/usr/local/lib/node_modules/n8n/src/workflows/workflow.service.ts:359:20)
2025-12-08T15:46:48.1021442Z stdout F     at WorkflowsController.update (/usr/local/lib/node_modules/n8n/src/workflows/workflows.controller.ts:411:27)
2025-12-08T15:46:48.1021455Z stdout F     at handler (/usr/local/lib/node_modules/n8n/src/controller.registry.ts:95:12)
2025-12-08T15:46:48.1021469Z stdout F     at /usr/local/lib/node_modules/n8n/src/response-helper.ts:161:17
2025-12-08T15:46:48.1021482Z stdout F `

**Comment by GauthierPLM** [comment]
I encounter the same issue with version 1.123.4. I confirm that editing the workflow, saving it and activating it solves the issue.

**Comment by erictmnz** [comment]
Same issue with version 1.123.1 - this is a critical issue for enterprise users as downstream environments should be protected instances and this breaks this control by having to manually edit the workflow.

As a side note - going into the workflow settings, not changing anything but hitting save does have the same effect.
That specific endpoint however (workflow patch with a settings payload) is not available via /api/v1 thus unfortunately not a viable pipeline workaround.

**Comment by luendres** [comment]
This has been addressed in this fix: Add version history records when importing workflows #22974

**Comment by GauthierPLM** [comment]
Hello :)
We upgraded to 1.123.5 but the issue persists on importing workflows:

```
 2025-Dec-12 11:58:14.940515 Could not remove webhooks of workflow "stFcIIjYJ1rVsss8" because of error: "Active version not found for workflow"
2025-Dec-12 11:58:14.947303 Active version not found for workflow
2025-Dec-12 11:58:14.947340 Error: Active version not found for workflow
2025-Dec-12 11:58:14.947347 at ActiveWorkflowManager.clearWebhooks (/usr/local/lib/node_modules/n8n/src/active-workflow-manager.ts:261:10)
2025-Dec-12 11:58:14.947376 at processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-Dec-12 11:58:14.947381 at ActiveWorkflowManager.remove (/usr/local/lib/node_modules/n8n/src/active-workflow-manager.ts:907:4)
2025-Dec-12 11:58:14.947386 at ImportService.importWorkflows (/usr/local/lib/node_modules/n8n/src/services/import.service.ts:84:5)
2025-Dec-12 11:58:14.947391 at ImportWorkflowsCommand.run (/usr/local/lib/node_modules/n8n/src/commands/import/workflow.ts:104:3)
2025-Dec-12 11:58:14.947396 at CommandRegistry.execute (/usr/local/lib/node_modules/n8n/src/command-registry.ts:67:4)
2025-Dec-12 11:58:14.947401 at /usr/local/lib/node_modules/n8n/bin/n8n:63:2 
```

This happens on a workflow with 12 Airtable triggers.
We have been able to fix it by modifying the DB to add a version number manually, but it's not really ideal.

**Comment by luendres** [comment]
Hey @GauthierPLM! 
When pulling workflows that didn't change from remote, n8n doesn't overwrite them, so to really see improvements, you need to push some changes first. 

Version 1.123.6 will be released soon, and this issue should be fixed when upgrading to it. If you wish, you can wait for a few more hours to try the new version. If so, please let me know whether the issue will be fixed after that.

If you don't want to wait, and:
You don't have lots of workflows you need to fix, you can just change anything about the specific workflow you need to fix (the name e.g.), push to remote, and then pull.

If you have lots of workflows, and you're pulling changes to a read-only instance, you can just delete all your workflows and pull from scratch. This will fix everything.

Thanks :)

**Comment by HermanPierre** [comment]
Hello, we still get the issue using the 1.123.6 version when importing workflows:
```Could not remove webhooks of workflow "yScQ7WjENuYclyua" because of error: "Active version not found for workflow"
Active version not found for workflow
Error: Active version not found for workflow
    at ActiveWorkflowManager.clearWebhooks (/usr/local/lib/node_modules/n8n/src/active-workflow-manager.ts:261:10)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ActiveWorkflowManager.remove (/usr/local/lib/node_modules/n8n/src/active-workflow-manager.ts:907:4)
    at ImportService.importWorkflows (/usr/local/lib/node_modules/n8n/src/services/import.service.ts:84:5)
    at ImportWorkflowsCommand.run (/usr/local/lib/node_modules/n8n/src/commands/import/workflow.ts:104:3)
    at CommandRegistry.execute (/usr/local/lib/node_modules/n8n/src/command-registry.ts:67:4)
    at /usr/local/lib/node_modules/n8n/bin/n8n:63:2
```

And it creates an issue when activating a workflow:
```
2025-Dec-16 14:10:53.593379
Execution 861561 (job 81060) finished
2025-Dec-16 14:12:33.006312
2025-Dec-16 14:12:33.006405
Error: 
2025-Dec-16 14:12:33.006416
at WorkflowHistoryService.getVersion (/usr/local/lib/node_modules/n8n/src/workflows/workflow-history/workflow-history.service.ts:82:10)
2025-Dec-16 14:12:33.006458
at processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-Dec-16 14:12:33.006470
at WorkflowService.update (/usr/local/lib/node_modules/n8n/src/workflows/workflow.service.ts:379:20)
2025-Dec-16 14:12:33.006479
at WorkflowsController.update (/usr/local/lib/node_modules/n8n/src/workflows/workflows.controller.ts:436:27)
2025-Dec-16 14:12:33.006620
at handler (/usr/local/lib/node_modules/n8n/src/controller.registry.ts:95:12)
2025-Dec-16 14:12:33.006634
at /usr/local/lib/node_modules/n8n/src/response-helper.ts:161:17
2025-Dec-16 14:12:33.006642
2025-Dec-16 14:12:35.947995
```
