### ISSUE TITLE
Error to fetch resources with a custom N8N_PATH

### ISSUE THREAD

**Issue by Madriax** [n8n-io/n8n#2651]
**Describe the bug**
Since the last update (0.157.0) I can no longer access to N8N due to 404 errors while fetching css and js resources. I'm runing N8N under **mywebsite.xxx/n8n/** but resources are being fetched from **mywebsite.xxx/css or /js**. 
For the older versions, I set the environment variable **N8N_PATH** to **/n8n/** and it was working fine.

**To Reproduce**
1. Deploy latest N8N Image in Kubernetes with Nginx ingress controller
2. Set **N8N_HOST** to **mywebsite.xxx**
3. Set **N8N_PATH** to **/n8n/**
4. Try to access to N8N and check the network tab in your console
5. See error

**Expected behavior**
Resources being fetch from **mywebsite.xxx/n8n/css or /js** based on the N8N_PATH like previous versions.

**Environment (please complete the following information):**
 - OS: Official Docker image of N8N
 - n8n Version 0.157.0
 - Node.js Version: Official Docker image of N8N
 - Database system: SQLite
 - Operation mode: own

**Comment by mutdmour** [comment]
thanks for reporting. I believe this should be fixed by this PR https://github.com/n8n-io/n8n/pull/2648

**Comment by n1xx1** [comment]
> thanks for reporting. I believe this should be fixed by this PR #2648

This was reverted in this #2655, so it's still broken. How do you get around the problem now?

**Comment by Madriax** [comment]
Hi @n1xx1 
In my case I reverted to an older version while waiting for a patch in a future update.

**Comment by n1xx1** [comment]
That's what I ended up doing, thanks @Madriax. 
I'm now on 0.155.2, but I can't wait to use the monaco editor in my code blocks!

**Comment by limxingzhi** [comment]
I have the same issue too, thanks for flagging it @Madriax

**Comment by kolobok22** [comment]
0.156.0 not working. 
0.155.1 work

**Comment by TrySound** [comment]
Still a problem with 0.162.0

**Comment by mutdmour** [comment]
We have started looking into this last week. Hopefully will update soon.

**Comment by janober** [comment]
Fix got merged with #2816 and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.165.0`

**Comment by limxingzhi** [comment]
Can confirm it is resolved with 0.165.1

**Comment by browser-bug** [comment]
I'm still getting the same error described with:
```
docker run -it --rm -e N8N_PATH=/n8n/ \
    --name n8n-test \
    -p 5678:5678 \
    -v /tmp/n8n:/home/node/.n8n \
    n8nio/n8n:0.165.1
```
Am I missing some other steps in the middle?

**Comment by pbac-sk** [comment]
I'm getting status 404 for .js and .css resources. Tried with versions 0.165.1 and 0.173.1
```
docker run -it --rm \
--name n8n \
-p 5678:5678 \
-v ~/.n8n:/home/node/.n8n \
-e N8N_USER_MANAGEMENT_DISABLED=true \
-e N8N_PATH=/n8n/ \
n8nio/n8n:$VERSION
```

**Comment by mutdmour** [comment]
@browser-bug @pbac-sk you still need some form of reverse proxy to ensure resources are loaded behind the correct path. You can see an example here to do that using traefik https://github.com/n8n-io/n8n/tree/master/docker/compose/subfolderWithSSL
to confirm fix is working, check the failing resources.. do they have the path in them?

**Comment by browser-bug** [comment]
@mutdmour yes I can confirm that behind a reverse proxy it works as it supposed to.

**Comment by mutdmour** [comment]
@browser-bug can you double check the failing requests and confirm subfolder path is not getting set correctly?

**Comment by ericsala** [comment]
@mutdmour @janober  is there any other option i should use with a nginx reverse proxy ? I've read about EventSource im other thread but still not working 😔
I receive HTML page without all CSS and JS.

**Comment by that-one-tom** [comment]
Hi @ericsala I am sorry to hear you're having trouble.

I just had a quick look over your docker command + nginx config and I am not sure this is the same problem as originally reported here. You don't seem to be setting the `N8N_PATH` environment variable in docker at all. Perhaps you can reach out on our forum at https://community.n8n.io/ with your full nginx config (including `location`) so we can take a closer look?

**Comment by jmls** [comment]
I'm getting the same error  - 404 with N8N_USER_MANAGEMENT_DISABLED=true or 401 without N8N_USER_MANAGEMENT_DISABLED set

`docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n -e VUE_APP_PUBLIC_PATH=/n8n/ -e N8N_PATH=/n8n/  -e N8N_USER_MANAGEMENT_DISABLED=true n8nio/n8n
`
If I run without the -e 

`docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n n8nio/n8n`

then I get a add user form

running with

```
`docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n -e N8N_USER_MANAGEMENT_DISABLED=true n8nio/n8n
```
then I get to the n8n main screen

Why would adding the sub path give 401 and 404 ?

**Comment by jmls** [comment]
> @browser-bug @pbac-sk you still need some form of reverse proxy to ensure resources are loaded behind the correct path. You can see an example here to do that using traefik https://github.com/n8n-io/n8n/tree/master/docker/compose/subfolderWithSSL to confirm fix is working, check the failing resources.. do they have the path in them?

why would we need to have a proxy that rewrites the path ? 

      
```
- 'traefik.http.routers.n8n.rule=PathPrefix(`/${SUBFOLDER}{regex:$$|/.*}`)'
- 'traefik.http.middlewares.n8n-stripprefix.stripprefix.prefixes=/${SUBFOLDER}'
- 'traefik.http.routers.n8n.middlewares=n8n-stripprefix'

```

**Comment by shotor** [comment]
Still an issue for me, https://github.com/n8n-io/n8n/tree/master/docker/compose/subfolderWithSSL gives me 404.

I changed to this, because als @jmls mentions if we're running on a subpath, we shouldn't have to strip the prefix.

With this config I get a 401 on every asset. Tried all kinds of combinations with the env vars, but no dice

```
version: "3.7"

services:
  initContainer:
    image: busybox
    command: ['sh', '-c', 'chown -R 1000:1000 /home/node/.n8n']
    volumes:
      - n8n_data:/home/node/.n8n

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`example.org`) && PathPrefix(`/n8n`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=cloudflare"
        #- "traefik.http.middlewares.n8n-stripprefix.stripprefix.prefixes=/n8n"
        #- "traefik.http.routers.n8n.middlewares=n8n-stripprefix"
      - "traefik.http.middlewares.n8n.headers.SSLRedirect=true"
      - "traefik.http.middlewares.n8n.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.n8n.headers.browserXSSFilter=true"
      - "traefik.http.middlewares.n8n.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.n8n.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.n8n.headers.SSLHost=workloads.shotor.casa"
      - "traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true"
       - "traefik.http.routers.n8n.middlewares=n8n"
      - "traefik.http.middlewares.n8n.headers.STSPreload=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    environment:
      - "N8N_USER_MANAGEMENT_DISABLED=true"
      - "VUE_APP_PUBLIC_PATH=/n8n/"
      - "N8N_HOST=example.org"
      - "N8N_PORT=5678"
      - "N8N_PROTOCOL=https"
      - "N8N_PATH=/n8n/"
      - "NODE_ENV=production"
      - "WEBHOOK_URL=https://example.org/n8n/"
      - "GENERIC_TIMEZONE=Europe/Berlin"
      - "N8N_BASIC_AUTH_ACTIVE=true"
      - "N8N_BASIC_AUTH_USER=user"
      - "N8N_BASIC_AUTH_PASSWORDS=user"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "n8n_data:/home/node/.n8n"
    networks:
      - default
    depends_on:
      initContainer:
        condition: service_completed_successfully

volumes:
  n8n_data:
    external: true

networks:
  default:
    name: apps
    external: true
```

**Comment by sh4dowmyst1c** [comment]
Hello,

I'm currently working on a setup and ran into what seems to be a recurring issue, so I wanted to share my experience in case it's helpful to others or worth clarifying in the documentation.

I'm having a similar problem:

> docker-compose.yaml

```yaml
volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: "0:0"
    environment:
      - GENERIC_TIMEZONE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
      - DB_TYPE
      - DB_POSTGRESDB_HOST
      - DB_POSTGRESDB_PORT
      - DB_POSTGRESDB_DATABASE
      - DB_POSTGRESDB_USER
      - DB_POSTGRESDB_PASSWORD
      - N8N_SECURE_COOKIE
      - N8N_HOST
      - N8N_PORT
      - N8N_PROTOCOL
      - NODE_ENV
      - WEBHOOK_URL
      - N8N_RUNNERS_ENABLED
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
      - N8N_PROXY_HOPS
      - N8N_PATH
      - N8N_ENDPOINT_REST
      - N8N_ENDPOINT_WEBHOOK
      - N8N_ENDPOINT_WEBHOOK_TEST
      - N8N_ENDPOINT_WEBHOOK_WAIT
      - VUE_APP_URL_BASE_API
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
      - /home/lsilvpin/volumes/n8n:/home/node/volume
    depends_on:
      postgres:
        condition: service_healthy

```

> .env

```markdown
POSTGRES_USER=my_postgres_user
POSTGRES_PASSWORD=my_postgres_pass
POSTGRES_DB=my_postgres_db
POSTGRES_NON_ROOT_USER=my_non_root_user
POSTGRES_NON_ROOT_PASSWORD=my_non_root_pass

DOMAIN_NAME=mydomain.com
GENERIC_TIMEZONE=America/Sao_Paulo

DB_TYPE=postgresdb
DB_POSTGRESDB_HOST=postgres
DB_POSTGRESDB_PORT=5432
DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
N8N_SECURE_COOKIE=false
N8N_HOST=${DOMAIN_NAME}
N8N_PORT=5678
N8N_PROTOCOL=https
NODE_ENV=production
GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
N8N_RUNNERS_ENABLED=true
N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_PROXY_HOPS=1

N8N_PATH=/n8n/
N8N_ENDPOINT_REST=n8n/rest
N8N_ENDPOINT_WEBHOOK=n8n/webhook/
N8N_ENDPOINT_WEBHOOK_TEST=n8n/webhook-test/
N8N_ENDPOINT_WEBHOOK_WAIT=n8n/webhook-waiting/

VUE_APP_URL_BASE_API=https://${DOMAIN_NAME}${N8N_PATH}

```

> Dockerfile

```markdown
FROM docker.n8n.io/n8nio/n8n
```

> init.sql

```markdown

CREATE USER n8n_user WITH PASSWORD 'my_non_root_pass';
GRANT ALL PRIVILEGES ON DATABASE my_postgres_db TO my_non_root_user;
GRANT CREATE ON SCHEMA public TO my_non_root_user;

```

I adjusted the variables `N8N_PATH`, `N8N_ENDPOINT_REST`, `N8N_ENDPOINT_WEBHOOK`, `N8N_ENDPOINT_WEBHOOK_TEST`, and `N8N_ENDPOINT_WEBHOOK_WAIT` as shown above, so that the resources could be accessed under `https://mydomain/n8n/`.

After testing via Docker Compose (my goal is to deploy it in Kubernetes later), I noticed that the assets, REST endpoints, and base path are all being built correctly, and all requests return 200. However, nothing appears on the browser screen. After trying many variations of these five variables, I came to the conclusion that it simply doesn't work.

> Some evidence from the browser after running docker compose up.

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/d04a73a6-1475-4fa5-8da4-f39bdb6e552b" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/0ce99224-3a24-412e-a44a-e28e00419353" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/fb07202f-481e-47f7-ad45-6eabdce756c1" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/e82e9e6f-3ffc-4856-9cb0-ac0354156295" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/8f033fe9-4f1d-48c3-a146-397fa94dccd5" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/cd408bd2-3ff2-4043-947e-6dfc701e0407" />

<img width="1919" height="983" alt="Image" src="https://github.com/user-attachments/assets/0ada24d9-75f5-4b16-9ee6-b401570bfbbc" />

As you can see from the evidence above, all files—such as .js, .css, the REST API, and others—are being correctly built under the /n8n path and are returning 200 responses. However, it is also evident that nothing is displayed on the screen. In other words, it seems the application might not be properly served from the configured sub-paths defined by N8N_PATH and the related variables. If this configuration is indeed not currently supported, perhaps it would be helpful to mention that in the documentation to avoid confusion. Of course, my hope is that this can eventually be resolved, and I truly appreciate all the work that has gone into building n8n. Thank you!
