### ISSUE TITLE
Error on `lerna bootstrap --hoist`

### ISSUE THREAD

**Issue by chrisgereina** [n8n-io/n8n#2675]
**Describe the bug**
While following the CONTRIBUTING.md guide, I forked n8n and cloned my version, cd'ed into n8n, and then ran `lerna bootstrap --hoist`

This command failed with the following output:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/colors/-/colors-1.4.1.tgz - Not found
npm ERR! 404 
npm ERR! 404  'colors@https://registry.npmjs.org/colors/-/colors-1.4.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2022-01-12T20_57_28_858Z-debug.log
lerna ERR! npm install exited 1 in 'n8n'
```

It seems there is a missing dependency that is causing this error, the url given by the error output `https://registry.npmjs.org/colors/-/colors-1.4.1.tgz` is a dead link

**To Reproduce**
1. Fork n8n
1. Clone your fork
1. Cd into `n8n`
1. Run `lerna bootstrap --hoist`

**Expected behavior**
No error

**Environment (please complete the following information):**
 - OS: Ubuntu | 20.04.3 LTS 64-bit
 - Node.js Version | v16.13.1

**Comment by janober** [comment]
Please try again with Node.js v14 as documented in the CONTRIBUTING.md guide:
![Screenshot from 2022-01-12 23-20-33](https://user-images.githubusercontent.com/6249596/149232200-61ee29bd-bd3c-4021-a9e9-df1ec1ec4c29.png)

**Comment by janober** [comment]
Actually just tested with Node.js v14 there it displays me some other error.

So v16 will definitely not work but right now there seems now also be something with v14 wrong. We have to look into that some more tomorrow.

**Comment by chrisgereina** [comment]
@janober thanks for looking into this, really excited about contributing since n8n has been so good to me

**Comment by janober** [comment]
That is really great to hear and appreciated @chrisgereina ! Looking forward to your first contribution!

I had now a look. The problem got caused by the `package-lock.json` file. It should now work fine.

**Comment by RachaelSMathew** [comment]
> That is really great to hear and appreciated @chrisgereina ! Looking forward to your first contribution!
> 
> I had now a look. The problem got caused by the `package-lock.json` file. It should now work fine.

Hi, I'm currently using NextJS to create a web application. I have done `npm install n8n` in my project directory and then ran `npm install` and I am still getting this error 
<img width="573" alt="Screen Shot 2022-01-15 at 8 52 56 PM" src="https://user-images.githubusercontent.com/30049533/149644272-b8ba47ef-3fba-4694-bb58-70ec9d04a258.png">

**Comment by janober** [comment]
@RachaelSMathew Please open a new issue and fill in all the requested information. Thanks!
