### ISSUE TITLE
Native crypto module could not be used to get secure random number.

### ISSUE THREAD

**Issue by le-ross** [n8n-io/n8n#300]
I just installed n8n on win10 with `npx n8n` but every time I try to create some credentials (either google drive or gitlab) I get hit with the following error:

```
ERROR RESPONSE
Error: Native crypto module could not be used to get secure random number.
    at secureRandom (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\core.js:45:16)
    at Object.random (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\core.js:337:30)
    at Object.execute (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:786:35)
    at Object.encrypt (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:837:42)
    at Object.encrypt (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:201:59)
    at Credentials.setData (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\n8n-core\dist\src\Credentials.js:20:37)
    at app.post._1.ResponseHelper.send (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\dist\src\Server.js:379:25)
ERROR RESPONSE
Error: Native crypto module could not be used to get secure random number.
    at secureRandom (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\core.js:45:16)
    at Object.random (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\core.js:337:30)
    at Object.execute (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:786:35)
    at Object.encrypt (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:837:42)
    at Object.encrypt (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\crypto-js\cipher-core.js:201:59)
    at Credentials.setData (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\node_modules\n8n-core\dist\src\Credentials.js:20:37)
    at app.post._1.ResponseHelper.send (C:\Users\LeChat\AppData\Roaming\npm-cache\_npx\15140\node_modules\n8n\dist\src\Server.js:379:25)
```

**To Reproduce**
each time I presson create

![image](https://user-images.githubusercontent.com/7969065/74190973-2f55b800-4c21-11ea-8cbf-6ad60ee1876d.png)

**Expected behavior**
I should be able to create some credentials

**Environment (please complete the following information):**
 - OS: win10
 - n8n Version 0.52.0
 - Node.js  10.15.1
 - npm 6.13.7

**Additional context**
none

**Comment by janober** [comment]
Yes, something seems to have changed. Also the current build just failed with the same error:
https://github.com/n8n-io/n8n/commit/05c64341e6105abf9634c3815e22fe4d19132fbf/checks?check_suite_id=449509322

Will check it out.

**Comment by janober** [comment]
Btw. the docker-containers should still work fine because they got generated before whatever outside dependency changed in the last 15 h.

**Comment by janober** [comment]
Ok got fixed by hardcoding "crypto-js" to a fixed version as the new one seems to break things. 

It took me quite a while to figure out. Even though it was one of the first things I thought could be the reason, I did not look into it further as according to https://www.npmjs.com/package/crypto-js the latest version is `3.1.9-1` and that is the version that got used from the start. Anyway, after nothing else worked I checked again and realized that there is a version `3.2.0` which gets installed even though it does not get displayed by npm. No idea what is going on with their website or npm in general. At least are happy that it now works again.

**Comment by le-ross** [comment]
> 
> 
> Ok got fixed by hardcoding "crypto-js" to a fixed version as the new one seems to break things.
> 
> It took me quite a while to figure out. Even though it was one of the first things I thought could be the reason, I did not look into it further as according to https://www.npmjs.com/package/crypto-js the latest version is `3.1.9-1` and that is the version that got used from the start. Anyway, after nothing else worked I checked again and realized that there is a version `3.2.0` which gets installed even though it does not get displayed by npm. No idea what is going on with their website or npm in general. At least are happy that it now works again.

Excellent. thanks

Do i have to go through the repo with `npm start` to test it? because with `npx n8n` is still the same issue.

**Comment by janober** [comment]
Ah yes did not think about the npx case. Yes, that will still fail as the currently released version of n8n does still not have the fixed version. For now, you have to either clone the repository or use the docker-image (the easiest). I will try to release a new version later today to make it also work with npm again.
