### ISSUE TITLE
NocoDB API Change since version 0,9

### ISSUE THREAD

**Issue by lubeda** [n8n-io/n8n#3170]
the nocodb node isn't working with nocodb Version from 0.9

the nocodb api changed with the new version see here https://all-apis.nocodb.com/#tag/DB-table-row and here **https://github.com/nocodb/nocodb/issues/1564**

**Comment by Joffcom** [comment]
Hey @lubeda,

It looks like a PR has been submitted to resolve this here #3146 it won't help with the old URLs not working but it will mean you should be able to use the newer paths.

**Comment by Joffcom** [comment]
Hey @lubeda,

It looks like `v0.90.7` of NocoDB should now work with the older APIs although it looks like the data structure has changed so you may need to update your workflow a bit.

I think we can mark this one as solved for now as the initial issue is solved for now, What do you think?

**Comment by ed-parsadanyan** [comment]
I have tested with the docker NocoDB `v0.90.8` today. It seems that NocoDB node is able to GET data, however when I try to update the database I still see error:

```
{"name":"NodeApiError","cause":{"message":"404 - \"<!DOCTYPE html>\\n<html lang=\\\"en\\\">\\n<head>\\n<meta charset=\\\"utf-8\\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot PUT /nc/n8n_multilang_bot_wzhb/api/v1/TG_users/bulk</pre>\\n</body>\\n</html>\\n\"","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"node":{"parameters":{"resource":"row","operation":"update","projectId":"n8n_multilang_bot_wzhb","table":"TG_users","id":"={{$node[\"CheckUser\"].json[\"id\"]}}","dataToSend":"defineBelow","fieldsUi":{"fieldValues":[{"fieldName":"TG_account_ID","binaryData":false,"fieldValue":"={{$node[\"chatID\"].json[\"chatID\"]}}"},{"fieldName":"Last_language_used","binaryData":false,"fieldValue":"={{$node[\"Telegram Trigger\"].json[\"message\"][\"from\"][\"language_code\"]}}"}]}},"name":"UpdateUser","type":"n8n-nodes-base.nocoDb","typeVersion":1,"position":[1100,380],"notesInFlow":true,"credentials":{"nocoDb":{"id":"13","name":"NocoDB n8n multilang bot"}}},"timestamp":1651138686064,"message":"The resource you are requesting could not be found","httpCode":"404","description":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot PUT /nc/n8n_multilang_bot_wzhb/api/v1/TG_users/bulk</pre>\n</body>\n</html>\n"}
```

**Comment by Joffcom** [comment]
Hey @ed-parsadanyan,

Looks like there could still be an issue with the API then, I will set up a new Nocodb instance locally on the latest release and test it.

**Comment by o1lab** [comment]
@ed-parsadanyan : till the new PR gets merged. If you want to, you can please use our [new APIs](https://apis.nocodb.com/#tag/DB-table-row/operation/db-table-row-bulk-update) via http. I see you are trying to do a bulk update.

**Comment by dominikmukrecki** [comment]
I confirm that issue still exists. HTTP requests work fine, but the NocoDB node does not. 

NocoDB version: 0.91.0

**Comment by Joffcom** [comment]
Hey @Zapfmeister,

Yes there have been a few more tweaks to the PR opened and it is now in the final review stage so unless anything urgent pops up it will hopefully be in one of the next releases

**Comment by luizeof** [comment]
In version 0.187.2 Node works, but the filter parameters do not work

the request is sent do old api endpoint.

`
GET /nc/p_mdq0kuqlah85ls/api/v1/leads?where=%28email%2Cneq%2Cnull%29&limit=50
`

**Comment by Joffcom** [comment]
@luizeof in theory the node only partially supports newer versions of NocoDB. The API routes were changed and the PR we have open brings in support for the newer URIs.

**Comment by zblesk** [comment]
The behavior I see is: I can get or list data, but updates fail _silently._  Even if I just make the simplest node and hard-code an ID and a single column to set, the component reports success, but no data is changed in NocoDB.

**Comment by Joffcom** [comment]
Hey @zblesk,

Could you pop open a new issue for that one and include your n8n version and nocodb version?

**Comment by Joffcom** [comment]
Looks like we forgot to close this one, The changes for 0.90.0 were released in 0.189.0
