### ISSUE TITLE
n8n detected that some packages are missing.

### ISSUE THREAD

**Issue by TheSmilez** [n8n-io/n8n#4771]
**Describe the bug**
Every time n8n is restarted, I get an error message on the console: ```n8n detected that some packages are missing.```

![Code_8y5Vxknx2k](https://user-images.githubusercontent.com/52396069/204813162-4405bdf3-dc64-40fd-8c62-7b471ce2a7d7.png)

I also receive an error on the browser in `localhost:5678/settings/community-nodes`.
I've checked with multiple nodes thinking it was just one, but they all seem to do the same.
>**The weirdest part is that the nodes seem to run fine for the most part --- *without installing them again*.**

**Tested multiple instances with both npm and Docker on 4 separate machines with the same results.**

![brave_hdflQ3djNP](https://user-images.githubusercontent.com/52396069/204812492-562cefa3-5832-40ba-aeac-27d48a45052b.png)
![brave_swY64mKag4](https://user-images.githubusercontent.com/52396069/204814454-7b4bf6de-6de3-42e3-90a8-f2196da2b3cd.png)

**To Reproduce**
Steps to reproduce the behaavior:
1. Install n8n
2. Install a community node
3. Shut down n8n
4. Run n8n again
5. See error

**Expected behavior**
I expect n8n to run without any errors.

**Environment (please complete the following information):**
- OS: Windows 10 x64 / Linux (Docker)
- n8n Version: 0.204.0
- Node.js Version: 18.12.1
- Database system: SQLite / MariaDB (Tried both)

**Additional context**
Please note that I have already tried the trouble shooting methods provided in https://docs.n8n.io/integrations/community-nodes/troubleshooting/

**Comment by Joffcom** [comment]
Hey @TheSmilez,

Thanks for taking the time to report this one, I have just taken a quick look and have managed to reproduce it. I have created a dev ticket which we will be tracking internally as `N8N-5798`.

**Comment by netroy** [comment]
The packages aren't actually missing, they were simply not listed in a new mapping that we recently added to keep track of what nodes are available without having to actually load all the nodes, and I forgot to add community nodes to this map.
Fixed in https://github.com/n8n-io/n8n/pull/4775.

**Comment by Joffcom** [comment]
Hey @TheSmilez,

The fix for this has been released with n8n@0.205.0

**Comment by radiumx3** [comment]
Hmmm; It still occurs as of today, is there a regression somehow in latest version  ?
