### ISSUE TITLE
ALERT! - for /types/credentials.json - make my domain list by google Dangerous: Avoid this site. If you get a full-page red warning screen,

### ISSUE THREAD

**Issue by mzayn** [n8n-io/n8n#5743]
hello team support N8N,

for the latest version N8N, when i used got warning by google - Dangerous: Avoid this site. If you get a full-page red warning screen,

when i check the log scan form my site most active retrieve at this link - /types/credentials.json can see all details the api and credential. 

Hope your team can fix this ASAP.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] - Ubuntu 22.04.2 LTS aarch64(Py3.7.8)
- n8n Version [e.g. 0.200.1] - 0.220.0
- Node.js Version [e.g. 16.17.0] - 16.19.0
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] - default
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`] 

**Additional context**

![image](https://user-images.githubusercontent.com/15009301/226627690-59bf4ffc-146b-4b34-87e2-58ae1738f53d.png)

**Comment by luizeof** [comment]
same here.

**Comment by janober** [comment]
Thanks a lot for reporting this.

But just to make it clear. No credentials are leaked, what gets returned by that endpoint are not the credentials, just its description. Meaning it does not return information like "Google Password = 1234" it just is the definition of how a Google credential (and others) look like. For example that a Google credential contains a password field which is a string. So all is secure, and there is no reason to worry.

But it looks like Google does not understand that and is so overprotective. In a new release, we will also add authentication to that endpoint to make sure that Google has no way of misunderstanding it.

**Comment by janober** [comment]
Actually just saw that a PR got already created for that #5745

**Comment by luizeof** [comment]
@janober I updated the N8N to version 0.200.1 and the error still appears. I have cases here of people who have more than 20 N8N with this desperate error message.

![CleanShot-2023-03-22-at-15-38-25-cópia](https://user-images.githubusercontent.com/257004/227007368-4b2f813a-5e0e-44d6-855c-2fe70e64a298.png)

**Comment by janober** [comment]
That is expected. Nothing regarding that has been changed in that version. A new version will be released tomorrow.

**Comment by mzayn** [comment]
any idea how to solved with google for this ?

**Comment by luizeof** [comment]
> any idea how to solved with google for this ? 

https://safebrowsing.google.com/safebrowsing/report_error/

**Comment by luizeof** [comment]
@Joffcom @janober 

I have reports of users still receiving phishing messages on the url https://domain.com/signin?redirect=/

Version 0.222.0

Could it be that there are still exposed files that Google understands is a leak? Or even a library?

**Comment by luizeof** [comment]
I verified that the `types/credentials.json` file is protected. Now the error is displayed by the `/signin` page

**Comment by mzayn** [comment]
@Joffcom  @janober 

i was update the latest version and got error 

![image](https://user-images.githubusercontent.com/15009301/229263959-f1ddc58e-8702-4483-8992-391886147b96.png)

use n8nio/n8n:latest

hope can help

**Comment by Joffcom** [comment]
Hey @mzayn,

We pulled the 0.222.0 release due to some issues, At the moment we would expect latest / 0.222.0 to fail.

**Comment by FlavioGuardia** [comment]
And the problems with the malicious website alert have now gained new status. It is not enough to mark it as Pishing, now the consequence is to block the DNS preventing the propagation of the domain.

History: I installed the N8N on 4/5/203 and after less than 24 hours the malicious website screen appeared on the domain and all subdomains.

I reported to Google that it was an error and requested the withdrawal. 8 hours later the situation got worse, as Google informed Radix that it blocked DNS propagation.

I was building a stream that took me 4 hours to make, still not backed up, when the N8N lost connection. I restarted the screen and the error appeared:

"DNS_PROBE_FINISHED_NXDOMAIN"

I went to the company that made the resale (HOSTINGER) and the attendant informed that it was RADIX, superior authority, who determined the blockage.

I went to RADIX who informed me that it was Google who registered the site as malicious and requested immediate blocking. Even after my dispute in the URL that Google makes available, even after adding the domain in Google Search Console, the decision was that the site was malicious, fraudulent, and all this because of the ALREADY KNOWN ERROR OF N8N, which apparently did not is not at all worried about the damage that this situation is causing, because as you can see from the reports here on Github, several people have already complained.

Will I be just another number in statistics?

![image](https://user-images.githubusercontent.com/75942905/230535229-3d694c7c-2a2d-4449-89f2-8b77036e8f81.png)

www.n8n.controlando.store

**Comment by Joffcom** [comment]
Hey @FlavioGuardia 

Which version of n8n did you install? A fix went out in 221.1 that should stop the credential.json from being flagged, we are still monitoring reports to see if any other parts are being flagged.

While this is very frustrating we don't get notified about this other than user reports so the more information we have in the report the quicker we can resolve these.

Which url was mentioned in the report?

**Comment by janober** [comment]
Very sorry to hear that you still have problems. But as you can see when you scroll up, did we take immediately action against that "issue" and "fixed it" (even though there was actually nothing wrong, and it is "just" a Google false-positive). If there would be any way to talk with Google about it and get them to fix it or get more information we would, but as you can imagine, that is pretty much impossible for a company of our size. The only thing we can do is to try to work with the little information we have, and we try.

Can you please share which n8n version you are using (or used if that for example also changed) and can you please also share all the information Google did provide (which is normally not very much which makes that even harder and more annoying). After all, do just very few of our users report that issue, and we are sadly not one of them. Meaning we are totally reliant on the information we receive for our users on that. So please share what you can and what exactly the issue is now. Because the credentials file is not accessible anymore and I currently do not understand what is supposed to be wrong with the `signin` page. Thanks a lot for your help!

**Comment by mzayn** [comment]
> @Joffcom @janober
> 
> i was update the latest version and got error
> 
> 1. use command >  n8nio/n8n:0.222.0 (got error installation)
> 
> ![image](https://user-images.githubusercontent.com/15009301/229264231-02eebe95-cf55-4bc3-876b-99320af6cbe7.png)
> 
> 2. use command >  n8nio/n8n:latest  (success got error like below)
> 
> ![image](https://user-images.githubusercontent.com/15009301/229263959-f1ddc58e-8702-4483-8992-391886147b96.png)
> 
> so now i was revert to version [0.221.2](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2) success
> 
> hope can help and fix for this.
> 
> Thanks

off topic, for this version was been fix ? i want to update n8n to latest  version

**Comment by Joffcom** [comment]
Hey @mzayn,

That should be good to go now, I have my home instance on portainer running n8n 0.223.0 at the moment but the latest tag (222.1) should also now work.

**Comment by FlavioGuardia** [comment]
Unfortunately I no longer have access to the version that was installed and I had to format the VPS.

But, to collaborate with the investigation, I inform you that I uploaded the container on April 4, 2023, using the latest parameter, that is, the most current version for that date.

As for the domain reseller's response, they only stated that the propagation of the domain was blocked by RADIX:

"The serverHold status is set in the registration part. After receiving the status, the domain no longer propagates DNS so it is not responding (displays error DNS_PROBE_FINISHED_NXDOMAIN). The reason behind this is usually a complaint from the brand owner registered, sending spam or malware / misleading content on the site. That is, it is active and working here, but the body responsible for .online, .site, .store, .space, .tech, etc. ) suspended him."

When consulting RADIX, I was informed that the blocking was at the request of Google which, after my objection stating that it was not phishing, denied the request to remove the alert from the fraudulent site and, on top of that, asked for the blocking of the propagation.

On Google, the only thing they answer is: "Your site has been identified as a threat. If you think there is a mistake, submit your URL for review."

After submitting it again for review, Google continues to block it and insists that there is malicious code and that I am practicing Social Engineering, in addition to fraudulently collecting user information.

It is important to make it clear that only Portainer and N8N were installed in the VM.

The domain is the same as informed in the previous message.

n8n.controlling.store

I hope this information helps with the investigation.

Flavio Guardia

**Comment by luizeof** [comment]
@janober Google reported the problem with /types/credentials.json .. after 0.221.1 this file started to be blocked. However, as I reported, the google search console also started to register problems in /signin . I believe it could be some library or something that google understands is phishing.

I've seen at least 5 domains that started to report a problem in /signin after the correction in /types/credentials.json.

**Comment by luizeof** [comment]
Before blocking a domain, Google generates alerts in Search Console, where we can report the false-positive.

Without Search Console I believe google blocks it immediately.

**Comment by diegosefrin** [comment]
Hello everybody!

I'm facing the same problem of false positive alerting the ""/signin"" in version 0.222.1.

I don't know if there's a correlation, but the google nodes are disconnecting the credentials.

**Comment by buchakow** [comment]
> @janober Google reported the problem with `/types/credentials.json`. after `0.221.1` this file started to be blocked. However, as I reported, the google search console also started to register problems in `/signin` . I believe it could be some library or something in the code that google understands is phishing.
> 
> I've seen at least 5 domains that started to report a problem in `/signin` after the correction in `/types/credentials.json`.

Hi! Have some problem with Google - my version is 0.206.1 .

**Comment by Joffcom** [comment]
Hey All,

This should now be fully resolved, We have not had a report for about a month or so now. I am going to mark this as closed and if anyone notices it again let me know and we can open this.

**Comment by Avasond** [comment]
Hello, I just updated my instance of N8N after neglecting it for a moment and I'm now getting flagged by Google Safe Browsing as well. I was about 30 updates behind when I updated - whoops! I submitted a review to Google but it's flagged my entire personal domain for several days.

**Environment (please complete the following information):**

Docker: 19.03.12
Ubuntu 20.04
n8n: 1.6.1

**Comment by Joffcom** [comment]
Hey @Avasond,

Chances are you may have been on the version before the fix and it is a delayed hit.

It might be worth submitting as a false positive report and scanning it with something like https://quttera.com/website-malware-scanner

**Comment by WeihanLi** [comment]
Still got this warning, deployed with the latest docker image tag a few hours ago
![Image](https://github.com/user-attachments/assets/c0e3db1c-c56e-4508-a55e-9cf96e9994e7)

**Comment by netroy** [comment]
@WeihanLi it's likely because of the `n8n.` in the domain name. Try using another subdomain.

**Comment by WeihanLi** [comment]
> it's likely because of the `n8n.` in the domain name. Try using another subdomain.

So wired, it did work when changed to another subdomain
