### ISSUE TITLE
Using 2FA authenticator app also consumes backup 2FA passcodes

### ISSUE THREAD

**Issue by jbusuttil** [n8n-io/n8n#7907]
**Describe the bug**
When using 2FA authentication using an authenticator app, after 10 logins, a pop-up message will indicate all backup passcodes have been consumed, and will suggest disabling and re-enabling 2FA to regenerate passcodes.

**To Reproduce**

1. Enable 2FA
2. Log in 10 times with 2FA authenticator app (not using backup passcodes)
3. Observe pop-up message on 10th login

**Expected behavior**
2FA using authenticator app should not (appear to) consume backup passcodes

**Environment (please complete the following information):**

- OS: Debian bookworm (12) (running inside LXD container, host OS also Debian bookworm 12)
- n8n Version 1.16.0
- Node.js Version 18.13.0
- Database system SQLite
- Operation mode main

**Additional context**
[Updated] Vanilla install using `npm install -g n8n`

**Comment by Joffcom** [comment]
Hey @jbusuttil,

I have just tried to give this a go using my self hosted install and it appears to be ok, Do you only see this when running from source and which commands are you using to launch n8n?

**Comment by jbusuttil** [comment]
Correction (my bad): I had installed using `npm install -g n8n` (not source as originally posted, bug report edited)

n8n is launched from systemd:

```
[Unit]
Description=n8n v1.16.0 server
After=syslog.target network.target

[Service]
Environment="N8N_CONFIG_FILES=/opt/n8n/production.json" "WEBHOOK_URL=https://[redacted]"
WorkingDirectory=/opt/n8n
ExecStart=/usr/local/bin/n8n start
Type=simple
Restart=always
RestartSec=10
SyslogIdentifier=n8n
User=n8n
Group=n8n

[Install]
WantedBy=multi-user.target
```

**Comment by jbusuttil** [comment]
Just to update on this, I disabled and re-enabled 2FA to regenerate the recovery codes, then I continued to log in using the authenticator app (again not using the recovery codes). After 10 logins, the same notification pops up to tell me that all the recovery codes have been used. I've disabled 2FA for the time being.

**Comment by Joffcom** [comment]
Hey @jbusuttil,

Some good news on this one, This issue was fixed in the `1.20.0` release of n8n with the PR below so an upgrade should get you up and running again.

https://github.com/n8n-io/n8n/pull/7936

**Comment by jbusuttil** [comment]
Hi @Joffcom - I've just upgraded to `1.20.0` - I'm assuming the 2FA issue is fixed as you've kindly highlighted, so I'll close this and reopen if not. Thanks!

**Comment by jbusuttil** [comment]
![image](https://github.com/n8n-io/n8n/assets/3918249/0ecbbe53-d947-45a8-b66e-ca5a52c61158)

Alas - still seeing the same problem in `1.20.0` - reopening

**Comment by Joffcom** [comment]
Hey @jbusuttil 

That isn't good I will get the internal ticket opened again.

While it does use up the recovery codes you should still be able to use MFA, the downside though is if you do need to use a recovery code you will need to use the cli to disable MFA for your user.

**Comment by Joffcom** [comment]
Hey @jbusuttil,

I have just been trying to reproduce this again on a clean `1.22.0` install and this doesn't appear to be an issue now. Can you check again to see if it is working for you as well?

**Comment by jbusuttil** [comment]
I've tested with 1.22.1, but **not on a clean install.** 

Test 1: After enabling MFA, the notification pops up that all recovery codes have been exhausted, as before.

![image](https://github.com/n8n-io/n8n/assets/3918249/1cf0bd05-94d3-4955-9b54-babe8e986204)

Test 2: I stayed logged in with my original browser (firefox), then I logged in from a different browser (chrome) while MFA was still enabled. I was able to log in and out in chrome repeatedly using MFA + auth app, despite further warning messages that my recovery codes were exhausted.

Test 3: In chrome, which had popped up the warning notification that I had no recovery codes left, I was able to log in using one of the recovery codes.

So a possible explanation is that only the warning notification itself is spurious. Thanks again for your help looking into this!

**Comment by Joffcom** [comment]
Hey @jbusuttil,

Your log seems to be from `1.21.1` not `1.22.1` are you sure you updated?

For some reason no matter what I do I am not able to reproduce this, How many attempts are you doing before it showed the message? I got up to 30 this time before I was happy it was all good. Do you see the message on every authentication attempt, Is your user the owner or a normal user?

When you enabled MFA did it pop up instantly to say the codes had been used or did it generate new codes for your user?

**Comment by jbusuttil** [comment]
@Joffcom Sorry - typo in the version number, should have been 1.21.1 (current 'latest' using `n8n update` at time of writing). I've updated the earlier comment to avoid confusion. (It's a production system, so I'm sticking to prod releases; I don't have a handy spare place to test other versions at the moment.)

(referring to [my earlier comment](https://github.com/n8n-io/n8n/issues/7907#issuecomment-1875597557)

Test 1: I logged in 4 times using MFA+app in firefox to get the first notification on the fourth login

Test 2: I logged in 2 further times in chrome using MFA+app to get the notification there on the second login

Test 3: no notification when using an actual recovery code to log in

Logging in repeatedly thereafter with both firefox and chrome using MFA+app only generates the notification intermittently, not every login. No pattern I could discern, every 3-4 logins it seemed.

**Comment by Joffcom** [comment]
@jbusuttil if I set you up a user on a test n8n instance could you try on that as well and let me know if you can reproduce the issue there as well?

**Comment by jbusuttil** [comment]
@Joffcom Happy to, let me know what you need me to do 👍

**Comment by Joffcom** [comment]
Hey @jbusuttil,

Good news, I am not sure how it happened but at some point over the weekend I got the same error. The only thing I noticed was I think the Version of firefox was a bit older. I am getting a new dev ticket made for this now so we can get to the bottom of it.

**Comment by NoLooseEnds** [comment]
Just chiming in that I also got this now without ever using a recovery code. 
I'm currently on v. 1.33.1 (selfhosted). Using Arc browser (chromium based) with 1Password.

**Comment by RicardoE105** [comment]
I have tried everything mentioned in the thread to replicate the issue, and I have not been able to. @jbusuttil @NoLooseEnds did you keep encountering this issue?

**Comment by jbusuttil** [comment]
The problem became much less frequent in the stable versions released around late January / early February (2024), then went away almost entirely in subsequent stable releases. I think I've only seen the message pop up literally once in the last couple of months as of time of writing.

**Comment by NoLooseEnds** [comment]
@RicardoE105 When I got the notification from github I tried to force the issue, but got rate limited on the login and did not have time to test until today. And I still get the error.

<img width="400" alt="Screenshot 2024-05-27 at 09 42 07" src="https://github.com/n8n-io/n8n/assets/4103531/a1f773e7-1cd3-41b5-9cb1-b78932fe19cd">

Running 1.41.0

**Comment by jbusuttil** [comment]
![image](https://github.com/n8n-io/n8n/assets/3918249/b764ceeb-3934-4eb6-a3a0-828d8f992132)

Triggered again for first time in a while for me

n8n self-host 1.42.1

Firefox 126.0.1 (64-bit, Windows 10)

**Comment by netroy** [comment]
I'm not certain if the bug was that the recovery codes were actually getting used up, or if the notification popup was incorrectly getting triggered, but for now the the code that triggered the notification has been removed since `1.45.0`.

I think we can close this issue for now. If someone finds an related issue with MFA, we can then re-open this.
