### ISSUE TITLE
Pagination with "Response contains next URL" erroring with Missing Authentication

### ISSUE THREAD

**Issue by pcxnet** [n8n-io/n8n#7937]
**Describe the bug**
Without pagination turned on, it works, but turning it on resuluts in error saying Missing Authentication, but console shows the auth header being sent.

**To Reproduce**
`{
  "meta": {
    "instanceId": "09ae26421a658d6d4bd137affcc05c36ff6c0d940d6ccd3c5f074ff305860878"
  },
  "nodes": [
    {
      "parameters": {
        "url": "=https://api.ento.com/au/api/shifts?filter[start_date]=2023-11-15&filter[end_date]=2023-11-15&page[size]=25",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/vnd.api+json"
            }
          ]
        },
        "options": {
          "response": {
            "response": {
              "responseFormat": "json"
            }
          },
          "pagination": {
            "pagination": {
              "paginationMode": "responseContainsNextURL",
              "nextURL": "=https://api.ento.com/au{{ $response.json.links.next}}",
              "limitPagesFetched": true,
              "maxRequests": 2
            }
          }
        }
      },
      "id": "0747f03b-d9b7-45b8-9b63-cfcca6a1a44b",
      "name": "getShifts",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        660,
        220
      ],
      "credentials": {
        "httpHeaderAuth": {
          "id": "74bSgPs38yQaQ3gh",
          "name": "Ento"
        }
      }
    }
  ],
  "connections": {}
}`
 I limited pages to 2 just to test.

**Expected behavior**
Cycles thru pages properly.

**Environment (please complete the following information):**

- OS: Docker 
- n8n Version 1.16.0

**Comment by Joffcom** [comment]
Hey @pcxnet,

Thanks for reporting this, it looks like this issue may have been fixed in `1.17.0` can you try updating your n8n instance and see if that helps.

**Comment by pcxnet** [comment]
Hi @Joffcom that didn't fix it, but i wonder if it has anything to do with the way the data is returned.
In the older version of the Http request, the data showed up properly, but in the new version of http request, the data looks like this 
![image](https://github.com/n8n-io/n8n/assets/16738529/1217e348-04e8-40fe-9ffd-740c648c28bc)

Unless I turn on 
Response Format - JSON

The dev console doesn't  show multiple requests so I can't see what its attempting to request, it only shows the initial one.

**Comment by Joffcom** [comment]
Hey @pcxnet,

Is it still showing that the authentication is missing?

Which version did you upgrade to in the end as well I can give it a test this morning when I start.

**Comment by pcxnet** [comment]
Hi @Joffcom  I tried 1.17.0 and now even 1.18.0 and both are doing the same thing .

![image](https://github.com/n8n-io/n8n/assets/16738529/d468e1de-918e-495c-a4c6-59dac4001e5a)

**Comment by pcxnet** [comment]
@Joffcom  yes this webhook.site test works fine. Can i give you access to my server or something via private message to look at it? I'm not sure exactly what is causing the problem.   Im wondering if its because the data isn't readable unless I tick the JSON response box, and its not being parsed before it reads the next page URL or something so its not finding URL or something? I'm not sure. I can screen share with you or whatever you need if you're available now.

**Comment by Joffcom** [comment]
Hey @pcxnet,

Ah it could be the `$response.json.links.next` actually, Can you remove the Content-Type header you are setting and see if that changes anything?

**Comment by pcxnet** [comment]
I get this still
![image](https://github.com/n8n-io/n8n/assets/16738529/1a5b1c27-9b8c-4bb8-9acd-adfc316bace4)

If i point the next URL to itself get this message, which makes me think its not getting the $response properly.
Without the header i get this message (which appens even without pagination)
![image](https://github.com/n8n-io/n8n/assets/16738529/94c0b0a0-937f-4df2-863b-d566c9dbad3a)
and with the content-type header back in, i get this 
![image](https://github.com/n8n-io/n8n/assets/16738529/d907e033-3e15-453d-8433-34e8bc2ae471)

**Comment by pcxnet** [comment]
With these settings
`{
  "meta": {
    "instanceId": "7286cb7af5e69b909e9502fd59ea92cbd7d4a06c840dc2904f09626675230c35"
  },
  "nodes": [
    {
      "parameters": {
        "url": "=https://api.ento.com/au/api/shifts?filter[start_date]=2023-11-15&filter[end_date]=2023-11-28&filter[area_id]=76715&page[size]=100",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "content-type",
              "value": "application/vnd.api+json"
            }
          ]
        },
        "options": {
          "response": {
            "response": {
              "responseFormat": "json"
            }
          }
        }
      },
      "id": "207e34ce-8469-4db6-bc0f-ccab43d11577",
      "name": "getShifts1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        640,
        -20
      ],
      "credentials": {
        "httpHeaderAuth": {
          "id": "60LbQtdK3HujKVwS",
          "name": "Ento"
        }
      }
    }
  ],
  "connections": {},
  "pinData": {}
}`
it returns 
![image](https://github.com/n8n-io/n8n/assets/16738529/98779dca-e608-4ff0-9f74-8b5e83094a68)

but without setting the type to JSON it returns
![image](https://github.com/n8n-io/n8n/assets/16738529/ac804626-0516-4364-8d70-c8a7c5e4244a)

I did try leaving the header as just application/json but it returns this
![image](https://github.com/n8n-io/n8n/assets/16738529/1d5c2cd2-0dbe-48a3-954a-f1378b52dd3d)


As you suggested
`{
  "meta": {
    "instanceId": "7286cb7af5e69b909e9502fd59ea92cbd7d4a06c840dc2904f09626675230c35"
  },
  "nodes": [
    {
      "parameters": {
        "url": "=https://api.ento.com/au/api/shifts?filter[start_date]=2023-11-15&filter[end_date]=2023-11-15&filter[area_id]=76715&page[size]=25",
        "authentication": "genericCredentialType",
        "genericAuthType": "httpHeaderAuth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "content-type",
              "value": "application/json"
            }
          ]
        },
        "options": {
          "response": {
            "response": {
              "responseFormat": "json"
            }
          },
          "pagination": {
            "pagination": {
              "paginationMode": "responseContainsNextURL",
              "nextURL": "=https://api.ento.com/au{{ JSON.parse($response.body.data).links. Next }}"
            }
          }
        }
      },
      "id": "207e34ce-8469-4db6-bc0f-ccab43d11577",
      "name": "getShifts1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        640,
        -20
      ],
      "credentials": {
        "httpHeaderAuth": {
          "id": "60LbQtdK3HujKVwS",
          "name": "Ento"
        }
      }
    }
  ],
  "connections": {},
  "pinData": {}
}`

Still returns
![image](https://github.com/n8n-io/n8n/assets/16738529/87fe0fb7-886c-44ef-a4ff-dcdf9a20be47)

**Comment by Joffcom** [comment]
We’re taking some time to review and tidy up our issue tracker. It looks like this issue hasn’t had any recent activity for the past 6 months. To keep our backlog focused on current priorities, we’re closing this issue for now.

That said, this doesn’t mean the issue is forgotten! If this is still relevant or you have more information to add, feel free to reopen it or create a new issue and we’d be happy to revisit it.

Thank you for understanding and for contributing to the project!
