### ISSUE TITLE
Zoho CRM: this.setDefaultStatusCodeMessage is not a function

### ISSUE THREAD

**Issue by sprankhub** [n8n-io/n8n#8508]
**Describe the bug**
On certain Zoho CRM API errors, no proper error message is shown. Instead, the error message `this.setDefaultStatusCodeMessage is not a function` is shown:

![image](https://github.com/n8n-io/n8n/assets/930199/a09bea0a-b81a-4a08-ba45-d84590fe78f9)

**To Reproduce**

1. Add a new workflow, which syncs all your Google Contacts with Zoho CRM:

        {
          "meta": {
            "templateCredsSetupCompleted": true,
            "instanceId": "..."
          },
          "nodes": [
            {
              "parameters": {
                "resource": "contact",
                "operation": "upsert",
                "lastName": "={{ $json[\"names\"][\"familyName\"] }}",
                "additionalFields": {
                  "customFields": {
                    "customFields": [
                      {
                        "fieldId": "Lead_Quelle",
                        "value": "={{ [\"Google Kontakte\"] }}"
                      }
                    ]
                  },
                  "Email": "={{ $json[\"emailAddresses\"][Object.keys($json[\"emailAddresses\"])[0]][0] }}",
                  "Secondary_Email": "={{ $json[\"emailAddresses\"][Object.keys($json[\"emailAddresses\"])[1]][0] }}",
                  "First_Name": "={{ $json.names.givenName }}",
                  "Mobile": "={{ $json.phoneNumbers.mobile[0] }}",
                  "Phone": "={{ $json[\"phoneNumbers\"][\"work\"] ? $json[\"phoneNumbers\"][\"work\"][0] : $json[\"phoneNumbers\"][Object.keys($json[\"phoneNumbers\"])[0]][0] }}",
                  "Home_Phone": "={{ $json.phoneNumbers.home[0] }}"
                }
              },
              "id": "...",
              "name": "Zoho CRM",
              "type": "n8n-nodes-base.zohoCrm",
              "typeVersion": 1,
              "position": [
                1280,
                360
              ],
              "credentials": {
                "zohoOAuth2Api": {
                  "id": "...",
                  "name": "Zoho account"
                }
              }
            }
          ],
          "connections": {},
          "pinData": {}
        }
2. Execute the workflow.

**Expected behavior**
I expected the workflow to be executed without any error or, if there is an error, I expected a proper error message / display.

**Environment (please complete the following information):**

- OS: Cloud
- n8n Version 1.25.1
- Node.js Version Cloud
- Database system Cloud
- Operation mode I don't know?

**Additional context**

**Comment by sprankhub** [comment]
Nice, thanks for your fast fix, @netroy! Any idea when there will be a bugfix release due to this? It is quite hard to fix workflows not knowing what is wrong :joy:

**Comment by netroy** [comment]
> Any idea when there will be a bugfix release due to this?

`1.27.0` Should be out in the next hour. And if we find any major issues in there, we'll consider creating a `1.26.1` patch.

**Comment by sprankhub** [comment]
Nice, it's released. Any idea when this is rolled out to the cloud version, @netroy?

**Comment by sprankhub** [comment]
@netroy, I updated to 1.27.2 now and tested my workflow again. The error display didn't improve a lot, to be honest:

![image](https://github.com/n8n-io/n8n/assets/930199/2e8ea445-c570-4eba-8c36-f578df7443b2)

This is the full stack:

    NodeApiError: [RE-WRAPPED]: 
        at Object.zohoApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Zoho/GenericFunctions.js:49:15)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Zoho/ZohoCrm.node.js:321:40)
        at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:706:19)
        at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:656:53
        at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1058:20

Could you please check this issue one more time?

**Comment by netroy** [comment]
Sorry about this.
#8510 did fix a JS error, and that's why the error message has changed here.

But, looks like there is some error from Zoho, that's getting re-wrapped for no good reason the code. 
I've created a custom image that might help debug this. Can you please try running with the image `n8nio/n8n:debug-8508`, and let me know what error you get this time? 🙏🏽

**Comment by sprankhub** [comment]
Thanks for your support, @netroy! I would love to, but since we currently use the cloud version, it is not really easy to do for me. I guess there is no way to switch to that image in the cloud version, right?
What's the easiest way to shortly host this myself and to import the workflow with the issue (including credentials) in this temporary instance?

**Comment by sprankhub** [comment]
@netroy, could you provide some further support here? I am currently unsure how we can solve this together.

**Comment by netroy** [comment]
Can you please send me your cloud account name?

**Comment by sprankhub** [comment]
customgento :)

**Comment by netroy** [comment]
Can you please try running the workflow again?

**Comment by sprankhub** [comment]
Done. Error message: "Problem in node ‘Zoho CRM‘". If it helps and it is safe to share, there is also a console error I can post...

**Comment by sprankhub** [comment]
Refreshed and executed. Did that help?

**Comment by netroy** [comment]
unfortunately the error handling in this node is a bit of a mess, and I forgot to explicitly log the error response from Zoho.
All I can tell is that there is an API error from Zoho, and this node isn't doing a good job of bringing that error up to the UI.
Creating a new image with more logging now. Will ping you back once it is deployed.

**Comment by netroy** [comment]
@sprankhub Can you try one more time please 🙏🏽 ?

**Comment by sprankhub** [comment]
Done, @netroy!

**Comment by netroy** [comment]
Did you get any more error related into in the UI?

In the console I got this:
```
{"data":[{"code":"INVALID_DATA","details":{"expected_data_type":"phone","api_name":"Phone"},"message":"invalid data","status":"error"}]}
```

I'm not familiar with Zoho API, but I'm assuming that they are doing some kind of input validation on a phone number field, and the value you are sending is invalid.

**Comment by sprankhub** [comment]
@netroy, any chance to forward this message to the UI? I only get "UNKNOWN ERROR - check the detailed error for more information", but there is no detailed error :D
It would be great if it was reporting the invalid data and the concrete error message.

**Comment by netroy** [comment]
Yeah, this is tech-debt. I've created an internal ticket to track this: `ENG-100`.

**Comment by sprankhub** [comment]
Thanks, @netroy! Could you give me an idea how this will evolve? Is this a matter of weeks, months or years? How can I follow the progress?

**Comment by sprankhub** [comment]
@netroy, could you please give me some information on this? Thanks!

**Comment by netroy** [comment]
parts of this is already being addressed in #8644.
but I unfortunately I don't have any more information to share, and neither can I provide a timeline at this moment.

**Comment by sprankhub** [comment]
#8644 has now already been merged for some time. I am currently using version 1.36.4. However, my Zoho node still doesn't show a proper error from the API, but just generic n8n information instead:

![image](https://github.com/n8n-io/n8n/assets/930199/f03656c9-84da-4855-969a-fa0f37fc4441)

@netroy, would you be able to have another look at this? I don't think this issue should be closed as the underyling issue is not fixed yet. Should I open a new ticket instead?

**Comment by netroy** [comment]
The `this.setDefaultStatusCodeMessage is not a function` issue is definitely resolved. However we still have an issue that we are not showing all the details in response errors on the UI.
We are working on improving this, but don't have a clear deadline.
If you know the Zoho endpoint that your node needs to talk to, can you please try using a HTTP node with the same credential instead? That should show you more details on what exactly is failing.

**Comment by sprankhub** [comment]
@netroy, thanks, I tried this, but I keep getting a credential issue when I use the same Zoho credentials in a generic HTTP node:

    {"code":"INVALID_TOKEN","details":{},"message":"invalid oauth token","status":"error"}

**Comment by sprankhub** [comment]
Okay the `INVALID_TOKEN` issue happened, because I used zohoapis.com instead of zohoapis.eu. Pity that there is not a better error message for this.

And now that I ran a simple HTTP node instead of the Zoho node, I also got the full error:

    {"code":"TOO_MANY_REQUESTS","details":{},"message":"Many requests fired in concurrent than the allowed limit.","status":"error"}

The issue is that I send one API request to Zoho for each result. Instead, it would be better to only send one API request to Zoho for all results at once. I am not sure how to implement that yet. I'll need to have a closer look.
