### ISSUE TITLE
Rabbit MQ triggers do not work in test mode

### ISSUE THREAD

**Issue by DRIMOL** [n8n-io/n8n#8871]
### Bug Description

A - Does not pull the item from the queue in test mode

B - If you write a message to a queue that does not exist, it returns an error.
       ERROR: Operation failed: QueueDeclare; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'test_queue' in vhost 'default'

### To Reproduce

A1 - adicione uma nova mensagem no rabbit mq
A2 - coloque o triggers em modo de escuta

A PS: No painel do rabbit MQ a messagem entra em Unacked, mas, no workflow do n8n nada acontece

B1 - try to write a message to a queue that doesn't exist

### Expected behavior

A - Test message reception by rabbit MQ

B - Create new queues through the RabbitMQ node

### Operating System

UbuntoLinux 20

### n8n Version

1.31.2

### Node.js Version

v18.19.1

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @DRIMOL,

Thanks for reporting this, I have created `NODE-1230` as the ticket to fix the bug, With the second one I would expect it to fail if the queue doesn't exist as we don't set the option to create it.

If you want us to add this I would recommend creating a feature request on the community support forum and we can track the popularity of this and look at adding it in the future.

**Comment by DRIMOL** [comment]
I thought it was a BUG, ​​because in version 1.24.1 it creates the queue if it doesn't exist.

Thanks

**Comment by Joffcom** [comment]
Hey @DRIMOL,

That was some important information that was missing... Looking at the release this was changed in 1.28.0 with this PR: https://github.com/n8n-io/n8n/pull/8430 and it looks like I missed that the change was not added to the standard node.

I will get that fixed shortly for the next release.

**Comment by DRIMOL** [comment]
Where can I track the progress?

**Comment by Joffcom** [comment]
Hey @DRIMOL,

This is the best place to check, Once fixed we will put a note on here to let you know. You can also keep an eye on the PR list to see if any of them contain `node-1230`.

Right now this is sat with a high priority and is waiting to be picked up.

**Comment by barn4k** [comment]
Actually, better to have an option like "Create if no queue" to avoid misconfigurations.

But I can imagine only one scenario when it might be needed - If someone by mistake has deleted a queue

**Comment by barn4k** [comment]
Hey @Joffcom , bug with the 404 instead of creating a queue is still there...

**Comment by Joffcom** [comment]
I have created a PR to fix the queue creation, Oddly enough when testing I noticed that running in test mode is working as well. @DRIMOL / @barn4k are you able to check on 1.41.0 to see if the test execution is working for an existing queue?

**Comment by Joffcom** [comment]
Thanks to a quick review from @netroy it looks like the option to make the queue is there already under Add Option > Assert Queue. This should resolve the issue of the queue not being created automatically.

**Comment by barn4k** [comment]
> I have created a PR to fix the queue creation, Oddly enough when testing I noticed that running in test mode is working as well. @DRIMOL / @barn4k are you able to check on 1.41.0 to see if the test execution is working for an existing queue?

Well, I can't check it right now as the latest docker version is 1.39.1 :)

**Comment by DRIMOL** [comment]
> > I have created a PR to fix the queue creation, Oddly enough when testing I noticed that running in test mode is working as well. @DRIMOL / @barn4k are you able to check on 1.41.0 to see if the test execution is working for an existing queue?
> 
> Well, I can't check it right now as the latest docker version is 1.39.1 :)

here it is also loading infinite
![Captura de Tela 2024-05-16 às 15 40 30](https://github.com/n8n-io/n8n/assets/47779716/231b7316-f6e4-46cd-b65f-45d5083eef14)
 na versão 1.41.0

**Comment by DRIMOL** [comment]
> Thanks to a quick review from @netroy it looks like the option to make the queue is there already under Add Option > Assert Queue. This should resolve the issue of the queue not being created automatically.

yes, it already exists in the trigger, but the interesting thing would be if it was in the "Send a Message to RabbitMQ", because then we would be able to create queues dynamically.

**Comment by DRIMOL** [comment]
Será que ainda vão resolver ? 😞

**Comment by luizeof** [comment]
@Joffcom Setting Up `N8N_LOG_LEVEL=verbose` I can see the error that happens when the rabbit trigger is started:

```
2024-06-06T22:56:04.076Z | error    | There was a problem with the RabbitMQ Trigger node "RabbitMQ Trigger" in workflow "hAKRgkvpANXAoSTW": "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function" "{\n  node: 'RabbitMQ Trigger',\n  workflowId: 'hAKRgkvpANXAoSTW',\n  file: 'LoggerProxy.js',\n  function: 'exports.error'\n}"
```

**Comment by ramonmatosweb** [comment]
[n8n20ylvns_n8n20ylvns_logs.txt](https://github.com/user-attachments/files/15687583/n8n20ylvns_n8n20ylvns_logs.txt)

**Comment by Joffcom** [comment]
This will be fixed very soon.

**Comment by DRIMOL** [comment]
> This will be fixed very soon.

I would like to add a bug that I noticed these days also about the rabbit

If I inactivate or delete an n8n flow where there is a rabbit trigger, the consumer is not automatically deleted from the rabbit, and continues to be sent to a ghost consumer, even though it has been deleted, the problem is only solved by updating n8n with prune , by doing this he excludes ghost consumers.

**Comment by netroy** [comment]
> If I inactivate or delete an n8n flow where there is a rabbit trigger, the consumer is not automatically deleted

When you deactivate the workflow, do you see any error in the container logs saying something like `There was a problem closing the RabbitMQ Trigger node connection`?

**Comment by DRIMOL** [comment]
> > If I inactivate or delete an n8n flow where there is a rabbit trigger, the consumer is not automatically deleted
> 
> When you deactivate the workflow, do you see any error in the container logs saying something like `There was a problem closing the RabbitMQ Trigger node connection`?

I will try to check if I should look at this log in the n8n workers or in the RabbitMQ container?

**Comment by netroy** [comment]
> I will try to check if I should look at this log in the n8n workers or in the RabbitMQ container?

Please check in the n8n worker logs.

**Comment by DRIMOL** [comment]
I tried to catch the bug here, but it excluded the consumer, it could have happened because the queue had a stuck message, for example when "parse json" is marked and the message arrives outside of the json format, in this case or something similar does not exclude, but by deleting a trigger that is "healthy" here the consumers were excluded from the rabbit

**Comment by ianpogi5** [comment]
> @Joffcom Setting Up `N8N_LOG_LEVEL=verbose` I can see the error that happens when the rabbit trigger is started:
> 
> ```
> 2024-06-06T22:56:04.076Z | error    | There was a problem with the RabbitMQ Trigger node "RabbitMQ Trigger" in workflow "hAKRgkvpANXAoSTW": "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function" "{\n  node: 'RabbitMQ Trigger',\n  workflowId: 'hAKRgkvpANXAoSTW',\n  file: 'LoggerProxy.js',\n  function: 'exports.error'\n}"
> ```

Same error as mine

**Comment by netroy** [comment]
> "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function"

This error makes me wonder if the `node_modules` package is somehow tampered.

@ianpogi5 Are you running n8n on docker? and do you have any custom or community nodes installed?

**Comment by ianpogi5** [comment]
> > "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function"
> 
> This error makes me wonder if the `node_modules` package is somehow tampered.
> 
> @ianpogi5 Are you running n8n on docker? and do you have any custom or community nodes installed?

We are using docker version.

**Comment by netroy** [comment]
> We are using docker version.

and do you have any custom or community nodes installed?

**Comment by ianpogi5** [comment]
> > We are using docker version.
> 
> and do you have any custom or community nodes installed?

Yes we have 1 which is the netsuite node. We don't use then together on the same flow if that matters.

**Comment by netroy** [comment]
`n8n-nodes-netsuite` is [pulling in a really old version of `n8n-core`](https://github.com/drudge/n8n-nodes-netsuite/blob/main/package.json#L69), and likely messing with the core functionality. Can you please try uninstalling the node, restarting n8n, and checking if that fixes the issue?
If it does, I can send a PR to `n8n-nodes-netsuite` to update their code.

**Comment by netroy** [comment]
With the `assertQueue` option enabled, I'm able to create new queue automatically, and receive messages on the latest release.

```json
{
  "nodes": [
    {
      "parameters": {
        "queue": "testing",
        "options": {
          "assertQueue": true
        }
      },
      "id": "9aaaac85-7c0d-4d8f-9cc4-098544bb16ac",
      "name": "RabbitMQ Trigger",
      "type": "n8n-nodes-base.rabbitmqTrigger",
      "typeVersion": 1,
      "position": [
        720,
        380
      ],
      "credentials": {
        "rabbitmq": {
          "id": "xyz",
          "name": "RabbitMQ account"
        }
      }
    }
  ],
  "connections": {}
}
```

**Comment by ianpogi5** [comment]
> `n8n-nodes-netsuite` is [pulling in a really old version of `n8n-core`](https://github.com/drudge/n8n-nodes-netsuite/blob/main/package.json#L69), and likely messing with the core functionality. Can you please try uninstalling the node, restarting n8n, and checking if that fixes the issue? If it does, I can send a PR to `n8n-nodes-netsuite` to update their code.

We did your instructions and got the same error.

**Comment by netroy** [comment]
I need a way to reproduce this, to be able to fix this. Are you able to reproduce this on a new n8n instance, with a minimal workflow?

**Comment by ianpogi5** [comment]
> I need a way to reproduce this, to be able to fix this. Are you able to reproduce this on a new n8n instance, with a minimal workflow?

Here's my workflow:

```json
{
  "name": "RabbitMQ test",
  "nodes": [
    {
      "parameters": {},
      "id": "f8f644e7-754e-44e1-a013-01dc0b309d8e",
      "name": "When clicking ‘Test workflow’",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        440,
        500
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "4c738ba4-d63b-4196-9297-e71e1f45ebca",
              "name": "name",
              "value": "Hello world!",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "d8530558-9790-4966-b529-0ae36ed22966",
      "name": "Edit Fields",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        680,
        500
      ]
    },
    {
      "parameters": {
        "queue": "n8n-test",
        "options": {}
      },
      "id": "cce5f6c4-bb8a-4307-86a5-9c454a7b1349",
      "name": "RabbitMQ",
      "type": "n8n-nodes-base.rabbitmq",
      "typeVersion": 1.1,
      "position": [
        940,
        500
      ],
      "credentials": {
        "rabbitmq": {
          "id": "poc4UQ08c1GLjORk",
          "name": "RabbitMQ account"
        }
      }
    },
    {
      "parameters": {
        "queue": "n8n-test",
        "options": {}
      },
      "id": "09021137-6b9f-48d7-b500-8989f2247359",
      "name": "RabbitMQ Trigger",
      "type": "n8n-nodes-base.rabbitmqTrigger",
      "typeVersion": 1,
      "position": [
        600,
        820
      ],
      "credentials": {
        "rabbitmq": {
          "id": "poc4UQ08c1GLjORk",
          "name": "RabbitMQ account"
        }
      }
    },
    {
      "parameters": {
        "operation": "deleteMessage"
      },
      "id": "09bf2dc7-8c18-4eae-941e-c7c6ed60c94a",
      "name": "RabbitMQ1",
      "type": "n8n-nodes-base.rabbitmq",
      "typeVersion": 1.1,
      "position": [
        820,
        820
      ],
      "credentials": {
        "rabbitmq": {
          "id": "poc4UQ08c1GLjORk",
          "name": "RabbitMQ account"
        }
      }
    }
  ],
  "pinData": {},
  "connections": {
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields": {
      "main": [
        [
          {
            "node": "RabbitMQ",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "RabbitMQ Trigger": {
      "main": [
        [
          {
            "node": "RabbitMQ1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  },
  "versionId": "09d1bd6f-6980-482e-80a7-76d1fbf65830",
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "1b06549ea40930d40bbf0844d3f62a7083d8cbe5e465acde61c9b6fda9870a55"
  },
  "id": "sSFuUAFfIUkqbU7l",
  "tags": []
}
```

**Comment by ianpogi5** [comment]
I'm not sure if this is related but the RabbitMQ trigger icon is broken.

![Screenshot from 2024-07-09 06-09-38](https://github.com/n8n-io/n8n/assets/1063875/8a66fcdc-cfc2-4c3e-b105-114a7d6f2501)

**Comment by netroy** [comment]
> RabbitMQ trigger icon is broken.

This was fixed [2 weeks ago ](https://github.com/n8n-io/n8n/pull/9844). Are you on an older version?

**Comment by ianpogi5** [comment]
> > RabbitMQ trigger icon is broken.
> 
> This was fixed [2 weeks ago ](https://github.com/n8n-io/n8n/pull/9844). Are you on an older version?

I just upgraded from 1.47.3 from 1.47.2 just now and still got the same error and broken rabbitmq trigger icon(points to png which should be svg just like the action). Disabled browser cache with same error.

**Comment by Joffcom** [comment]
Hey @ianpogi5 

The icon issue has been fixed can you try 1.48.0?

**Comment by ianpogi5** [comment]
> Hey @ianpogi5
> 
> The icon issue has been fixed can you try 1.48.0?

I have upgraded to 1.48.3. I confirm the icon issue now fixed. But the rabbitmq trigger in test mode is still not working. 

Btw after upgrade, I tested the trigger. When I clicked "Test step" button, I see that it creates a consumer connection on rabbitmq. When I click "Stop Listening" in the trigger, the consumer connection doesn't go away. If I do it again, it will again create a new consumer. I think this may point us to where the issue is.

![Screenshot from 2024-07-09 17-23-58](https://github.com/n8n-io/n8n/assets/1063875/5c76a886-21aa-4d0a-beda-cde306a608c5)

**Comment by netroy** [comment]
I think the issue might be that when we start manually testing a trigger node, and stop it before the node is actually triggered, we were not calling the cleanup function on that node. 
This meant that you could end up with open connections and message consumers that could not actually create any executions, but still kept accepting messages.

I've tried to address this in #9980, and created a custom docker image `n8nio/n8n:fix-8871`.
Can one of you please also pull this docker image and check if this resolves the issue for you?
We can then try to get this merged and released tomorrow 🤞🏽

**Comment by ianpogi5** [comment]
> I think the issue might be that when we start manually testing a trigger node, and stop it before the node is actually triggered, we were not calling the cleanup function on that node. This meant that you could end up with open connections and message consumers that could not actually create any executions, but still kept accepting messages.
> 
> I've tried to address this in #9980, and created a custom docker image `n8nio/n8n:fix-8871`. Can one of you please also pull this docker image and check if this resolves the issue for you? We can then try to get this merged and released tomorrow 🤞🏽

I confirm that the open connections is now gone after I click the stop listening. Thank you very much!

But testing mode still does not work. When clicking test step button, I immediately see in the logs  "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function". Then I would see in RabbitMQ that it did got a message:

![Screenshot from 2024-07-10 06-25-59](https://github.com/n8n-io/n8n/assets/1063875/0d0cc523-2865-4e38-a97f-24c8caf64e24)

The Unackowledge becomes 1 but the trigger is still listening. I expect it would stop listening and show the data in output section just like other types of nodes. Let me know if this is correct expectation. When I stop listening, Unack becomes 0 and Ready goes back to 3.

**Comment by ianpogi5** [comment]
I also tried the option "Delete From Queue When" but same resut.

![Screenshot from 2024-07-10 06-53-05](https://github.com/n8n-io/n8n/assets/1063875/a6f070cd-640c-4012-8a09-4625ce6ecf10)

**Comment by ianpogi5** [comment]
> `n8n-nodes-netsuite` is [pulling in a really old version of `n8n-core`](https://github.com/drudge/n8n-nodes-netsuite/blob/main/package.json#L69), and likely messing with the core functionality. Can you please try uninstalling the node, restarting n8n, and checking if that fixes the issue?
> 
> If it does, I can send a PR to `n8n-nodes-netsuite` to update their code.

@netroy thank you for all your help but it would also be great if you can do a PR on 'n8n-nodes-netsuite'.

**Comment by netroy** [comment]
> it would also be great if you can do a PR on 'n8n-nodes-netsuite'

https://github.com/drudge/n8n-nodes-netsuite/pull/6

**Comment by luizeof** [comment]
@netroy In version 1.52 the Rabbit Trigger node still does not work.

The connection is opened, the queue item is set to unaked but is not displayed in the N8N interface.

All tests give the same log:

```
2024-07-24T13:25:00.777Z | error    | There was a problem starting the waiting execution with id "67138": "Only saved workflows can be resumed." "{ executionId: '67138', file: 'WaitTracker.js' }"
2024-07-24T13:25:14.038Z | info     | Started with job ID: 12754 (Execution ID: 415956) "{ file: 'WorkflowRunner.js', function: 'enqueueExecution' }"
2024-07-24T13:25:29.042Z | info     | Started with job ID: 12755 (Execution ID: 415957) "{ file: 'WorkflowRunner.js', function: 'enqueueExecution' }"
2024-07-24T13:25:29.195Z | info     | Started with job ID: 12756 (Execution ID: 415954) "{ file: 'WorkflowRunner.js', function: 'enqueueExecution' }"
```

**Comment by Joffcom** [comment]
Hey @luizeof,

I have just given this a test and I can confirm it is working in 1.52

![image](https://github.com/user-attachments/assets/7d16e9e4-a37f-40a3-b0c7-c47ce7e81a91)

Are you able to share your full workflow and how you have n8n configured as it may be something else, In your log snippet which like is for the RabbitMQ test are you also testing this with a wait?

**Comment by luizeof** [comment]
Simple Workflow

The Workflow only has the Rabbit node to isolate the test

![image](https://github.com/user-attachments/assets/0d8935eb-b174-4409-972d-de0f4b913e13)

The connection is made in rabbit and the item is fetched

![image](https://github.com/user-attachments/assets/b8bf1873-b068-4791-9702-2121889b6029)

But it is not displayed on the interface.

Using the n8n next docker image, without custom nodes.

This message is displayed in the editor container, no error message appears in the worker:

```
2024-07-24T15:24:30.918Z | error    | There was a problem with the RabbitMQ Trigger node "RabbitMQ Trigger" in workflow "REOOmdtQpPJGaTCZ": "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function" "{\n  node: 'RabbitMQ Trigger',\n  workflowId: 'REOOmdtQpPJGaTCZ',\n  file: 'LoggerProxy.js',\n  function: 'exports.error'\n}"
```

**Comment by netroy** [comment]
@luizeof Can you reproduce this error right after restarting the instance?

**Comment by netroy** [comment]
`Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit` error would me that you somehow have an open consumer from a previous manual execution or a previous activation, so something is picking up messages, but that something doesn't have access to the execution context anymore.

This was the exact same thing we fixed in #9980 . So, it's a little perplexing that you are still seeing this 😕

**Comment by ianpogi5** [comment]
I updated to 1.52.0 and got all the same results as @luizeof

**Comment by luizeof** [comment]
Hi Jon and Ian, I did a new installation from scratch with the `next` image.

Same error, but @Joffcom, in the interface I get a message in the console that could be the problem:

![Captura de tela 2024-07-26 094933](https://github.com/user-attachments/assets/2fed1759-8072-41c0-ae0a-7f613898c8c4)

This installation has 1 workflow that has 1 Rabbit Trigger, this message appears as soon as the message is obtained by Rabbit.

![Captura de tela 2024-07-26 095128](https://github.com/user-attachments/assets/efdb3ebd-db66-4f8b-852f-e0d34210722f)

The message is obtained in the rabbit, so that it remains as Unaked. It is just not displayed in the interface itself.

![Captura de tela 2024-07-26 095158](https://github.com/user-attachments/assets/b8d38313-2a18-41ff-808a-0bfa8ad34237)

**Comment by barn4k** [comment]
Same issue as @luizeof .

My WF setup:
RMQ trigger node with new queue name, assert queue option is enabled. I've run it in the Test mode, then created another WF to send two pinned items there The first item from it has been collected by the trigger. I've hit the Test mode again and nothing happend. The second item wasn't return and the trigger seems stuck.

Log:
`2024-07-30 14:00:39 2024-07-30T12:00:39.509Z | error    | There was a problem with the RabbitMQ Trigger node "RabbitMQ Trigger" in workflow "2FK2S1aHYGZakNNj": "Overwrite NodeExecuteFunctions.getExecuteTriggerFunctions.emit function" "{\n  node: 'RabbitMQ Trigger',\n  workflowId: '2FK2S1aHYGZakNNj',\n  file: 'LoggerProxy.js',\n  function: 'exports.error'\n}"`

compose file:
```yaml
version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=password1
    ports:
      - "5672:5672"
      - "15672:15672"
  n8n:
    image: n8nio/n8n:next
    container_name: n8n_next
    environment:
    - N8N_LOG_LEVEL=debug
    - N8N_LOG_OUTPUT=console,file
    - N8N_SECURE_COOKIE=false
    - RMQIP=rabbitmq
    ports:
    - "5678:5678"
    links:
    - rabbitmq
    volumes:
    - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

networks:
  default:
    driver: bridge
```

Trigger WF
```
{
  "meta": {
    "instanceId": "83e1030ad7804421d85e8d13f129b137363ab1ab458054d2a70d6e10b31bf02d"
  },
  "nodes": [
    {
      "parameters": {
        "queue": "myQueue",
        "options": {
          "assertQueue": true
        }
      },
      "id": "26b6e33c-73f5-46f5-97c4-401e437a24e3",
      "name": "RabbitMQ Trigger",
      "type": "n8n-nodes-base.rabbitmqTrigger",
      "typeVersion": 1,
      "position": [
        840,
        420
      ],
      "credentials": {
        "rabbitmq": {
          "id": "RBxe6tOmcdBzIwhT",
          "name": "RabbitMQ account"
        }
      }
    }
  ],
  "connections": {},
  "pinData": {}
}
```

Sample WF
```
{
  "meta": {
    "instanceId": "83e1030ad7804421d85e8d13f129b137363ab1ab458054d2a70d6e10b31bf02d"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "1e6ef7de-c305-4329-8a99-2bbce7530801",
      "name": "When clicking ‘Test workflow’",
      "type": "n8n-nodes-base.manualTrigger",
      "position": [
        820,
        380
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "queue": "myQueue",
        "options": {}
      },
      "id": "3154b647-0c0b-411e-89c8-7c4f0ef37ff3",
      "name": "RabbitMQ",
      "type": "n8n-nodes-base.rabbitmq",
      "typeVersion": 1.1,
      "position": [
        1000,
        380
      ],
      "credentials": {
        "rabbitmq": {
          "id": "RBxe6tOmcdBzIwhT",
          "name": "RabbitMQ account"
        }
      }
    }
  ],
  "connections": {
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "RabbitMQ",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "When clicking ‘Test workflow’": [
      {
        "name": "First item",
        "code": 1
      },
      {
        "name": "Second item",
        "code": 2
      }
    ]
  }
}
```

**Comment by netroy** [comment]
I'm finally able to reproduce this.
1. put a message in the queue
2. manually test the rabbitmq trigger node

This fails because we are starting the rabbitmq consumer before `.emit` is assigned to `triggerResponse` [here](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/Workflow.ts#L1152).
When there are no messages in the queue before a manual trigger, `.emit` gets assigned correctly though.
So to fix this we need to make sure that the either the consumer starts after the `.emit` assignment, or consumer starts whenever, but calls `.emit` only after the assignment.

**Comment by galdianoo** [comment]
hello, any time line to fix the bug in this node?

**Comment by stephen-galea-weavr** [comment]
Any update on this please? It's a pain to design workflows without test mode.

**Comment by netroy** [comment]
This will be fixed in #10663

**Comment by janober** [comment]
Fix got released with [`n8n@1.58.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.58.0)

**Comment by stephen-galea-weavr** [comment]
Thank you!
