### ISSUE TITLE
IMAP Trigger Node Binary File Attachments Corrupted

### ISSUE THREAD

**Issue by darrengoldner** [n8n-io/n8n#9313]
### Bug Description

Beginning around approximately commit 9f87cc2, all binary files retrieved from the IMAP trigger nodes in my workflow are overstated by approximately 2X.

### To Reproduce

Create a new IMAP trigger node with credentials to any IMAP mailbox with file attachments.
Test trigger with filter criteria that include a message with attachments.
Compare binary data for attachment(s) vs expectactions

### Expected behavior

Binary file attachments should be retrieved exactly as they are represented in the IMAP mailbox.

### Operating System

Ubuntu 22.04.3 LTS

### n8n Version

1.38.2

### Node.js Version

18.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @darrengoldner,

Are the files actually bigger and corrupted or do we just show a larger size in the UI?

**Comment by darrengoldner** [comment]
Bigger and corrupted

**Comment by Joffcom** [comment]
@darrengoldner I have managed to reproduce and have created `NODE-1344` as the internal ticket to fix this.

**Comment by darrengoldner** [comment]
would it be possible to merge this fix into the `Latest` release? It was in [1.41.1](https://github.com/n8n-io/n8n/compare/n8n@1.41.0...n8n@1.41.1) and then we moved up to [1.42.1](https://github.com/n8n-io/n8n/compare/n8n@1.42.0...n8n@1.42.1) on latest track. Or is there a timeline for one of the latter minor versions which have the patch to become the latest?

**Comment by netroy** [comment]
this fix should already be in the latest release. are you still seeing this issue ?

**Comment by darrengoldner** [comment]
Yes. AFAICT the behavior returned in `1.42.1`. It had been resolved in `1.41.1`

**Comment by webkp** [comment]
Same here. Still seeing this issue with `1.42.1` (but can not tell if it was solved with `1.41.1`). 
In my case the problem is with .wav files (but did not test other files)

**Comment by Joffcom** [comment]
That is very odd, The change from `1.41.1` should be in `1.42.1`, I will give it a quick test now and see if it is still an issue on `1.44.0`

**Comment by webkp** [comment]
@darrengoldner in case you are using a more recent version of n8n now: do you still encounter the problem? I switched to a community imap-node to to circumvent the problem for the moment until the problem is solved but I would like to use again n8n's core node instead of external ones once it is all working well.

**Comment by netroy** [comment]
I haven't managed to reproduce this issue. What IMAP server are you folks seeing the issue with?

**Comment by webkp** [comment]
Did you try with `1.42.1` @netroy ? I'll see if I can do an update the next couple days and try again.

**Comment by netroy** [comment]
I have only tried to reproduce this on the latest code. Can you please try one of the newer releases to see if the issue is fixed now? 🙏🏽

**Comment by netroy** [comment]
Hey folks, is this still happening for any of you in a newer release?

**Comment by netroy** [comment]
I'll close this for now. If someone reports this to still be a bug in the latest release, we can re-open.
