### ISSUE TITLE
HTTP node Max Pages expression ignored

### ISSUE THREAD

**Issue by NilsW86** [n8n-io/n8n#9597]
### Bug Description

When using a JS expression in the "Max Pages" parameter (in Pagination/Limit Pages Fetched) in a HTTP Request node the limit is ignored. Any expression including {{ 2 }} can be used and it is still ignored so it is not due to the data not being available. Others have been experiencing the same thing:
https://community.n8n.io/t/need-some-help-with-http-request-node-pagination-using-max-pages-expression/39449

### To Reproduce

- Add a HTTP Request node
- Connect to any API with pagination
- Add option/pagination
- Activate Limit Pages Fetched
- Change Max Pages to expression and input {{ 2 }} or any other value to test
- Test the step
- The limit will be ignored and all pages will be fetched

### Expected behavior

The expected behavior would be that an expression with {{ 2 }} would limit the pages fetched like a Fixed 2 would.

### Operating System

n8n cloud

### n8n Version

1.42.1

### Node.js Version

The one n8n cloud is using

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @NilsW86,

Thanks for the report I have managed to reproduce this and have created `NODE-1387` as the internal ticket to get this resolved.

**Comment by elsmr** [comment]
Hi @NilsW86 this has been fixed in the linked PR and will be released next week!

**Comment by janober** [comment]
Fix got released with [`n8n@1.53.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.0)

**Comment by NilsEle** [comment]
Hi @Joffcom @elsmr and @janober ,

I think the bug is still present although slightly different. I am now on the cloud version 1.55.3. I have this test case:
![image](https://github.com/user-attachments/assets/cb191aef-3908-4c5d-a9c4-2ca6430a761e)

This data is pinned to the manual node:
[
  {
    "filter": {
      "country": "xyz",
      "categories": [
        "x",
        "y"
      ],
      "contactLimit": 2,
      "pageLimit": 3
    }
  }
]

My HTTP node works great when using "Max pages" as "Fixed" and input 3. It also works with a expression of {{ 3 }}. However, it does not work with the expression {{ $json.filter.pageLimit }}. I am 100% sure that the data is available, I can even see that n8n can identify it:
![image](https://github.com/user-attachments/assets/ded5fda4-a48f-48c8-a963-9df64cdca1ab)

But when executing with {{ $json.filter.pageLimit }} instead of {{ 3 }}, I get an error. It says "No execution data available" even though it is:
![image](https://github.com/user-attachments/assets/4c19aff6-0151-48a9-ab95-235f11f4aedf)

Meaning that it can still not handle a proper input parameter. I have also tried adding a set node before with a different parameter, not working either. Can you confirm that you can reproduce or so you need more information?

Thanks!

**Comment by janober** [comment]
Fix got released with [`n8n@1.61.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.61.0)
